### ISSUE TITLE
GitLab commit build statuses not updating via updateGitlabCommitStatus on protected branches

### ISSUE THREAD

**Issue by katanacrimson** [jenkinsci/gitlab-plugin#1045]
## Issue

Jenkins builds using the plugin's `updateGitlabCommitStatus ` are no longer updating GitLab commits with the correct status information on protected branches.

### Context
- **Gitlab plugin version**: 1.5.13
- **Gitlab version**: 12.9.1
- **Jenkins version**: Jenkins 2.204.5 LTS (slightly tweaked Docker image for running Jenkins as a non-root user)
- **Job type**: Pipeline, Freestyle, Matrix, etc.

### Logs & Traces

```
Mar 16, 2020 12:54:52 PM SEVERE com.dabsquared.gitlabjenkins.util.CommitStatusUpdater updateCommitStatus

Failed to update Gitlab commit status for project 'katana/TreeResolver'
javax.ws.rs.ClientErrorException: HTTP 403 Forbidden
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:216)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:50)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.$Proxy121.changeBuildStatus(Unknown Source)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.ResteasyGitLabClient.changeBuildStatus(ResteasyGitLabClient.java:60)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$7.execute(AutodetectingGitLabClient.java:112)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$7.execute(AutodetectingGitLabClient.java:109)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.execute(AutodetectingGitLabClient.java:335)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.access$100(AutodetectingGitLabClient.java:332)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.execute(AutodetectingGitLabClient.java:328)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.changeBuildStatus(AutodetectingGitLabClient.java:108)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$7.execute(AutodetectingGitLabClient.java:112)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$7.execute(AutodetectingGitLabClient.java:109)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.execute(AutodetectingGitLabClient.java:335)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.access$100(AutodetectingGitLabClient.java:332)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.execute(AutodetectingGitLabClient.java:328)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.changeBuildStatus(AutodetectingGitLabClient.java:108)
	at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.updateCommitStatus(CommitStatusUpdater.java:85)
	at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.updateCommitStatus(CommitStatusUpdater.java:97)
	at com.dabsquared.gitlabjenkins.workflow.UpdateGitLabCommitStatusStep$UpdateGitLabCommitStatusStepExecution.run(UpdateGitLabCommitStatusStep.java:79)
	at com.dabsquared.gitlabjenkins.workflow.UpdateGitLabCommitStatusStep$UpdateGitLabCommitStatusStepExecution.run(UpdateGitLabCommitStatusStep.java:63)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution.start(AbstractSynchronousStepExecution.java:42)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:286)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:179)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
	at sun.reflect.GeneratedMethodAccessor338.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:163)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:157)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:161)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:165)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:135)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at sun.reflect.GeneratedMethodAccessor159.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
	at sun.reflect.GeneratedMethodAccessor162.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

```
==> /var/log/gitlab/nginx/gitlab_access.log <==
[REDACTED] - - [18/Mar/2020:16:18:39 +0000] "GET /api/v4/projects/katana%2FTreeResolver/repository/commits/f1c35fef86bb22a8d067d94636f649e0cc955332 HTTP/1.1" 200 878 "" "-"
[REDACTED] - - [18/Mar/2020:16:18:39 +0000] "POST /api/v4/projects/katana%2FTreeResolver/statuses/f1c35fef86bb22a8d067d94636f649e0cc955332 HTTP/1.1" 403 27 "" "-"
[REDACTED] - - [18/Mar/2020:16:18:39 +0000] "GET /api/v4/projects/katana%2FTreeResolver/repository/commits/f1c35fef86bb22a8d067d94636f649e0cc955332 HTTP/1.1" 200 878 "" "-"
[REDACTED] - - [18/Mar/2020:16:18:39 +0000] "POST /api/v4/projects/katana%2FTreeResolver/statuses/f1c35fef86bb22a8d067d94636f649e0cc955332 HTTP/1.1" 403 27 "" "-"

==> /var/log/gitlab/gitlab-rails/production.log <==
Started GET "/api/v4/projects/katana%2FTreeResolver/repository/commits/f1c35fef86bb22a8d067d94636f649e0cc955332" for [REDACTED] at 2020-03-18 16:18:39 +0000
Started POST "/api/v4/projects/katana%2FTreeResolver/statuses/f1c35fef86bb22a8d067d94636f649e0cc955332" for [REDACTED] at 2020-03-18 16:18:39 +0000
Started GET "/api/v4/projects/katana%2FTreeResolver/repository/commits/f1c35fef86bb22a8d067d94636f649e0cc955332" for [REDACTED] at 2020-03-18 16:18:39 +0000
Started POST "/api/v4/projects/katana%2FTreeResolver/statuses/f1c35fef86bb22a8d067d94636f649e0cc955332" for [REDACTED] at 2020-03-18 16:18:39 +0000

==> /var/log/gitlab/gitlab-rails/api_json.log <==
{"time":"2020-03-18T16:18:39.347Z","severity":"INFO","duration":47.85,"db":5.62,"view":42.230000000000004,"status":200,"method":"GET","path":"/api/v4/projects/katana%2FTreeResolver/repository/commits/f1c35fef86bb22a8d067d94636f649e0cc955332","params":[],"host":"gitlab.[REDACTED]","remote_ip":"[REDACTED], [REDACTED], 127.0.0.1","ua":null,"route":"/api/:version/projects/:id/repository/commits/:sha","user_id":4,"username":"jenkins","queue_duration":6.58,"gitaly_calls":1,"gitaly_duration":7.04,"rugged_calls":1,"rugged_duration_ms":4.4,"correlation_id":"T6FIgeHJH81"}
{"time":"2020-03-18T16:18:39.381Z","severity":"INFO","duration":24.85,"db":4.88,"view":19.970000000000002,"status":403,"method":"POST","path":"/api/v4/projects/katana%2FTreeResolver/statuses/f1c35fef86bb22a8d067d94636f649e0cc955332","params":[{"key":"state","value":"pending"},{"key":"context","value":"jenkins"},{"key":"target_url","value":"https://jenkins.[REDACTED]/job/TreeResolver/job/master/31/display/redirect"},{"key":"description","value":"[FILTERED]"}],"host":"gitlab.[REDACTED]","remote_ip":"[REDACTED], [REDACTED], 127.0.0.1","ua":null,"route":"/api/:version/projects/:id/statuses/:sha","user_id":4,"username":"jenkins","queue_duration":3.56,"rugged_calls":1,"rugged_duration_ms":3.52,"correlation_id":"V4mr3cdrUI9"}
{"time":"2020-03-18T16:18:39.571Z","severity":"INFO","duration":51.41,"db":8.41,"view":43.0,"status":200,"method":"GET","path":"/api/v4/projects/katana%2FTreeResolver/repository/commits/f1c35fef86bb22a8d067d94636f649e0cc955332","params":[],"host":"gitlab.[REDACTED]","remote_ip":"[REDACTED], [REDACTED], 127.0.0.1","ua":null,"route":"/api/:version/projects/:id/repository/commits/:sha","user_id":4,"username":"jenkins","queue_duration":8.07,"gitaly_calls":1,"gitaly_duration":7.66,"rugged_calls":1,"rugged_duration_ms":1.85,"correlation_id":"EoMi9vlS0b8"}
{"time":"2020-03-18T16:18:39.608Z","severity":"INFO","duration":28.14,"db":5.16,"view":22.98,"status":403,"method":"POST","path":"/api/v4/projects/katana%2FTreeResolver/statuses/f1c35fef86bb22a8d067d94636f649e0cc955332","params":[{"key":"state","value":"running"},{"key":"context","value":"jenkins"},{"key":"target_url","value":"https://jenkins.[REDACTED]/job/TreeResolver/job/master/31/display/redirect"},{"key":"description","value":"[FILTERED]"}],"host":"gitlab.[REDACTED]","remote_ip":"[REDACTED], [REDACTED], 127.0.0.1","ua":null,"route":"/api/:version/projects/:id/statuses/:sha","user_id":4,"username":"jenkins","queue_duration":3.88,"rugged_calls":1,"rugged_duration_ms":3.94,"correlation_id":"WIIHfLOqEka"}

==> /var/log/gitlab/gitaly/current <==
{"correlation_id":"T6FIgeHJH81","grpc.code":"OK","grpc.meta.auth_version":"v2","grpc.meta.client_name":"gitlab-web","grpc.meta.deadline_type":"regular","grpc.method":"CommitStats","grpc.request.deadline":"2020-03-18T16:19:09Z","grpc.request.fullMethod":"/gitaly.CommitService/CommitStats","grpc.request.glProjectPath":"katana/TreeResolver","grpc.request.glRepository":"project-19","grpc.request.repoPath":"katana/TreeResolver.git","grpc.request.repoStorage":"default","grpc.request.topLevelGroup":"katana","grpc.service":"gitaly.CommitService","grpc.start_time":"2020-03-18T16:18:39Z","grpc.time_ms":5.839,"level":"info","msg":"finished unary call with code OK","peer.address":"@","pid":938,"span.kind":"server","system":"grpc","time":"2020-03-18T16:18:39Z"}
{"correlation_id":"EoMi9vlS0b8","grpc.code":"OK","grpc.meta.auth_version":"v2","grpc.meta.client_name":"gitlab-web","grpc.meta.deadline_type":"regular","grpc.method":"CommitStats","grpc.request.deadline":"2020-03-18T16:19:09Z","grpc.request.fullMethod":"/gitaly.CommitService/CommitStats","grpc.request.glProjectPath":"katana/TreeResolver","grpc.request.glRepository":"project-19","grpc.request.repoPath":"katana/TreeResolver.git","grpc.request.repoStorage":"default","grpc.request.topLevelGroup":"katana","grpc.service":"gitaly.CommitService","grpc.start_time":"2020-03-18T16:18:39Z","grpc.time_ms":6.076,"level":"info","msg":"finished unary call with code OK","peer.address":"@","pid":938,"span.kind":"server","system":"grpc","time":"2020-03-18T16:18:39Z"}

==> /var/log/gitlab/gitlab-workhorse/current <==
{"correlation_id":"T6FIgeHJH81","duration_ms":55,"host":"gitlab.[REDACTED]","level":"info","method":"GET","msg":"access","proto":"HTTP/1.1","referrer":"","remote_addr":"127.0.0.1:0","remote_ip":"127.0.0.1","status":200,"system":"http","time":"2020-03-18T16:18:39Z","uri":"/api/v4/projects/katana%2FTreeResolver/repository/commits/f1c35fef86bb22a8d067d94636f649e0cc955332","user_agent":"","written_bytes":878}
{"correlation_id":"V4mr3cdrUI9","duration_ms":29,"host":"gitlab.[REDACTED]","level":"info","method":"POST","msg":"access","proto":"HTTP/1.1","referrer":"","remote_addr":"127.0.0.1:0","remote_ip":"127.0.0.1","status":403,"system":"http","time":"2020-03-18T16:18:39Z","uri":"/api/v4/projects/katana%2FTreeResolver/statuses/f1c35fef86bb22a8d067d94636f649e0cc955332","user_agent":"","written_bytes":27}
{"correlation_id":"EoMi9vlS0b8","duration_ms":60,"host":"gitlab.[REDACTED]","level":"info","method":"GET","msg":"access","proto":"HTTP/1.1","referrer":"","remote_addr":"127.0.0.1:0","remote_ip":"127.0.0.1","status":200,"system":"http","time":"2020-03-18T16:18:39Z","uri":"/api/v4/projects/katana%2FTreeResolver/repository/commits/f1c35fef86bb22a8d067d94636f649e0cc955332","user_agent":"","written_bytes":878}
{"correlation_id":"WIIHfLOqEka","duration_ms":32,"host":"gitlab.[REDACTED]","level":"info","method":"POST","msg":"access","proto":"HTTP/1.1","referrer":"","remote_addr":"127.0.0.1:0","remote_ip":"127.0.0.1","status":403,"system":"http","time":"2020-03-18T16:18:39Z","uri":"/api/v4/projects/katana%2FTreeResolver/statuses/f1c35fef86bb22a8d067d94636f649e0cc955332","user_agent":"","written_bytes":27}
```

### Problem description

This appears to be caused by an API breakage by GitLab - Maintainer access is now required for the Jenkins user.

Ref: https://gitlab.com/gitlab-org/gitlab/-/issues/213626
Ref: https://gitlab.com/gitlab-org/gitlab/-/commit/5f63ef2b03936978376e47f01e0b509a45e899cd

---

This issue is being opened as a catchall for the overarching issue, and to consider updates for any documentation in the event that GitLab decides to stick with their API breakage.

**Comment by katanacrimson** [comment]
Original cause appears to be:

https://gitlab.com/gitlab-org/gitlab/-/issues/22956

GitLab will not be reverting the behavior.

Another issue has been opened, however, to potentially move the feature of specifying specific user access for branch protection overrides:  https://gitlab.com/gitlab-org/gitlab/-/issues/214661
