### ISSUE TITLE
Web hook  doesn't work

### ISSUE THREAD

**Issue by PiterGoCompany** [jenkinsci/gitlab-plugin#1054]
## Issue
Triggering web hook from project in GitLab returns status 500.
### Context
- **Gitlab plugin version**: 1.5.13
- **Gitlab version**: 12.9.4 (Community Edition)
- **Jenkins version**: 2.233
- **Job type**: Freestyle

### Logs & Traces
JENKINS LOG:
Apr 27, 2020 1:06:36 PM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/MyProject
Apr 27, 2020 1:06:36 PM WARNING hudson.init.impl.InstallUncaughtExceptionHandler handleException
Caught unhandled exception with ID 0828e0f1-d888-4254-a75d-310224887802
java.lang.Exception: Failed to read request body
	at org.kohsuke.stapler.HttpResponses.error(HttpResponses.java:91)
	at com.dabsquared.gitlabjenkins.webhook.ActionResolver.getRequestBody(ActionResolver.java:161)
	at com.dabsquared.gitlabjenkins.webhook.ActionResolver.onPost(ActionResolver.java:114)

### Problem description

For a very long time everything worked as is should. Now when web hook is fired from GitLab and received by Jenkins job is not started. Jenkins log shows exception as in the "Logs & Traces" section. In the GitLab web hook log looks OK. Additional strange thing is that if I post the same POST request using Postman, then Jenkins starts the job without any exception.

**Comment by system77771** [comment]
did you find a solution?

**Comment by PiterGoCompany** [comment]
No. We've moved Jenkins jobs to the GitLab.
