### ISSUE TITLE
jenkins not updating gitlab

### ISSUE THREAD

**Issue by Masber** [jenkinsci/gitlab-plugin#1084]
### Context
- **Gitlab plugin version**: 1.5.13
- **Gitlab version**: GitLab Community Edition 13.4.1
- **Jenkins version**: 2.260
- **Job type**: Pipeline

### Logs & Traces

_Please include any relevant log that could serve to better understand the source of your issue_
For Jenkins Gitlab Plugin logs, follow instruction in [User Support section](https://github.com/jenkinsci/gitlab-plugin#user-support).
For Gitlab logs, ask an administrator to provide you the relevant Gitlab logs.

Jenkins log

```
2020-10-26 23:34:31.579+0000 [id=16]	INFO	c.d.g.webhook.GitLabWebHook#getDynamic: WebHook called with url: /project/helloworld
2020-10-26 23:34:31.583+0000 [id=16]	INFO	c.d.g.t.h.AbstractWebHookTriggerHandler#handle: helloworld triggered for push.
2020-10-26 23:34:49.578+0000 [id=206]	INFO	c.d.g.util.CommitStatusUpdater#retrieveGitlabProjectIds: Retrieving gitlab project ids
2020-10-26 23:34:50.055+0000 [id=206]	INFO	c.d.g.util.CommitStatusUpdater#updateCommitStatus: Updating build '2' to 'pending'
2020-10-26 23:34:50.695+0000 [id=206]	SEVERE	c.d.g.util.CommitStatusUpdater#updateCommitStatus: Failed to update Gitlab commit status for project '2'
javax.ws.rs.BadRequestException: HTTP 400 Bad Request
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:197)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:50)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.$Proxy83.changeBuildStatus(Unknown Source)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.ResteasyGitLabClient.changeBuildStatus(ResteasyGitLabClient.java:60)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$7.execute(AutodetectingGitLabClient.java:112)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$7.execute(AutodetectingGitLabClient.java:109)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.execute(AutodetectingGitLabClient.java:335)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.access$100(AutodetectingGitLabClient.java:332)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.execute(AutodetectingGitLabClient.java:328)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.changeBuildStatus(AutodetectingGitLabClient.java:108)
	at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.updateCommitStatus(CommitStatusUpdater.java:85)
	at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.updateCommitStatus(CommitStatusUpdater.java:97)
	at com.dabsquared.gitlabjenkins.workflow.GitLabBuildsStep$GitLabBuildStepExecution$1.onStart(GitLabBuildsStep.java:85)
	at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution.launch(CpsBodyExecution.java:135)
	at org.jenkinsci.plugins.workflow.cps.CpsBodyInvoker.launch(CpsBodyInvoker.java:187)
	at org.jenkinsci.plugins.workflow.cps.DSL$ThreadTaskImpl.lambda$invokeBodiesAndSwitchToAsyncMode$0(DSL.java:660)
	at org.jenkinsci.plugins.workflow.cps.CpsStepContext.withBodyInvokers(CpsStepContext.java:537)
	at org.jenkinsci.plugins.workflow.cps.DSL$ThreadTaskImpl.invokeBodiesAndSwitchToAsyncMode(DSL.java:650)
	at org.jenkinsci.plugins.workflow.cps.DSL$ThreadTaskImpl.eval(DSL.java:615)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:195)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:136)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Problem description

_Describe your problem in a meaningful way_:
- what were you doing (simple push, merge request, MR with fork, ...)
- what was expected
- what occurred finally

steps to reproduce the issue:

1. push to gitlab
2. Gitlab triggers Jenkins pipeline through a Jenkinsfile in within the project
3. Jenkins pipeline finishes however Gitlab is not aware of this and shows the pipeline with "pending" status

This is the content of my Jenkinsfile
```

pipeline {
    agent any
    options {
      gitLabConnection('Gitlab')
      gitlabBuilds(builds: ['test', 'build'])
    }
    triggers {
        gitlab(triggerOnPush: true, triggerOnMergeRequest: true, branchFilterType: 'All')
    }
    stages {
        stage("test") {
            steps {
                sh 'ansible-playbook /var/jenkins_home/workspace/helloworld/ansible/build_and_run_unittest.yaml'
            }
            post {
                 success {
                     updateGitlabCommitStatus name: 'test', state: 'success'
                 }
                 failure {
                     updateGitlabCommitStatus name: 'test', state: 'failed'
                 }
                 aborted {
                     updateGitlabCommitStatus name: 'test', state: 'canceled'
                 }
             }
        }
        stage("build") {
            steps {
                echo 'production build'
                error("TESTING STAGE FAILURE..")
            }
            post {
                 success {
                     updateGitlabCommitStatus name: 'build', state: 'success'
                 }
                 failure {
                     updateGitlabCommitStatus name: 'build', state: 'failed'
                 }
                 aborted {
                     updateGitlabCommitStatus name: 'build', state: 'canceled'
                 }
             }
        }
    }
}
```

**Comment by aiKharybin** [comment]
Hi, what was the solution?

**Comment by quroom** [comment]
@Kharibin
Did you solve your problem?
In my case, The only problem is that I didn't set gitLabConnection option properly.
After I set it, it works properly.
If you don't have any logs for updategitlabcommitstatus, you should check your gitlabconnection options.
If you do perfectly, we will get log like c.d.g.util.CommitStatusUpdater#updateCommitStatus: Updating build '26104487' to 'success'
