### ISSUE TITLE
When I commented on the merge request of gitlab, webhooks has triggered the event to jenkins, but jenkins did not start the build

### ISSUE THREAD

**Issue by ningjunwei2** [jenkinsci/gitlab-plugin#1158]
my jenkins version is 2.296
my jenkinssci/gitlab plugin is  1.5.20
my system is ubuntu  Ubuntu 21.04

there is error  some  log
29-Sep-2021 11:53:50.475 SEVERE [Handling POST /jenkins/job/other/job/time-test/descriptorByName/com.dabsquared.gitlabjenkins.GitLabPushTrigger/checkIncludeBranchesSpec from xxxx : http-nio-8080-exec-1] org.apache.catalina.core.ApplicationContext.log Error while serving http://xxxx/jenkins/job/other/job/time-test/descriptorByName/com.dabsquared.gitlabjenkins.GitLabPushTrigger/checkIncludeBranchesSpec
        java.lang.reflect.InvocationTargetException
                at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:397)
                at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:405)
                at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:208)
                at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:141)
                at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:536)
                at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
                at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
                at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
                at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:281)
                at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
                at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
                at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
                at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:281)
                at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
                at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
                at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
                at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:281)
                at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
                at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
                at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
                at org.kohsuke.stapler.Stapler.invoke(Stapler.java:694)
                at org.kohsuke.stapler.Stapler.service(Stapler.java:240)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:232)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
                at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:157)
                at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:248)
                at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
                at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:129)
                at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
                at jenkins.security.ResourceDomainFilter.doFilter(ResourceDomainFilter.java:81)
                at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
                at com.smartcodeltd.jenkinsci.plugin.assetbundler.filters.LessCSS.doFilter(LessCSS.java:47)
                at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
                at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:160)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
                at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:155)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
                at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:93)
                at jenkins.security.AcegiSecurityExceptionFilter.doFilter(AcegiSecurityExceptionFilter.java:52)
                at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:98)
                at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:53)

**Comment by ljackiewicz** [comment]
@ningjunwei2 Can you provide the steps needed to reproduce this bug?
