### ISSUE TITLE
Error on "Test Connection" button

### ISSUE THREAD

**Issue by gleitoncampos** [jenkinsci/gitlab-plugin#1209]
### Version report

Jenkins and plugins versions report:

```
Jenkins 2.319.1
GitLab plugin 1.5.25
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Ubuntu 20.04 (AWS)
```

### Reproduction steps

- Install Jenkins with recommended plugins;
- Install Gitlab Plugin + Restart;
- Create a credential with the option "GitLab Token";
- Configure Gitlab options with Global Gitlab (url, select token and name);
- Hit "Test Connection" button

### Results

Expected result:

Connection Ok

Actual result:

The word "ERROR", with a generic text and a Lgging ID

If I keep a tail -f in the jenkins.log, after push the button, I receive the following stream of log:

> 2021-12-24 22:40:16.653+0000 [id=15]    WARNING o.e.j.s.h.ContextHandler$Context#log: Error while serving http://35.173.127.253:8080/descriptorByName/com.dabsquared.gitlabjenkins.connection.GitLabConnection/testConnection
> java.lang.NoClassDefFoundError: javax/ws/rs/ext/MessageBodyReader
>         at com.dabsquared.gitlabjenkins.gitlab.api.impl.ResteasyGitLabClientBuilder.buildClient(ResteasyGitLabClientBuilder.java:139)
>         at com.dabsquared.gitlabjenkins.gitlab.api.impl.ResteasyGitLabClientBuilder.buildClient(ResteasyGitLabClientBuilder.java:91)
>         at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.autodetect(AutodetectingGitLabClient.java:315)
>         at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.autodetectOrDie(AutodetectingGitLabClient.java:305)
>         at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.delegate(AutodetectingGitLabClient.java:298)
>         at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.access$200(AutodetectingGitLabClient.java:14)
>         at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.execute(AutodetectingGitLabClient.java:335)
>         at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.access$100(AutodetectingGitLabClient.java:332)
>         at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.execute(AutodetectingGitLabClient.java:328)
>         at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.getCurrentUser(AutodetectingGitLabClient.java:242)
>         at com.dabsquared.gitlabjenkins.connection.GitLabConnection$DescriptorImpl.doTestConnection(GitLabConnection.java:240)
>         at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
>         at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:393)
> Caused: java.lang.reflect.InvocationTargetException
>         at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:397)
>         at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:405)
>         at org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:77)
>         at org.kohsuke.stapler.PreInvokeInterceptedFunction.invoke(PreInvokeInterceptedFunction.java:26)
>         at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:208)
>         at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:141)
>         at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:536)
>         at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
>         at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
>         at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
>         at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:281)
>         at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
>         at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
>         at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
>         at org.kohsuke.stapler.Stapler.invoke(Stapler.java:694)
>         at org.kohsuke.stapler.Stapler.service(Stapler.java:240)
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
>         at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
>         at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
>         at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:156)
>         at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)
>         at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:153)
>         at jenkins.security.ResourceDomainFilter.doFilter(ResourceDomainFilter.java:80)
>         at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:153)
>         at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:159)
>         at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
>         at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
>         at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:153)
>         at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
>         at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
>         at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:92)
>         at jenkins.security.AcegiSecurityExceptionFilter.doFilter(AcegiSecurityExceptionFilter.java:52)
>         at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
>         at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:53)
>         at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
>         at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:121)
>         at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
>         at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
>         at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105)
>         at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
>         at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:101)
>         at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:92)
>         at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
>         at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:218)
>         at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
>         at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
>         at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:97)
>         at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
>         at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
>         at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
>         at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:62)
>         at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
>         at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:109)
>         at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
>         at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
>         at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
>         at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:51)
>         at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
>         at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
>         at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:85)
>         at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
>         at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
>         at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
>         at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
>         at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
>         at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:39)
>         at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
>         at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
>         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
>         at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
>         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
>         at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
>         at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
>         at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
>         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
>         at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
>         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
>         at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
>         at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
>         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
>         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
>         at org.eclipse.jetty.server.Server.handle(Server.java:516)
>         at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
>         at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
>         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
>         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
>         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
>         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
>         at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
>         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
>         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
>         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
>         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
>         at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
>         at java.lang.Thread.run(Thread.java:748)
> 2021-12-24 22:40:16.657+0000 [id=15]    WARNING h.i.i.InstallUncaughtExceptionHandler#handleException: Caught unhandled exception with ID 79982e69-c94e-4ccf-b8f0-94b729c0d716
> java.lang.NoClassDefFoundError: javax/ws/rs/ext/MessageBodyReader
>         at com.dabsquared.gitlabjenkins.gitlab.api.impl.ResteasyGitLabClientBuilder.buildClient(ResteasyGitLabClientBuilder.java:139)
>         at com.dabsquared.gitlabjenkins.gitlab.api.impl.ResteasyGitLabClientBuilder.buildClient(ResteasyGitLabClientBuilder.java:91)
>         at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.autodetect(AutodetectingGitLabClient.java:315)
>         at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.autodetectOrDie(AutodetectingGitLabClient.java:305)
>         at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.delegate(AutodetectingGitLabClient.java:298)
>         at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.access$200(AutodetectingGitLabClient.java:14)
>         at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.execute(AutodetectingGitLabClient.java:335)
>         at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.access$100(AutodetectingGitLabClient.java:332)
>         at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.execute(AutodetectingGitLabClient.java:328)
>         at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.getCurrentUser(AutodetectingGitLabClient.java:242)
>         at com.dabsquared.gitlabjenkins.connection.GitLabConnection$DescriptorImpl.doTestConnection(GitLabConnection.java:240)
>         at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
>         at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:393)
>         at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:405)
>         at org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:77)
>         at org.kohsuke.stapler.PreInvokeInterceptedFunction.invoke(PreInvokeInterceptedFunction.java:26)
>         at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:208)
>         at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:141)
>         at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:536)
>         at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
>         at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
> Caused: javax.servlet.ServletException
>         at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:816)
>         at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
>         at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:281)
>         at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
>         at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
>         at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
>         at org.kohsuke.stapler.Stapler.invoke(Stapler.java:694)
>         at org.kohsuke.stapler.Stapler.service(Stapler.java:240)
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
>         at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
>         at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
>         at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:156)
>         at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)
>         at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:153)
>         at jenkins.security.ResourceDomainFilter.doFilter(ResourceDomainFilter.java:80)
>         at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:153)
>         at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:159)
>         at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
>         at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
>         at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:153)
>         at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
>         at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
>         at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:92)
>         at jenkins.security.AcegiSecurityExceptionFilter.doFilter(AcegiSecurityExceptionFilter.java:52)
>         at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
>         at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:53)
>         at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
>         at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:121)
>         at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
>         at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
>         at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105)
>         at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
>         at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:101)
>         at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:92)
>         at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
>         at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:218)
>         at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
>         at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
>         at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:97)
>         at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
>         at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
>         at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
>         at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:62)
>         at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
>         at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:109)
>         at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
>         at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
>         at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
>         at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:51)
>         at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
>         at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
>         at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:85)
>         at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
>         at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
>         at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
>         at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
>         at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
>         at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:39)
>         at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
>         at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
>         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
>         at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
>         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
>         at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
>         at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
>         at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
>         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
>         at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
>         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
>         at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
>         at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
>         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
>         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
>         at org.eclipse.jetty.server.Server.handle(Server.java:516)
>         at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
>         at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
>         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
>         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
>         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
>         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
>         at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
>         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
>         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
>         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
>         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
>         at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
>         at java.lang.Thread.run(Thread.java:748)

**Comment by gleitoncampos** [comment]
The problem was tracked in #1206 . The cause and a workaround was found. Closing.
