### ISSUE TITLE
[Jenkins][Gitlab Plugin1.5.34]Failed to update Gitlab commit status for project - HTTP 410 Gone

### ISSUE THREAD

**Issue by weiluxianche** [jenkinsci/gitlab-plugin#1305]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```
Jenkins: 2.341
OS: Linux - 5.13.0-35-generic
---
ace-editor:1.1
allure-jenkins-plugin:2.30.2
ant:1.13
antisamy-markup-formatter:2.7
apache-httpcomponents-client-4-api:4.5.13-1.0
authentication-tokens:1.4
bootstrap4-api:4.6.0-3
bootstrap5-api:5.1.3-6
bouncycastle-api:2.25
branch-api:2.1044.v2c007e51b_87f
build-timeout:1.20
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
checks-api:1.7.2
cloudbees-folder:6.714.v79e858ef76a_2
command-launcher:1.6
cppcheck:1.25
credentials:1118.v320cd028cb_a_0
credentials-binding:1.27.1
display-url-api:2.3.6
docker-build-step:2.8
docker-commons:1.19
docker-java-api:3.1.5.2
docker-plugin:1.2.7
docker-workflow:1.28
durable-task:495.v29cd95ec10f2
echarts-api:5.3.0-2
email-ext:2.87
emailext-template:1.4
external-monitor-job:191.v363d0d1efdf8
font-awesome-api:6.0.0-1
generic-webhook-trigger:1.84
git:4.11.3
git-client:3.11.0
git-server:1.10
github:1.34.3
github-api:1.301-378.v9807bd746da5
github-branch-source:1598.v91207e9f9b_4a_
gitlab-plugin:1.5.34
gradle:1.38
handlebars:3.0.8
jackson2-api:2.13.3-285.vc03c0256d517
javax-activation-api:1.2.0-3
javax-mail-api:1.6.2-5
jaxb:2.3.6-1
jdk-tool:1.5
jersey2-api:2.36-2
jjwt-api:0.11.2-9.c8b45b8bb173
jnr-posix-api:3.1.7-3
jquery3-api:3.6.0-2
jsch:0.1.55.2
junit:1.58
ldap:2.8
lockable-resources:2.14
mailer:408.vd726a_1130320
mapdb-api:1.0.9.0
matrix-auth:3.1
matrix-project:771.v574584b_39e60
metrics:4.1.6.1
momentjs:1.1.1
okhttp-api:4.9.3-105.vb96869f8ac3a
pam-auth:1.7
pipeline-build-step:2.17
pipeline-github-lib:36.v4c01db_ca_ed16
pipeline-graph-analysis:188.v3a01e7973f2c
pipeline-input-step:447.v95e5a_6e3502a_
pipeline-milestone-step:100.v60a_03cd446e1
pipeline-model-api:2.2075.vce74e77b_ce40
pipeline-model-definition:2.2075.vce74e77b_ce40
pipeline-model-extensions:2.2075.vce74e77b_ce40
pipeline-rest-api:2.23
pipeline-stage-step:291.vf0a8a7aeeb50
pipeline-stage-tags-metadata:2.2075.vce74e77b_ce40
pipeline-stage-view:2.23
plain-credentials:1.8
plugin-util-api:2.16.0
popper-api:1.16.1-2
popper2-api:2.11.5-1
publish-over:0.22
publish-over-ssh:1.24
rebuild:1.34
redmine:0.21
resource-disposer:0.18
scm-api:608.vfa_f971c5a_a_e9
script-security:1145.vb_cf6cf6ed960
snakeyaml-api:1.29.1
sonar:2.14
ssh-credentials:277.v95c2fec1c047
ssh-slaves:1.806.v2253cedd3295
sshd:3.228.v4c9f9e652c86
structs:308.v852b473a2b8c
subversion:2.15.5
support-core:1148.vedff8cb_56a_da_
timestamper:1.17
token-macro:285.vff7645a_56ff0
trilead-api:1.57.v6e90e07157e1
variant:1.4
windows-slaves:1.8.1
workflow-aggregator:2.7
workflow-api:1143.v2d42f1e9dea_5
workflow-basic-steps:941.vdfe1b_a_132c64
workflow-cps:2686.v7c37e0578401
workflow-cps-global-lib:566.vd0a_a_3334a_555
workflow-durable-task-step:1128.v8c259d125340
workflow-job:1174.vdcb_d054cf74a_
workflow-multibranch:711.vdfef37cda_816
workflow-scm-step:2.13
workflow-step-api:625.vd896b_f445a_f8
workflow-support:817.v58126df57338
ws-cleanup:0.41
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 20.04

### Reproduction steps

1. Install gitlab plugin on jenkins
2. Config right gitlab token to jenkins and test success
3. Config webhook on gitlab and triggered jenkins job build successfully
4. However, the post-build actions "Publish build status to GitLab" failed.

My gitlab version is 13.10

The jenkins log shows:
Failed to update Gitlab commit status for project '39'
javax.ws.rs.ClientErrorException: HTTP 410 Gone
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:263)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:50)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:154)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.$Proxy111.getCommit(Unknown Source)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.ResteasyGitLabClient.getCommit(ResteasyGitLabClient.java:120)
	at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.existsCommit(CommitStatusUpdater.java:121)
	at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.updateCommitStatus(CommitStatusUpdater.java:83)
	at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.updateCommitStatus(CommitStatusUpdater.java:97)
	at com.dabsquared.gitlabjenkins.publisher.GitLabCommitStatusPublisher.perform(GitLabCommitStatusPublisher.java:57)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:814)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:763)
	at hudson.model.Build$BuildExecution.post2(Build.java:179)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:707)
	at hudson.model.Run.execute(Run.java:1921)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)

![Screenshot from 2022-06-23 21-05-23](https://user-images.githubusercontent.com/53055227/175305520-0740de27-a27c-4a75-bb33-33d9221a1607.png)

### Expected Results

The jenkins job result could be write back to gitlab Merge&Request's commit.

### Actual Results

Nothing occurred.

**Comment by harsh-ps-2003** [comment]
hey @weiluxianche I tried reproducing the issue but got this instead - 
<img width="786" alt="Screenshot%25202023-03-19%2520at%252011 11 40%2520AM" src="https://user-images.githubusercontent.com/119954739/226172120-cad0bb06-223a-4637-b388-2f86f1c1fef7.png">
I am not getting any HTTP 410 error as mentioned in the issue.

**Comment by krisstern** [comment]
And which version of the plugin you have been using to try and reproduce the issue @harsh-ps-2003? Is it 1.5.34 as stated for this issue, or is it something newer? It would not be helpful for us without such an important piece of detail.

**Comment by harsh-ps-2003** [comment]
@krisstern I am using 1.7.9 version of gitlab plugin for trying to reproduce the issue.

**Comment by davidsj2** [comment]
For what it's worth, I ran into the same exact error message.  For me, the issue was I had a prior issue (no_proxy settings) that was resulting in 502 Bad Gateway errors.  I started messing around with the connection settings trying to fixed it, and at one point changed the api level from `autodetect` to v3.  When I resolved the no_proxy issue, I started getting the 410 errors.  I then when back into the connection settings and noticed the api level was set to v3.  After switching it back to autodetect, things started working again.
