### ISSUE TITLE
NPE when Jenkins jobs are triggered by PUSH or MERGE notification

### ISSUE THREAD

**Issue by cmurczek** [jenkinsci/gitlab-plugin#137]
Hi,
we're using GitLab 7.4 and Gitlab-Plugin 1.1.27. After installing the [dependencies required to build PhantomJs on Linux](http://phantomjs.org/build.html), when starting Jenkins I see the following in Jenkins' log:

```
Failed to instantiate Key[type=com.dabsquared.gitlabjenkins.GitLabPushTrigger$DescriptorImpl, annotation=[none]]; skipping this component
com.google.inject.ProvisionException: Guice provision errors:

1) Tried proxying com.dabsquared.gitlabjenkins.GitLabPushTrigger$DescriptorImpl to support a circular dependency, but it is not an interface.
```

Then for each job triggered by notification message sent by Gitlab I get:

```
GitLab Push Request detected in PicoCanyon_Build. Triggering  #1006

Nov 19, 2015 9:21:01 AM WARNING org.jenkins_ci.plugins.run_condition.BuildStepRunner logEvaluateException
Exception caught evaluating condition: [java.lang.NullPointerException: null], action = [Don't run]
java.lang.NullPointerException
at hudson.model.AbstractBuild.getBuildVariables(AbstractBuild.java:1045)
at hudson.model.AbstractBuild.getBuildVariableResolver(AbstractBuild.java:1066)
at org.jenkinsci.plugins.tokenmacro.TokenMacro.expandAll(TokenMacro.java:231)
at org.jenkinsci.plugins.tokenmacro.TokenMacro.expandAll(TokenMacro.java:222)
at org.jenkins_ci.plugins.run_condition.core.ExpressionCondition.runPerform        (ExpressionCondition.java:56)
at org.jenkins_ci.plugins.run_condition.BuildStepRunner$2.evaluate(BuildStepRunner.java:107)
at org.jenkins_ci.plugins.run_condition.BuildStepRunner$DontRun.conditionalRun(BuildStepRunner.java:259)
at org.jenkins_ci.plugins.run_condition.BuildStepRunner.perform(BuildStepRunner.java:105)
at org.jenkins_ci.plugins.flexible_publish.strategy.FailAtEndExecutionStrategy.perform(FailAtEndExecutionStrategy.java:85)
at org.jenkins_ci.plugins.flexible_publish.ConditionalPublisher.perform(ConditionalPublisher.java:206)
at org.jenkins_ci.plugins.flexible_publish.FlexiblePublisher.perform(FlexiblePublisher.java:124)
at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
at hudson.model.Build$BuildExecution.post2(Build.java:185)
at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
at hudson.model.Run.execute(Run.java:1766)
at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
at hudson.model.ResourceController.execute(ResourceController.java:98)
at hudson.model.Executor.run(Executor.java:408)


Nov 19, 2015 9:21:01 AM WARNING hudson.model.listeners.RunListener report
RunListener failed
java.lang.NullPointerException
at hudson.model.AbstractBuild.getSensitiveBuildVariables(AbstractBuild.java:1007)
at org.jenkinsci.plugins.envinject.service.EnvInjectActionSetter.addEnvVarsToEnvInjectBuildAction(EnvInjectActionSetter.java:43)
at org.jenkinsci.plugins.envinject.EnvInjectListener.onCompleted(EnvInjectListener.java:317)
at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
at hudson.model.Run.execute(Run.java:1786)
at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
at hudson.model.ResourceController.execute(ResourceController.java:98)
at hudson.model.Executor.run(Executor.java:408)


Nov 19, 2015 9:21:01 AM WARNING org.jenkins_ci.plugins.run_condition.BuildStepRunner logEvaluateException
Exception caught evaluating condition: [java.lang.NullPointerException: null], action = [Don't run]
java.lang.NullPointerException
at hudson.model.AbstractBuild.getBuildVariables(AbstractBuild.java:1045)
at hudson.model.AbstractBuild.getBuildVariableResolver(AbstractBuild.java:1066)
at org.jenkinsci.plugins.tokenmacro.TokenMacro.expandAll(TokenMacro.java:231)
at org.jenkinsci.plugins.tokenmacro.TokenMacro.expandAll(TokenMacro.java:222)
at org.jenkins_ci.plugins.run_condition.core.ExpressionCondition.runPerform    (ExpressionCondition.java:56)
at org.jenkins_ci.plugins.run_condition.BuildStepRunner$2.evaluate(BuildStepRunner.java:107)
at org.jenkins_ci.plugins.run_condition.BuildStepRunner$DontRun.conditionalRun(BuildStepRunner.java:259)
at org.jenkins_ci.plugins.run_condition.BuildStepRunner.perform(BuildStepRunner.java:105)
at org.jenkins_ci.plugins.flexible_publish.ConditionalDependencyWrapper.shouldTriggerBuild(ConditionalDependencyWrapper.java:91)
at hudson.tasks.BuildTrigger.execute(BuildTrigger.java:245)
at hudson.model.AbstractBuild$AbstractBuildExecution.cleanUp(AbstractBuild.java:687)
at hudson.model.Build$BuildExecution.cleanUp(Build.java:200)
at hudson.model.Run.execute(Run.java:1788)
at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
at hudson.model.ResourceController.execute(ResourceController.java:98)
at hudson.model.Executor.run(Executor.java:408)


Nov 19, 2015 9:28:14 AM INFO com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
WebHook called with url: 

Nov 19, 2015 9:28:14 AM INFO com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
WebHook called with url: /build

Nov 19, 2015 9:28:14 AM INFO com.dabsquared.gitlabjenkins.GitLabPushTrigger$2 run
PicoCanyon_Build triggered for push.

Nov 19, 2015 9:28:14 AM INFO com.dabsquared.gitlabjenkins.GitLabPushTrigger$2 createActions
GitLab Push Request from branch dev_INPD_704.

Nov 19, 2015 9:28:14 AM INFO com.dabsquared.gitlabjenkins.GitLabPushTrigger$2 createActions
Trying to get name and URL for job: PicoCanyon_Build using project PicoCanyon_Build (push)

Nov 19, 2015 9:28:14 AM INFO com.dabsquared.gitlabjenkins.GitLabPushTrigger$2 run
PicoCanyon_Build triggered for push.`
```

Any ideas?

**Comment by coder-hugo** [comment]
The installation of the dependencies for building PhontomJS can't cause these exceptions. I think you have installed/updated a plugin that causes these errors. Can you provide us a list of all installed plugins in your jenkins.
