### ISSUE TITLE
Merge request does not trigger build

### ISSUE THREAD

**Issue by cuiyangyang** [jenkinsci/gitlab-plugin#161]
Dec 17, 2015 8:04:22 PM org.apache.catalina.core.StandardHostValve custom
SEVERE: Exception Processing ErrorPage[exceptionType=java.lang.Throwable, location=/oops]
javax.servlet.ServletException: net.sf.json.JSONException: A JSONObject text must begin with '{' at character 0 of
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:795)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:875)
        at org.kohsuke.stapler.MetaClass$12.dispatch(MetaClass.java:391)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:745)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:875)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:648)
        at org.kohsuke.stapler.Stapler.service(Stapler.java:237)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:646)
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:551)
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:488)
        at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:416)
        at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:270)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
        at java.lang.Thread.run(Thread.java:745)
Caused by: net.sf.json.JSONException: A JSONObject text must begin with '{' at character 0 of
        at net.sf.json.util.JSONTokener.syntaxError(JSONTokener.java:499)
        at net.sf.json.JSONObject._fromJSONTokener(JSONObject.java:919)
        at net.sf.json.JSONObject._fromString(JSONObject.java:1145)
        at net.sf.json.JSONObject.fromObject(JSONObject.java:162)
        at net.sf.json.JSONObject.fromObject(JSONObject.java:132)
        at com.dabsquared.gitlabjenkins.GitLabWebHook.generateBuild(GitLabWebHook.java:332)
        at com.dabsquared.gitlabjenkins.GitLabWebHook.getDynamic(GitLabWebHook.java:152)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
        at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
        at org.kohsuke.stapler.MetaClass$12.dispatch(MetaClass.java:389)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:745)

**Comment by markus-mnm** [comment]
Hi!
What Jenkins, gitlab server and gitlab plugin versions are you using?
Also, could you set up a [Test log in Jenkins](https://wiki.jenkins-ci.org/display/JENKINS/Logging) with a debug level log for com.dabsquared.gitlabjenkins.GitLabWebHook?
Thanks!
