### ISSUE TITLE
Object Attribute from Gitlab webhook out of range of int

### ISSUE THREAD

**Issue by snegboris** [jenkinsci/gitlab-plugin#1705]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.462.3
OS: Linux - 5.15.0-119-generic
Java: 17.0.12 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
allure-jenkins-plugin:2.31.1
analysis-model-api:12.9.0
ant:511.v0a_a_1a_334f41b_
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
apache-httpcomponents-client-5-api:5.4-118.v199115451c4d
asm-api:9.7.1-95.v9f552033802a_
authentication-tokens:1.119.v50285141b_7e1
bootstrap5-api:5.3.3-1
bouncycastle-api:2.30.1.78.1-248.ve27176eb_46cb_
branch-api:2.1178.v969d9eb_c728e
build-blocker-plugin:166.vc82fc20b_a_ed6
build-name-setter:2.4.3
build-timeout:1.33
build-user-vars-plugin:176.vb_9c7907fd524
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.2.1
cloudbees-folder:6.955.v81e2a_35c08d3
command-launcher:115.vd8b_301cc15d0
commons-lang3-api:3.17.0-84.vb_b_938040b_078
commons-text-api:1.12.0-129.v99a_50df237f7
conditional-buildstep:1.4.3
copyartifact:749.vfb_dca_a_9b_6549
credentials:1384.vf0a_2ed06f9c6
credentials-binding:681.vf91669a_32e45
custom-folder-icon:2.14
dark-theme:479.v661b_1b_911c01
data-tables-api:2.1.8-1
display-url-api:2.204.vf6fddd8a_8b_e9
docker-commons:443.v921729d5611d
docker-custom-build-environment:1.7.3
durable-task:577.v2a_8a_4b_7c0247
echarts-api:5.5.1-1
eddsa-api:0.3.0-4.v84c6f0f4969e
email-ext:1844.v3ea_a_b_842374a_
envinject:2.919.v009a_a_1067cd0
envinject-api:1.199.v3ce31253ed13
file-operations:266.v9d4e1eb_235b_a_
font-awesome-api:6.6.0-2
forensics-api:2.6.0
generic-webhook-trigger:2.2.2
git:5.5.2
git-client:5.0.0
git-parameter:0.9.19
github:1.40.0
github-api:1.321-468.v6a_9f5f2d5a_7e
github-branch-source:1797.v86fdb_4d57d43
gitlab-plugin:1.8.1
gradle:2.13.1
gson-api:2.11.0-41.v019fcf6125dc
instance-identity:201.vd2a_b_5a_468a_a_6
ionicons-api:74.v93d5eb_813d5f
jackson2-api:2.17.0-379.v02de8ec9f64c
jakarta-activation-api:2.1.3-1
jakarta-mail-api:2.1.3-1
javax-activation-api:1.2.0-7
javax-mail-api:1.6.2-10
jaxb:2.3.9-1
jdk-tool:80.v8a_dee33ed6f0
jersey2-api:2.44-151.v6df377fff741
jjwt-api:0.11.5-112.ve82dfb_224b_a_d
joda-time-api:2.13.0-85.vb_64d1c2921f1
jquery3-api:3.7.1-2
jsch:0.2.16-86.v42e010d9484b_
json-api:20240303-41.v94e11e6de726
json-path-api:2.9.0-58.v62e3e85b_a_655
junit:1304.vc85a_b_ca_96613
ldap:725.v3cb_b_711b_1a_ef
mailer:488.v0c9639c1a_eb_3
material-theme:0.5.2-rc100.6121925fe229
matrix-auth:3.2.2
matrix-project:839.vff91cd7e3a_b_2
mina-sshd-api-common:2.14.0-133.vcc091215a_358
mina-sshd-api-core:2.14.0-133.vcc091215a_358
okhttp-api:4.11.0-172.vda_da_1feeb_c6e
oss-symbols-api:75.v337a_1c270ffc
pam-auth:1.11
parameterized-trigger:806.vf6fff3e28c3e
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-github-lib:61.v629f2cc41d83
pipeline-graph-analysis:216.vfd8b_ece330ca_
pipeline-groovy-lib:730.ve57b_34648c63
pipeline-input-step:495.ve9c153f6067b_
pipeline-milestone-step:119.vdfdc43fc3b_9a_
pipeline-model-api:2.2214.vb_b_34b_2ea_9b_83
pipeline-model-definition:2.2214.vb_b_34b_2ea_9b_83
pipeline-model-extensions:2.2214.vb_b_34b_2ea_9b_83
pipeline-rest-api:2.34
pipeline-stage-step:312.v8cd10304c27a_
pipeline-stage-tags-metadata:2.2214.vb_b_34b_2ea_9b_83
pipeline-stage-view:2.34
plain-credentials:183.va_de8f1dd5a_2b_
plugin-util-api:5.1.0
postbuild-task:1.9
postbuildscript:3.3.0-654.v67cf36130d78
powershell:2.1
prism-api:1.29.0-17
progress-bar-column-plugin:11.vdef198c2d6c1
publish-over:0.22
publish-over-ssh:1.25
rebuild:332.va_1ee476d8f6d
resource-disposer:0.24
run-condition:1.7
scm-api:696.v778d637b_a_762
script-security:1362.v67dc1f0e1b_b_3
snakeyaml-api:2.3-123.v13484c65210a_
ssh-agent:376.v8933585c69d3
ssh-credentials:343.v884f71d78167
ssh-slaves:2.973.v0fa_8c0dea_f9f
ssh-steps:2.0.68.va_d21a_12a_6476
sshd:3.330.vc866a_8389b_58
structs:338.v848422169819
theme-manager:262.vc57ee4a_eda_5d
throttle-concurrents:2.14
timestamper:1.27
token-macro:400.v35420b_922dcb_
trilead-api:2.147.vb_73cc728a_32e
uno-choice:2.8.4
variant:60.v7290fc0eb_b_cd
warnings-ng:11.9.0
workflow-aggregator:600.vb_57cdd26fdd7
workflow-api:1336.vee415d95c521
workflow-basic-steps:1058.vcb_fc1e3a_21a_9
workflow-cps:3969.vdc9d3a_efcc6a_
workflow-durable-task-step:1371.vb_7cec8f3b_95e
workflow-job:1436.vfa_244484591f
workflow-multibranch:795.ve0cb_1f45ca_9a_
workflow-scm-step:427.v4ca_6512e7df1
workflow-step-api:678.v3ee58b_469476
workflow-support:926.v9f4f9b_b_98c19
ws-cleanup:0.47
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins LTS docker image

### Reproduction steps

Create a comment in MR

Example:
```
{
  "object_kind": "note",
  "event_type": "note",
  "user": {
    "id": *****,
    "name": "*****",
    "username": "*****",
    "avatar_url": "*****",
    "email": "[REDACTED]"
  },
  "project_id": *****,
  "project": {
    "id": *****,
    "name": "*****",
    "description": "",
    "web_url": "*****",
    "avatar_url": null,
    "git_ssh_url": "*****",
    "git_http_url": "*****",
    "namespace": "*****",
    "visibility_level": 0,
    "path_with_namespace": "*****",
    "default_branch": "master",
    "ci_config_path": null,
    "homepage": "*****",
    "url": "*****",
    "ssh_url": "*****,
    "http_url": "*****"
  },
  "object_attributes": {
    "attachment": null,
    "author_id": *****,
    "change_position": null,
    "commit_id": null,
    "created_at": "2024-10-08 14:13:05 UTC",
    "discussion_id": "*****",
    "id": 2148334819,
    "line_code": null,
    "note": "retry",
    "noteable_id": *****,
    "noteable_type": "MergeRequest",
    "original_position": null,
    "position": null,
    "project_id": *****,
    "resolved_at": null,
    "resolved_by_id": null,
    "resolved_by_push": null,
    "st_diff": null,
    "system": false,
    "type": null,
    "updated_at": "2024-10-08 14:13:05 UTC",
    "updated_by_id": null,
    "description": "retry",
    "url": "*****",
    "action": "create"
  }..............................
```

### Expected Results

No error

### Actual Results

The error occurs with the note id in webhook from GitLab.

```
Caught unhandled exception with ID 6b0380f1-b1f0-4982-8806-ab6ac52188cc
com.fasterxml.jackson.core.exc.InputCoercionException: Numeric value (2148334819) out of range of int (-2147483648 - 2147483647)
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1108]
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.core.base.ParserMinimalBase._reportInputCoercion(ParserMinimalBase.java:562)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.core.base.ParserMinimalBase.reportOverflowInt(ParserMinimalBase.java:624)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:1059)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.core.base.ParserBase._parseIntValue(ParserBase.java:983)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:789)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:526)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:506)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
Caused: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (2148334819) out of range of int (-2147483648 - 2147483647)
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1108] (through reference chain: com.dabsquared.gitlabjenkins.gitlab.hook.model.NoteHook["object_attributes"]->com.dabsquared.gitlabjenkins.gitlab.hook.model.NoteObjectAttributes["id"])
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1937)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:312)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4905)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3848)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3816)
	at PluginClassLoader for gitlab-plugin//com.dabsquared.gitlabjenkins.util.JsonUtil.read(JsonUtil.java:57)
Caused: java.lang.RuntimeException
	at PluginClassLoader for gitlab-plugin//com.dabsquared.gitlabjenkins.util.JsonUtil.read(JsonUtil.java:59)
```

<details>
  <summary>Full log</summary>

```
Caught unhandled exception with ID 6b0380f1-b1f0-4982-8806-ab6ac52188cc
com.fasterxml.jackson.core.exc.InputCoercionException: Numeric value (2148334819) out of range of int (-2147483648 - 2147483647)
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1108]
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.core.base.ParserMinimalBase._reportInputCoercion(ParserMinimalBase.java:562)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.core.base.ParserMinimalBase.reportOverflowInt(ParserMinimalBase.java:624)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:1059)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.core.base.ParserBase._parseIntValue(ParserBase.java:983)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:789)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:526)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:506)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
Caused: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (2148334819) out of range of int (-2147483648 - 2147483647)
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1108] (through reference chain: com.dabsquared.gitlabjenkins.gitlab.hook.model.NoteHook["object_attributes"]->com.dabsquared.gitlabjenkins.gitlab.hook.model.NoteObjectAttributes["id"])
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1937)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:312)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4905)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3848)
	at PluginClassLoader for jackson2-api//com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3816)
	at PluginClassLoader for gitlab-plugin//com.dabsquared.gitlabjenkins.util.JsonUtil.read(JsonUtil.java:57)
Caused: java.lang.RuntimeException
	at PluginClassLoader for gitlab-plugin//com.dabsquared.gitlabjenkins.util.JsonUtil.read(JsonUtil.java:59)
	at PluginClassLoader for gitlab-plugin//com.dabsquared.gitlabjenkins.webhook.build.NoteBuildAction.<init>(NoteBuildAction.java:32)
	at PluginClassLoader for gitlab-plugin//com.dabsquared.gitlabjenkins.webhook.ActionResolver.onPost(ActionResolver.java:121)
	at PluginClassLoader for gitlab-plugin//com.dabsquared.gitlabjenkins.webhook.ActionResolver.resolveAction(ActionResolver.java:65)
	at PluginClassLoader for gitlab-plugin//com.dabsquared.gitlabjenkins.webhook.ActionResolver.resolve(ActionResolver.java:59)
	at PluginClassLoader for gitlab-plugin//com.dabsquared.gitlabjenkins.webhook.GitLabWebHook.getDynamic(GitLabWebHook.java:42)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:416)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:429)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:211)
	at org.kohsuke.stapler.MetaClass$9.dispatch(MetaClass.java:546)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:827)
Caused: javax.servlet.ServletException
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:878)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:965)
	at org.kohsuke.stapler.MetaClass$9.dispatch(MetaClass.java:548)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:827)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:965)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:747)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:253)
	at Jenkins Main ClassLoader//javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:163)
	at jenkins.util.HttpServletFilter$1.doFilter(HttpServletFilter.java:76)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:160)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:166)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at jenkins.ErrorAttributeFilter.doFilter(ErrorAttributeFilter.java:29)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at PluginClassLoader for gitlab-plugin//com.dabsquared.gitlabjenkins.webhook.GitLabWebHook$GitlabWebHookCrumbExclusion.process(GitLabWebHook.java:52)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:128)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:94)
	at jenkins.security.AcegiSecurityExceptionFilter.doFilter(AcegiSecurityExceptionFilter.java:52)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:54)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:145)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:101)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:97)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:117)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:63)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:111)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:172)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:53)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:86)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:31)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:38)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
	at Jenkins Main ClassLoader//org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:569)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1580)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:822)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.Server.handle(Server.java:563)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
	at Jenkins Main ClassLoader//org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at Jenkins Main ClassLoader//org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at Jenkins Main ClassLoader//org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Unknown Source)
```

</details>

**Comment by bouaouda-achraf** [comment]
same error on our end  : "object_attributes": { id  : XXXXX }

**Comment by ericromario** [comment]
same error on our end : "object_attributes": { id : XXXXX }

**Comment by ghost** [comment]
Same here

**Comment by rastakajakwanna** [comment]
Jenkins version 2.440.3 with plugin version 1.8.1 (latest for this LTS version) is also affected. But it's really just the note type (comment) trigger, other triggers work fine. Gitlab is the gitlab.com SaaS.

**Comment by jeremygaither** [comment]
Jenkins 2.474 with plugin 1.9.1 is also affected, with comment triggers when the note ID is greater than max int.

**Comment by simonefranconetti** [comment]
Same here

**Comment by asxan** [comment]
Same here

**Comment by rastakajakwanna** [comment]
It is confirmed with Gitlab support. `Id` column for the notes changed from `integer` to `bigint` (see [MR](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/119705) ). If I get approval from the person who replied I'll quote the whole answer, but this is basically the most important part.

Probably this https://github.com/jenkinsci/gitlab-plugin/blob/c8d5d7b89d2c7c5ae7a2cb3e30184558dff65f1e/src/main/java/com/dabsquared/gitlabjenkins/gitlab/api/model/Note.java#L11 has to be updated, but I am no programmer, I don't know for sure. Hopefully someone more knowledgeable than me could submit a PR soon.

Here's the full quote:
> The `id` column for notes on [GitLab.com](http://gitlab.com/) was converted from `integer` to `bigint` in the database to allow a higher range of values, see in this [MR](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/119705) for details.
> The values for the column now exceed the int datatypes range, which seems to be used for marshalling the value from the JSON in the Jenkins plugin.
 
```
Caused: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (2148334819) out of range of int (-2147483648 - 2147483647)
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1108] (through reference chain: com.dabsquared.gitlabjenkins.gitlab.hook.model.NoteHook["object_attributes"]->com.dabsquared.gitlabjenkins.gitlab.hook.model.NoteObjectAttributes["id"]
```
 
> The Plugin needs to be updated to with a data type appropriate for marshalling the data from bigint column datatype.

The question is if we can get it fixed for some of the older plugin versions as well. We (and I guess plenty of others) are using only LTS Jenkins releases and I am unsure what is the latest supported plugin version for these.

**Comment by MarkEWaite** [comment]
I've submitted a draft pull request that others can use in their tests.  The draft pull request is based on the 1.8 line, so it requires Jenkins 2.426.3 or newer.

* #1706 

The "checks" tab of that pull request will have an "Incrementals publisher" entry on the left side when the job is complete.  Inside that page there will be instructions and links that allow others to download the build so they can test it.

**Comment by MarkEWaite** [comment]
The incrementals link is not provided by the ci.jenkins.io job because the branch is out-of-date. Here is a zip file of the plugin built on my computer.

[gitlab-plugin.zip](https://github.com/user-attachments/files/17343146/gitlab-plugin.zip)

**Comment by simonefranconetti** [comment]
> The incrementals link is not provided by the ci.jenkins.io job because the branch is out-of-date. Here is a zip file of the plugin built on my computer.
> 
> [gitlab-plugin.zip](https://github.com/user-attachments/files/17343146/gitlab-plugin.zip)

I don't know if it's just me, but it seems not to work.

I think that this file should have the type of the `id` field changed accordingly `src/main/java/com/dabsquared/gitlabjenkins/gitlab/hook/model/NoteObjectAttributes.java`.

I'm not so confident with Java but I can push a fix in the existing PR if you enable changes from your fork @MarkEWaite or you can easily do it on your own. Let me know

**Comment by MarkEWaite** [comment]
Thanks for trying that first attempt @simonefranconetti .  Here is another zip file with the NoteObjectAttribute change:

[gitlab-plugin.zip](https://github.com/user-attachments/files/17344131/gitlab-plugin.zip)

**Comment by simonefranconetti** [comment]
@MarkEWaite Now it seems to work properly! Thank you so much

**Comment by rastakajakwanna** [comment]
@MarkEWaite I confirm this fixed the problem on Jenkins 2.440.3 too! Thank you! 🥇

**Comment by krisstern** [comment]
A new release https://github.com/jenkinsci/gitlab-plugin/releases/tag/gitlab-plugin-1.9.4 has been cut containing @MarkEWaite's fix for this issue.

**Comment by MarkEWaite** [comment]
[Release 1.8.2](https://github.com/jenkinsci/gitlab-plugin/releases/tag/gitlab-plugin-1.8.2) is available for older Jenkins versions with the same fix.
