### ISSUE TITLE
NPE on merge request

### ISSUE THREAD

**Issue by mattiasb** [jenkinsci/gitlab-plugin#184]
I've set up a Jenkins job at my company for building our main product. The job is supposed to build both on MERGE and PUSH (to master, develop and release/*). 
The builds are triggered and starts running but I get a NPE during the SCM phase. Here's the output:

```
GitLab Merge Request #130 : feature/silence_buildscript => develop
Building on master in workspace C:\Program Files (x86)\Jenkins\jobs\Important-Project\workspace
Wiping out workspace first.
Cloning the remote Git repository
Using shallow clone
Cloning repository git@git.mycompany.se:important-project/important-project.git
 > C:\Program Files (x86)\Git\bin\git.exe init C:\Program Files (x86)\Jenkins\jobs\Important-Project\workspace # timeout=10
Fetching upstream changes from git@git.mycompany.se:important-project/important-project.git
 > C:\Program Files (x86)\Git\bin\git.exe --version # timeout=10
using GIT_SSH to set credentials 
 > C:\Program Files (x86)\Git\bin\git.exe -c core.askpass=true fetch --tags --progress git@git.mycompany.se:important-project/important-project.git +refs/heads/*:refs/remotes/origin/* --depth=1
 > C:\Program Files (x86)\Git\bin\git.exe config remote.origin.url git@git.mycompany.se:important-project/important-project.git # timeout=10
 > C:\Program Files (x86)\Git\bin\git.exe config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > C:\Program Files (x86)\Git\bin\git.exe config remote.origin.url git@git.mycompany.se:important-project/important-project.git # timeout=10
Fetching upstream changes from git@git.mycompany.se:important-project/important-project.git
using GIT_SSH to set credentials 
 > C:\Program Files (x86)\Git\bin\git.exe -c core.askpass=true fetch --tags --progress git@git.mycompany.se:important-project/important-project.git +refs/heads/*:refs/remotes/origin/*
 > C:\Program Files (x86)\Git\bin\git.exe rev-parse "refs/remotes/origin/feature/silence_buildscript^{commit}" # timeout=10
 > C:\Program Files (x86)\Git\bin\git.exe rev-parse "refs/remotes/origin/origin/feature/silence_buildscript^{commit}" # timeout=10
Merging Revision bc231d4b073ebac551d9f39bcffe56ef56b8a0b0 (refs/remotes/origin/feature/silence_buildscript) to origin/develop, UserMergeOptions{mergeRemote='origin', mergeTarget='${gitlabTargetBranch}', mergeStrategy='default', fastForwardMode='--ff-only'}
 > C:\Program Files (x86)\Git\bin\git.exe rev-parse "origin/develop^{commit}" # timeout=10
 > C:\Program Files (x86)\Git\bin\git.exe config core.sparsecheckout # timeout=10
 > C:\Program Files (x86)\Git\bin\git.exe checkout -f origin/develop
 > C:\Program Files (x86)\Git\bin\git.exe merge --ff-only bc231d4b073ebac551d9f39bcffe56ef56b8a0b0 # timeout=10
 > C:\Program Files (x86)\Git\bin\git.exe config core.sparsecheckout # timeout=10
 > C:\Program Files (x86)\Git\bin\git.exe checkout -f bc231d4b073ebac551d9f39bcffe56ef56b8a0b0
FATAL: null
java.lang.NullPointerException
    at hudson.plugins.git.extensions.impl.PreBuildMerge.decorateRevisionToBuild(PreBuildMerge.java:88)
    at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:965)
    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1054)
    at hudson.scm.SCM.checkout(SCM.java:485)
    at hudson.model.AbstractProject.checkout(AbstractProject.java:1276)
    at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
    at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
    at hudson.model.Run.execute(Run.java:1738)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
```

Any idea what might be causing this?

**Comment by mattiasb** [comment]
We're running Jenkins `1.645`, GitLab CE `8.1.4` and git `1.9.5.msysgit.1`.

**Comment by warrenseine** [comment]
Same problem here. I set up Jenkins / GitLab to handle Merge Requests and tested with a very simple case (a repository with one text file and a merge request that just adds a file). I receive the same exception on the same line.

My configuration is almost the same : Jenkins `1.645`, GitLab CE `8.1.4`, but git `1.9.1`. All plugins are up-to-date.

I will upgrade GitLab and Git.

**Comment by mattiasb** [comment]
Cool, please write back here if it solves the issue!

**Comment by warrenseine** [comment]
Unfortunately, same error with GitLab `8.4.0` and Git `2.7.0`.

**Comment by mattiasb** [comment]
:(

**Comment by mattiasb** [comment]
I found my issue. I've been doing `Wipe & force clone` together with `shallow clone` in `git-plugin` to let every build start from a clean slate. The `shallow clone` will obviously not work together with `merge before build`. So yeah. My bad.

@warrenseine maybe you had done something similar?

**Comment by warrenseine** [comment]
@mattiasb Indeed, I was using `Shallow clone`. Thanks for the tip, unticking the checkbox fixed it!

**Comment by mattiasb** [comment]
Let's close this then. :)
