### ISSUE TITLE
Gitlab 8.5.4 Webhook to Jenkins

### ISSUE THREAD

**Issue by cdenneen** [jenkinsci/gitlab-plugin#222]
Project is setup as:
BuildFlow Project which is comprised of Freestyle -> Freestyle -> Multi-configuration Projects
First free-style is the actual Git project (and named module-profile_base_init_master) so that's why this message is misleading.
If I add git reference to the BuildFlow this now works even though the buildflow does nothing with the Git repository.

---

Hook execution failed: <!DOCTYPE html> Jenkins [Jenkins]var isRunAsTest=false; var rootURL=""; var resURL="/static/48acc275";crumb.init("", "");var Q=jQuery.noConflict()Skip to content createSearchBox("/search/");Jenkins Jenkins project Bug tracker Mailing Lists Twitter: @jenkinsci Oops!A problem occurred while processing the request. Please check our bug tracker to see if a similar problem has already been reported. If it is already reported, please vote and put a comment on it to let us gauge the impact of the problem. If you think this is a new issue, please file a new issue. When you file an issue, make sure to add the entire stack trace, along with the version of Jenkins and relevant plugins. The users list might be also useful in understanding what has happened.Stack tracejavax.servlet.ServletException: java.lang.IllegalArgumentException: This project does not use git:module-profile_base_init_master at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:796) at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876) at org.kohsuke.stapler.MetaClass$13.dispatch(MetaClass.java:411) at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746) at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876) at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649) at org.kohsuke.stapler.Stapler.service(Stapler.java:238) at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494) at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132) at com.smartcodeltd.jenkinsci.plugin.assetbundler.filters.LessCSS.doFilter(LessCSS.java:47) at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:129) at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:59) at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:129) at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:123) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482) at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84) at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76) at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482) at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482) at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482) at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) at org.eclipse.jetty.server.Server.handle(Server.java:370) at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489) at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960) at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021) at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865) at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668) at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52) at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:745) Caused by: java.lang.IllegalArgumentException: This project does not use git:module-profile_base_init_master at com.dabsquared.gitlabjenkins.GitLabPushTrigger$DescriptorImpl.getSourceRepoNameDefault(GitLabPushTrigger.java:888) at com.dabsquared.gitlabjenkins.GitLabPushTrigger.createActions(GitLabPushTrigger.java:288) at com.dabsquared.gitlabjenkins.GitLabPushTrigger.onPost(GitLabPushTrigger.java:238) at com.dabsquared.gitlabjenkins.GitLabWebHook.generatePushBuild(GitLabWebHook.java:378) at com.dabsquared.gitlabjenkins.GitLabWebHook.generateBuild(GitLabWebHook.java:338) at com.dabsquared.gitlabjenkins.GitLabWebHook.getDynamic(GitLabWebHook.java:146) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298) at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161) at org.kohsuke.stapler.MetaClass$13.dispatch(MetaClass.java:409) at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746) ... 51 more Page generated: Mar 7, 2016 9:38:55 PMREST APIJenkins ver. 1.643 Help us localize this page var footer = document.getElementById('l10n-footer'); var f = document.getElementById('footer'); f.insertBefore(footer,f.firstChild); footer.style.display="block"; var translation={}; translation.bundles = "WlKLPoXtSIO5Xm3CLjC/bsnvZIuFLTOHyUPT7i4I4qtKWCPL1bWOCezxM4JtIPABUmbRxTruHccOoeoIIG941G4f3mX5B5oMVkh6jGjW7a8ecxMYVNkP7Zn+ah/HCJF8DZBTi6HQ0qbDrXP43/aAmDA06lzWH2EZlRIEBBGA0gRqmwyQwMUQF6mH2pCJwEJa2vQ+G6AZSSDgY54EFXo7xF+KBjGY7ghZhs4EUOpONdNh/bUa0vcuvzS6pfSs/JhSmCNMTu5KvuSoeUw0mwab+5666KgjlPXxNDUUZbx97gqBdIyvb8nogqMuEt2AdqMdkygWdq7MWtR4HhJn7Ts/4OaEcXIBwvh62NIlbvw2/DiBx3L6grGu85s1IUNde8AFj6W9tKRdF9Ur1K2kKxUiPMsDiGLasSwmouIM+Ec9+f2MN9qvZGUUWHqDYei719u7"; translation.detectedLocale = ""; function showTranslationDialog() { if(!translation.launchDialog) loadScript("/static/48acc275/plugin/translation/dialog.js"); else translation.launchDialog(); return false; }

**Comment by WebDucer** [comment]
The same issue after update the plugin from 1.2.28 to 1.2.31.

**Comment by cdenneen** [comment]
Maybe the plugin needs BuildFlow support?

**Comment by WebDucer** [comment]
I use only the Git and the GitLab plugins. no other. But I get the same error output if I try to trigger new build with 1.2.31. The same build with 1.2.28 version works like a charm.

Job configuration on Jenkins:
- Freestyle job with only one build step (execute FAKE build script on Windows agent on command line).
- Git an GitLab configuration (without Fork or Tag Push) as described on the startpage.

**Comment by omehegan** [comment]
This happens when the plugin thinks your project is not configured to use Git. In addition to a GitLab trigger setup, you also must be using Git as your SCM, and you must have successfully run the job once in order for Jenkins to recognize that the project uses Git.

**Comment by WebDucer** [comment]
Git is setup in Jenkins job and works fine with version 1.2.28. With this version the job ran over 20 times in the last few days. With version 1.2.31 it doesn't work. After revert the plugin to 1.2.28 it works again.

**Comment by wl2776** [comment]
Same here. I've got the same error after upgrading Gitlab plugin on Jenkins to 1.2.31

**Comment by WebDucer** [comment]
Here is my output:

```
Hook execution failed: 




    <!DOCTYPE html>


    Jenkins [Jenkins]var isRunAsTest=false; var rootURL=""; var resURL="/static/edf1c447";crumb.init("", "");Skip to content createSearchBox("/search/");Jenkins Jenkins project Bug tracker Mailing Lists Twitter: @jenkinsci Oops!A problem occurred while processing the request.
        Please check our bug tracker to see if a similar problem has already been reported.
        If it is already reported, please vote and put a comment on it to let us gauge the impact of the problem.
        If you think this is a new issue, please file a new issue.
        When you file an issue, make sure to add the entire stack trace, along with the version of Jenkins and relevant plugins.
        The users list might be also useful in understanding what has happened.Stack tracejavax.servlet.ServletException: java.lang.NullPointerException
    at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:796)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
    at org.kohsuke.stapler.MetaClass$13.dispatch(MetaClass.java:411)
    at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
    at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
    at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
    at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:123)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
    at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
    at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
    at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
    at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
    at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
    at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:370)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
    at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
    at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at org.gitlab.api.GitlabAPI.createCommitStatus(GitlabAPI.java:809)
    at com.dabsquared.gitlabjenkins.GitLabPushRequest.createCommitStatus(GitLabPushRequest.java:44)
    at com.dabsquared.gitlabjenkins.GitLabPushTrigger.onPost(GitLabPushTrigger.java:250)
    at com.dabsquared.gitlabjenkins.GitLabWebHook.generatePushBuild(GitLabWebHook.java:378)
    at com.dabsquared.gitlabjenkins.GitLabWebHook.generateBuild(GitLabWebHook.java:338)
    at com.dabsquared.gitlabjenkins.GitLabWebHook.getDynamic(GitLabWebHook.java:146)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
    at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
    at org.kohsuke.stapler.MetaClass$13.dispatch(MetaClass.java:409)
    at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
    ... 47 more
Page generated: Mar 14, 2016 8:15:15 AMREST APIJenkins ver. 1.642.1
      Help us localize this page
    var footer = document.getElementById('l10n-footer');
    var f = document.getElementById('footer');
    f.insertBefore(footer,f.firstChild);
    footer.style.display="block";

    var translation={}; 
    translation.bundles = "gEXCLeg4GkTwjAGMcb0mgK7DFOJ5d7VY4Ugs3Wokl0BtWGIn2CtbVrtMVGKkx36sR4pStu4KVRRhe2HAigi7ir22J7KgsAzR5t1PkWFEeL2PfsCTFggb70zy3jHVU3Oos0Ii4e9HJ5EHTJydHYwOMCMIC9IDlXXFmTX8X7/xT7Xe9vi3DJOeZf7e2jgdsOzfyMegEdbmGYRssRpmt6stv6C57h5Jt/PVZxv4HNdfOnMpvrCUOvnh//GoVIxrHbamPR2OfpxIQksdXxpDX1zCViLX+wgahYhmO7/JCcnpFuaZ2GH0P8Pgyb50l029XOsqLhmE6jncOoN1YhjKPQ/GeftoCgbZuSp1jkVuVm3fesyoavEOXAEgpwsqfXvxCYGpmuYvnqVVzXETE2IrhmbyhXJFYTIUOenLCdlYQelxC/ZakVoBE7D4A7WMwVVjj62i";
    translation.detectedLocale = "";

    function showTranslationDialog() {
      if(!translation.launchDialog)
        loadScript("/static/edf1c447/plugin/translation/dialog.js");
      else
        translation.launchDialog();
      return false; 
    }
```

**Comment by cdenneen** [comment]
Seems fine with 1.642 (lts) and 1.652

**Comment by WebDucer** [comment]
We use in production GitLab 8.5.0 and Jenkins 1.638 (1.2.28 works, 1.2.31 doesn't work).

I tried to reproduce the problem with GitLab 8.5.0 (gitlab/gitlab-ce) and Jenkins 1.642.1 (Jenkins) as Docker container. The same result (1.2.28 works, after update on 1.2.31 doesn't work).

**Comment by WebDucer** [comment]
I found the reason, why it is not working any more.

In version 1.2.28 of the plugin Jenkins configuration doesn't require GitLab URL and API Token. In version 1.2.31 it is required. If URI and API Token are configured the version 1.2.31 works as expected.

**Comment by wl2776** [comment]
~~I've got configured GitLab URL and token, but it still doesn't work~~
**Update**
My API token has been broken. Probably, I've regenerated it some time ago, don't remember. After entering correct token, everything works again.

**Comment by alexmufatti** [comment]
I've the same problem after updating to 1.1.31.
In configuration I've URI and API Token configured as @WebDucer said but this didn't solve the problem.

Any other suggestion?

**Comment by alexmufatti** [comment]
I've found the solution to my problem. It was the slack integration plugin that was updated from 1.8 to 2.0.

I don't know how the 2 plugins interact but when I downgraded slack plugin everything worked.

**Comment by DieBauer** [comment]
I've had the same problem. First-time installed plugin version 1.1.31 and the Gitlab hook didn't work on <Jenkins>/project/<id>, even with the API token filled. I've downgraded to 1.1.28 and the hook did work. This morning I upgraded the plugin to 1.1.32 and it still works (or works again).

**Comment by omehegan** [comment]
@cdenneen can you confirm that this is resolved in the latest release and close this issue if so?
