### ISSUE TITLE
Merge Request Rebuild with new push to source branch is break.

### ISSUE THREAD

**Issue by ghost** [jenkinsci/gitlab-plugin#237]
FATAL: Null value not allowed as an environment variable: gitlabUserEmail
java.lang.IllegalArgumentException: Null value not allowed as an environment variable: gitlabUserEmail
    at hudson.EnvVars.put(EnvVars.java:356)
    at hudson.model.StringParameterValue.buildEnvironment(StringParameterValue.java:56)
    at hudson.model.ParametersAction.buildEnvVars(ParametersAction.java:89)
    at hudson.model.AbstractBuild.getEnvironment(AbstractBuild.java:950)
    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1046)
    at hudson.scm.SCM.checkout(SCM.java:485)
    at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
    at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
    at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
    at hudson.model.Run.execute(Run.java:1738)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
[android-lint] Skipping publisher since build result is FAILURE
Email was triggered for: Failure - Any
Sending email for trigger: Failure - Any
Error retrieving environment vars: Null value not allowed as an environment variable: gitlabUserEmail
An attempt to send an e-mail to empty list of recipients, ignored.
Finished: FAILURE

Is anything I don't config ?

**Comment by omehegan** [comment]
Update to the latest version of the plugin, .32. This bug was fixed in that release. Please close if fixed.

**Comment by omorillo** [comment]
@JavanEu Did the update fix the issue?
