### ISSUE TITLE
Jenkins authentication failed

### ISSUE THREAD

**Issue by fabMrc** [jenkinsci/gitlab-plugin#255]
Hi

I tried this plugin with a secure jenkins and I have a 401 ERROR when I execute the webhook url 
How do you configure gitlab (CE edition) for giving credentials parameters on webhook event ?

**Comment by osamahf** [comment]
In gitlab weeb-hooks add your credential in the url and disable ssl verification  if you work with a self signed certificate.

**Comment by fabMrc** [comment]
Can you give me the url syntax with the credentials parameters ?

**Comment by osamahf** [comment]
what do you mean by a secure jenkins ? 
if jenkins is secured by server proxy the url syntax will be : http://user:pass@jenkins_ip/project/job

if jenkins secured with jenkins global Security you don't need to add your credential in the url.

**Comment by fabMrc** [comment]
Jenkins is secured with global security and Webhook raise 401 ERROR so it might be a problem of authentication

**Comment by osamahf** [comment]
try this : 

http://user:token@jenkins_server/project/job

You can obtain the token  from http://jenkins_server/user/username/configure

**Comment by fabMrc** [comment]
It failed !

`Hook execution failed: <!DOCTYPE html> Jenkins [Jenkins]var isRunAsTest=false; var rootURL="/jenkins"; var resURL="/jenkins/static/3218044d";crumb.init("", "");Skip to content log in createSearchBox("/jenkins/search/");Jenkins Jenkins project Bug tracker Mailing Lists Twitter: @jenkinsci Oops!A problem occurred while processing the request. Please check our bug tracker to see if a similar problem has already been reported. If it is already reported, please vote and put a comment on it to let us gauge the impact of the problem. If you think this is a new issue, please file a new issue. When you file an issue, make sure to add the entire stack trace, along with the version of Jenkins and relevant plugins. The users list might be also useful in understanding what has happened.Stack tracejavax.servlet.ServletException: java.lang.NullPointerException at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:796) at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876) at org.kohsuke.stapler.MetaClass$13.dispatch(MetaClass.java:411) at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746) at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876) at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649) at org.kohsuke.stapler.Stapler.service(Stapler.java:238) at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132) at com.sonymobile.jenkins.plugins.kerberossso.KerberosSSOFilter.doFilter(KerberosSSOFilter.java:208) at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:129) at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:123) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84) at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87) at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87) at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87) at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87) at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87) at jenkins.security.BasicHeaderProcessor.success(BasicHeaderProcessor.java:140) at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:82) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87) at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249) at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87) at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76) at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) at`

**Comment by omehegan** [comment]
@fabMrc can you tell me what authentication mechanism you are using in Jenkins? Is it just Jenkins internal usernames and passwords? Or are you using something external like LDAP or OAuth?

**Comment by jblaine** [comment]
I think I am in the same boat, no matter whether I try the http or https endpoints, with or without SSL verification.

We're using LDAP authentication in Jenkins.

WebHook URL configured in Gitlab 8.6 as http://jblaine:MyAPIkeyHere@jenkins.our.org:8080/project/rcf-chef

```
Apr 21, 2016 2:48:08 PM com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
INFO: WebHook called with url:
Apr 21, 2016 2:48:08 PM com.dabsquared.gitlabjenkins.GitLabPushTrigger onPost
INFO: rcf-chef triggered for push.
Apr 21, 2016 2:48:08 PM com.dabsquared.gitlabjenkins.GitLabPushTrigger createActions
INFO: GitLab Push Request from branch master.
Apr 21, 2016 2:48:08 PM com.dabsquared.gitlabjenkins.GitLabPushTrigger createActions
INFO: Trying to get name and URL for job: rcf-chef
Apr 21, 2016 2:48:08 PM org.eclipse.jetty.util.log.JavaUtilLog warn
WARNING: Error while serving http://jenkins.our.org:8080/project/rcf-chef
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:320)
        at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:163)
        at org.kohsuke.stapler.MetaClass$11.dispatch(MetaClass.java:378)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
        at org.kohsuke.stapler.MetaClass$11.dispatch(MetaClass.java:380)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
        at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
        at hudson.plugins.audit_trail.AuditTrailFilter.doFilter(AuditTrailFilter.java:95)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
        at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:59)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
        at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
        at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at jenkins.security.BasicHeaderProcessor.success(BasicHeaderProcessor.java:140)
        at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:82)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
        at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
        at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
        at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:370)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
        at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.gitlab.api.GitlabAPI.createCommitStatus(GitlabAPI.java:809)
        at com.dabsquared.gitlabjenkins.GitLabPushRequest.createCommitStatus(GitLabPushRequest.java:44)
        at com.dabsquared.gitlabjenkins.GitLabPushTrigger.onPost(GitLabPushTrigger.java:250)
        at com.dabsquared.gitlabjenkins.GitLabWebHook.generatePushBuild(GitLabWebHook.java:378)
        at com.dabsquared.gitlabjenkins.GitLabWebHook.generateBuild(GitLabWebHook.java:338)
        at com.dabsquared.gitlabjenkins.GitLabWebHook.getDynamic(GitLabWebHook.java:146)
        ... 75 more
```

**Comment by omehegan** [comment]
@jblaine can you tell me what Authorization strategy you have configured in Jenkins? This would be distinct from the authentication strategy (LDAP in your case). E.g. matrix, logged in user can do anything, legacy mode, etc.

If you want, join the #gitlab-plugin channel on the irc.freenode.org IRC network, and I can help you there in realtime.

**Comment by jblaine** [comment]
Role-Based Strategy

**Comment by omehegan** [comment]
I actually don't think you should need to put any auth information in the web hook URL. I use Google auth for Jenkins web UI access control, Anonymous users only have read access and can't run jobs. Yet I can trigger jobs from GitLab with the plugin just using a standard URL of https://jenkins:8080/project/mybuild  Even if I remove all access for the Anonymous user, I can still trigger builds.

@jblaine what versions of Jenkins and the GitLab plugin are you using? Have you created a user for Jenkins in GitLab, and given that user Developer-level permissions on the project you are trying to build? The error you are getting is quite different from the one @fabMrc is getting.

**Comment by omehegan** [comment]
@fabMrc what version of the plugin are you using? What are your settings for Security Realm and Authorization in the Jenkins Global Security configuration page?

**Comment by jblaine** [comment]
@omehegan I agree. I tried adding my creds to the WebHook URL only because I saw it mentioned here. Previously the hook had no creds of mine and was working. We are not using the optional "extra" configuration where one creates a user in Gitlab and configures the Gitlab Plugin to use it. We are also not yet trying to do anything in the plugin with merge requests. We are using version 1.1.32 of the Gitlab Plugin from the official Jenkins plugin repository.

**Comment by omehegan** [comment]
@jblaine so you had the plugin working at one point and then it stopped? Do you know what could have changed?

I think you should try creating the appropriate Jenkins user in GitLab and giving it access to the project you are trying to build. I have a feeling that this is causing your problem, and although I see that the docs say it is optional, I suspect that may not (or may no longer be) the case.

**Comment by jblaine** [comment]
Yes, it used to work. The only recent change was our upgrade to Gitlab 8.6.6 from 8.5.something. That was done last week as I recall.

**Comment by fabMrc** [comment]
Hi

I retry recently, upgrade gitlab CI plugin on jenkins and delete old plugins (gitlab merge request etc...) 
It works nice with and without authentication. 
However I actived Kerberos plugin and it failed. Basically the kerberos plugin allow bypass the kerberos process by enriching HTTP Header with a skip information. I think I may use a proxy in front of my jenkins for that because no way in gitlab webhook form to specify any header instructions. I will try that asap.

**Comment by jblaine** [comment]
Weird. My problem described in this issue is working now after an upgrade to 1.2.0 of the plugin.

**Comment by omehegan** [comment]
@jblaine version 1.2.0 discarded the gitlab API library we were using in favor of a simplified internal implementation. So you were probably hitting a bug in that.
