### ISSUE TITLE
Host Key Verification Failed

### ISSUE THREAD

**Issue by devmattrick** [jenkinsci/gitlab-plugin#265]
Hello,

Whenever I push to my GitLab instance, I get the error below with the build failing immediately. The issue is of course that Jenkins is attempting to use SSH to authenticate rather than the HTTPS that I had configured. I'm not too sure the cause of the issue and would appreciate it if you could provide any assistance.

Thank you!

```
Started by GitLab push by mattrick
Building in workspace /var/lib/jenkins/workspace/Example
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Done
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from 2 remote Git repositories
 > git config remote.mattrick/Example.url git@git.example.com:mattrick/Example.git # timeout=10
Fetching upstream changes from git@git.example.com:mattrick/Example.git
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress git@git.example.com:mattrick/Example.git +refs/heads/*:refs/remotes/mattrick/Example/*
ERROR: Error fetching remote repo 'mattrick/Example'
hudson.plugins.git.GitException: Failed to fetch from git@git.example.com:mattrick/Example.git
  at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:810)
  at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1067)
  at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1098)
  at hudson.scm.SCM.checkout(SCM.java:485)
  at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
  at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
  at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
  at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
  at hudson.model.Run.execute(Run.java:1738)
  at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:531)
  at hudson.model.ResourceController.execute(ResourceController.java:98)
  at hudson.model.Executor.run(Executor.java:410)
Caused by: hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress git@git.example.com:mattrick/Example.git +refs/heads/*:refs/remotes/mattrick/Example/*" returned status code 128:
stdout: 
stderr: Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

  at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1719)
  at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1463)
  at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:63)
  at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:314)
  at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:808)
  ... 11 more
ERROR: null
Archiving artifacts
Finished: FAILURE
```

**Comment by omehegan** [comment]
This is not an issue with the GitLab plugin. It seems like the git configuration of your job, where code is checked out, is invalid. I'm assuming the job also doesn't work when run manually?

**Comment by devmattrick** [comment]
When run manually it appears to not even replace the variables at all:

```
Started by user mattrick
Building in workspace /var/lib/jenkins/workspace/Example
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Done
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from 2 remote Git repositories
 > git config remote.${gitlabSourceRepoName}.url ${gitlabSourceRepoURL} # timeout=10
Fetching upstream changes from ${gitlabSourceRepoURL}
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress ${gitlabSourceRepoURL} +refs/heads/*:refs/remotes/${gitlabSourceRepoName}/*
ERROR: Error fetching remote repo '${gitlabSourceRepoName}'
hudson.plugins.git.GitException: Failed to fetch from ${gitlabSourceRepoURL}
  at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:810)
  at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1067)
  at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1098)
  at hudson.scm.SCM.checkout(SCM.java:485)
  at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
  at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
  at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
  at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
  at hudson.model.Run.execute(Run.java:1738)
  at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:531)
  at hudson.model.ResourceController.execute(ResourceController.java:98)
  at hudson.model.Executor.run(Executor.java:410)
Caused by: hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress ${gitlabSourceRepoURL} +refs/heads/*:refs/remotes/${gitlabSourceRepoName}/*" returned status code 128:
stdout: 
stderr: fatal: '${gitlabSourceRepoURL}' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

  at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1719)
  at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1463)
  at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:63)
  at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:314)
  at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:808)
  ... 11 more
ERROR: null
Archiving artifacts
Finished: FAILURE
```

I'm obviously doing something wrong here, but I never defined an SSH URI.

**Comment by devmattrick** [comment]
Decided just to add an SSH key; solved.
