### ISSUE TITLE
Merge request not triggering in Jenkins with gitlab-plugin 1.1.32

### ISSUE THREAD

**Issue by jsyrjala** [jenkinsci/gitlab-plugin#267]
I upgraded gitlab-plugin from 1.1.28 to 1.1.32 and merge request no longer trigger builds in Jenkins.

With gitlab-plugin 1.1.28 merge request were working just fine.

Environment:
- Gitlab server 8.5.10
- Jenkins ver. 1.651.1
- Jenkins running on Ubuntu Linux 

My jenkins logs this when I push to a merge request:

```
INFO: WebHook called with url: 
Apr 22, 2016 5:06:13 PM com.dabsquared.gitlabjenkins.GitLabWebHook generateMergeRequestBuild
INFO: Existing Merge Request, build will be trigged by buildOpenMergeRequests instead
Apr 22, 2016 5:06:14 PM com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
INFO: WebHook called with url: 
Apr 22, 2016 5:06:15 PM com.dabsquared.gitlabjenkins.GitLabPushTrigger onPost
INFO: trigger on merge request not set
```

**Comment by jsyrjala** [comment]
I tested also with gitlab-plugin 1.2.0: the problem still exists.

Now I get this in Jenkins log when push to branch occurs and GitLab notifies jenkins.

```
Apr 27, 2016 10:13:23 AM com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
INFO: WebHook called with url: /jenkins/project/my-merge-requests
Apr 27, 2016 10:13:23 AM com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
INFO: WebHook called with url: /jenkins/project/my-merge-requests
```

**Comment by coder-hugo** [comment]
Can you please provide the configuration of your Jenkins job. Additionally you could configure a logger in your Jenkins for "com.dabsquared.gitlabjenkins" and paste its output here to get some more information what's happening in your Jenkins.

**Comment by jagardaniel** [comment]
**EDIT**: I upgraded GitLab to 8.7.0 and it works now.

I think I have the same issue. Push requests works great but merge requests seems to fail. 

GitLab: 8.3.7
Jenkins: 2.0
gitlab-plugin: 1.2.0    

Here is some output from **/var/log/jenkins/jenkins.log** when a merge request is triggered from GitLab:

```
Apr 29, 2016 8:54:36 PM com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
INFO: api triggered for merge request.
Apr 29, 2016 8:54:36 PM org.eclipse.jetty.util.log.JavaUtilLog warn
WARNING: Error while serving http://jenkins.domain.com/project/api
java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor599.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:320)
        at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:163)
        at org.kohsuke.stapler.MetaClass$11.dispatch(MetaClass.java:378)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
        at org.kohsuke.stapler.MetaClass$11.dispatch(MetaClass.java:380)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
        at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
        at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at com.dabsquared.gitlabjenkins.webhook.GitLabWebHook$GitlabWebHookCrumbExclusion.process(GitLabWebHook.java:53)
        at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:58)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
        at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:135)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
        at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
        at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: sourceRepoHomepage must not be null.
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:204)
        at com.dabsquared.gitlabjenkins.cause.CauseData.<init>(CauseData.java:48)
        at com.dabsquared.gitlabjenkins.cause.CauseDataBuilder.build(CauseDataBuilder.java:324)
        at com.dabsquared.gitlabjenkins.trigger.handler.merge.MergeRequestHookTriggerHandlerImpl.retrieveCauseData(MergeRequestHookTriggerHandlerImpl.java:82)
        at com.dabsquared.gitlabjenkins.trigger.handler.merge.MergeRequestHookTriggerHandlerImpl.retrieveCauseData(MergeRequestHookTriggerHandlerImpl.java:26)
        at com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler.createActions(AbstractWebHookTriggerHandler.java:50)
        at com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler.handle(AbstractWebHookTriggerHandler.java:38)
        at com.dabsquared.gitlabjenkins.trigger.handler.merge.MergeRequestHookTriggerHandlerImpl.handle(MergeRequestHookTriggerHandlerImpl.java:39)
        at com.dabsquared.gitlabjenkins.trigger.handler.merge.MergeRequestHookTriggerHandlerImpl.handle(MergeRequestHookTriggerHandlerImpl.java:26)
        at com.dabsquared.gitlabjenkins.GitLabPushTrigger.onPost(GitLabPushTrigger.java:186)
        at com.dabsquared.gitlabjenkins.webhook.build.MergeRequestBuildAction$1.run(MergeRequestBuildAction.java:37)
        at hudson.security.ACL.impersonate(ACL.java:198)
        at com.dabsquared.gitlabjenkins.webhook.build.MergeRequestBuildAction.execute(MergeRequestBuildAction.java:33)
        at com.dabsquared.gitlabjenkins.webhook.GitLabWebHook.getDynamic(GitLabWebHook.java:44)
        ... 65 more
```

And here is the data from the logging filter:

```
Apr 29, 2016 8:54:36 PM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/api
Apr 29, 2016 8:54:36 PM FINE com.dabsquared.gitlabjenkins.webhook.build.MergeRequestBuildAction
MergeRequest: {
  "object_kind" : "merge_request",
  "user" : {
    "name" : "daniel",
    "username" : "daniel",
    "avatar_url" : "http://www.gravatar.com/avatar/...................."
  },
  "repository" : {
    "name" : "api",
    "url" : "git@git.i.domain.com:project/api.git",
    "description" : "Project API",
    "homepage" : "http://git.i.domain.com/project/api"
  },
  "object_attributes" : {
    "id" : 14,
    "target_branch" : "develop",
    "source_branch" : "feature/dm-openstack",
    "source_project_id" : 8,
    "author_id" : 2,
    "assignee_id" : null,
    "title" : "Feature/dm openstack",
    "created_at" : "2016-04-29 18:54:36 UTC",
    "updated_at" : "2016-04-29 18:54:36 UTC",
    "milestone_id" : null,
    "state" : "opened",
    "merge_status" : "unchecked",
    "target_project_id" : 8,
    "iid" : 12,
    "description" : "",
    "position" : 0,
    "locked_at" : null,
    "updated_by_id" : null,
    "merge_error" : null,
    "merge_params" : { },
    "merge_when_build_succeeds" : false,
    "merge_user_id" : null,
    "source" : {
      "name" : "api",
      "ssh_url" : "git@git.i.domain.com:project/api.git",
      "http_url" : "http://git.i.domain.com/project/api.git",
      "web_url" : "http://git.i.domain.com/project/api",
      "namespace" : "project",
      "visibility_level" : 0
    },
    "target" : {
      "name" : "api",
      "ssh_url" : "git@git.i.domain.com:project/api.git",
      "http_url" : "http://git.i.domain.com/project/api.git",
      "web_url" : "http://git.i.domain.com/project/api",
      "namespace" : "project",
      "visibility_level" : 0
    },
    "last_commit" : {
      "id" : "d3776aac328c96fb550df6e75e2c29fd7241c96d",
      "message" : "test again\n",
      "timestamp" : "2016-04-29T20:26:35+02:00",
      "url" : "http://git.i.domain.com/project/api/commit/d3776aac328c96fb550df6e75e2c29fd7241c96d",
      "author" : {
        "name" : "Daniel",
        "email" : "myemail@mail.com"
      }
    },
    "work_in_progress" : false,
    "url" : "http://git.i.domain.com/project/api/merge_requests/12",
    "action" : "open"
  }
}
Apr 29, 2016 8:54:36 PM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
api triggered for merge request.
```

I see commits from the last couple of days that seems to change something related to merge requests (I have never touched Java). So it could be fixed already :)

/Daniel

**Comment by omehegan** [comment]
@jagardaniel so is your issue resolved now?

@jsyrjala version 1.2.1 of the plugin was just released. Please update to that and see if it resolves your issue. If you are using Pipeline/Workflow jobs, please note that you will need to make changes to your Pipeline script. See https://github.com/jenkinsci/gitlab-plugin#jenkins-job-configuration for details.

**Comment by jagardaniel** [comment]
@omehegan Thanks for the reply. Yes, the issue was resolved when I upgraded GitLab to the latest version. I will try with the new version of the plugin later today.

**Comment by jsyrjala** [comment]
@omehegan I can test this on Monday.

**Comment by jsyrjala** [comment]
1.2.1 doesn't work for me. I am using a freestyle job with configuration
-   Build on Merge Request Events:      enabled
-   Build on Push Events:       enabled
-   Rebuild open Merge Requests:        on push to source branch
-   Enable [ci-skip]:       enabled
-   Set build description to build cause (eg. Merge request or Git Push ):      enabled
-   Add note with build status on merge requests:       enabled
-   Use GitLab CI features (GitLab 8.1 required!)   :   enabled
-   Vote added to note with build status on merge requests:  enabled
- Filter branches. Exclude: master

I made a force push to my branch and this what happens in log with gitlab-plugin 1.2.1

```
Apr 30, 2016 10:33:12 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /jenkins/project/my-job
Apr 30, 2016 10:33:12 AM FINE com.dabsquared.gitlabjenkins.webhook.build.MergeRequestBuildAction
MergeRequest: {
  "object_kind" : "merge_request",
  "user" : {
...

Apr 30, 2016 10:33:13 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /jenkins/project/my-job
Apr 30, 2016 10:33:13 AM FINE com.dabsquared.gitlabjenkins.webhook.build.PushBuildAction
Push: {
  "object_kind" : "push",
...
```

This is what happens with force push in gitlab-plugin 1.1.28 when things are working.

```
Apr 30, 2016 10:40:40 AM INFO com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
WebHook called with url: 
Apr 30, 2016 10:40:40 AM FINE com.dabsquared.gitlabjenkins.GitLabWebHook
data: {
    "object_kind": "merge_request",
    "user":     {
...
Apr 30, 2016 10:40:40 AM INFO com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
WebHook called with url: 
Apr 30, 2016 10:40:40 AM FINE com.dabsquared.gitlabjenkins.GitLabWebHook
data: {
    "object_kind": "push",
...
Apr 30, 2016 10:40:40 AM INFO com.dabsquared.gitlabjenkins.GitLabWebHook generateMergeRequestBuild
Existing Merge Request, build will be trigged by buildOpenMergeRequests instead
Apr 30, 2016 10:40:40 AM FINE com.dabsquared.gitlabjenkins.GitLab
Connecting to Gitlab server (https://git.my-server.com/)
Apr 30, 2016 10:40:43 AM FINE com.dabsquared.gitlabjenkins.GitLabWebHook
Generating new merge trigger from org.gitlab.api.models.GitlabMergeRequest@283b0f13
 source: my-branch
 target: master
 state: opened
 assign: null
 author: org.gitlab.api.models.GitlabUser@1ad836e9
 id: 332
 iid: 229
 last commit: f9764f7feb1c5784a7bcb78b6079388a5871fa6e


Apr 30, 2016 10:40:43 AM INFO com.dabsquared.gitlabjenkins.GitLabPushTrigger$3 run
my-job triggered for merge request.
Apr 30, 2016 10:40:43 AM INFO com.dabsquared.gitlabjenkins.GitLabPushTrigger$3 createActions
Trying to get name and URL for job: my-job
Apr 30, 2016 10:40:43 AM FINE com.dabsquared.gitlabjenkins.GitLab
Connecting to Gitlab server (https://git.my-server.com/)
Apr 30, 2016 10:40:43 AM INFO com.dabsquared.gitlabjenkins.GitLabPushTrigger$3 run
GitLab Merge Request detected in my-job. Triggering  #1619
```

**Comment by coder-hugo** [comment]
@jsyrjala can you please provide the complete log output. If the JSON contains some sensitive data just filter this out and not the complete JSON.

**Comment by jsyrjala** [comment]
Got it working now. It seems that upgrading to 1.2.1 disabled the gitlab-plugin in all the jobs and downgrading back to 1.1.28 enabled it again and I didn't check the configuration while the 1.2.1 was installed. Once I enabled the configuration in 1.2.1, all seems to work now.

**Comment by omehegan** [comment]
That's very strange. I have not seen that behavior when I upgraded the plugin. I wonder if this is an issue upgrading from 1.1.28 directly to 1.2.1. I have always upgraded incrementally.

**Comment by jsyrjala** [comment]
Maybe it is related to exclude branches functionality I was using? At least UI for that has changed (and maybe also underlaying configuration) from 1.1.28 to 1.2.0

**Comment by yuyan-seik** [comment]
I'm having the same issue. Pipeline job is working fine but multibranch pipeline job seems not processing the webhook.

Log from /var/lib/jenkins/jenkins.log
com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
INFO: WebHook called with url: /project/multibranchprojectname

GitLab: CE 9.4.1
Jenkins: 2.107.3
gitlab-plugin: 1.5.6

**Comment by yuyan-seik** [comment]
I'm having the same issue. Pipeline job is working fine but multibranch pipeline job seems not processing the webhook.

Log from /var/lib/jenkins/jenkins.log
com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
INFO: WebHook called with url: /project/multibranchprojectname

GitLab: CE 9.4.1
Jenkins: 2.107.3
gitlab-plugin: 1.5.6

**Comment by yuyan-seik** [comment]
I'm having the same issue. Pipeline job is working fine but multibranch pipeline job seems not processing the webhook.

Log from /var/lib/jenkins/jenkins.log
com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
INFO: WebHook called with url: /project/multibranchprojectname

GitLab: CE 9.4.1
Jenkins: 2.107.3
gitlab-plugin: 1.5.6

**Comment by InfoSec812** [comment]
I am having this same issue on a brand-new install of Jenkins with version 1.5.11. The MR JSON body is delivered, but pipeline never starts. When I send a "Push" event it works fine.

Trigger Config:

```
   triggers {
        gitlab(
            triggerOnPush: true, 
            triggerOnMergeRequest: true, 
            branchFilterType: 'All',
            secretToken: "REDACTED"
        )
    }
```

Example JSON Body:

```
MergeRequest: {
  "object_kind" : "merge_request",
  "event_type" : "merge_request",
  "user" : {
    "name" : "John Smith",
    "username" : "johnsmith",
    "avatar_url" : "https://secure.gravatar.com/avatar/BLAH?s=80&d=identicon"
  },
  "project" : {
    "id" : 11209262,
    "name" : "REDACTED",
    "description" : "REDACTED",
    "web_url" : "https://gitlab.com/REDACTED",
    "avatar_url" : null,
    "git_ssh_url" : "git@gitlab.com:REDACTED.git",
    "git_http_url" : "https://gitlab.com/REDACTED.git",
    "namespace" : "REDACTED",
    "visibility_level" : 0,
    "path_with_namespace" : "REDACTED",
    "default_branch" : "master",
    "ci_config_path" : null,
    "homepage" : "https://gitlab.com/REDACTED",
    "url" : "git@gitlab.com:REDACTED.git",
    "ssh_url" : "git@gitlab.com:REDACTED.git",
    "http_url" : "https://gitlab.com/REDACTED.git"
  },
  "object_attributes" : {
    "assignee_id" : 3463172,
    "author_id" : 3464157,
    "created_at" : "2019-03-07T23:28:15.870Z",
    "description" : "",
    "head_pipeline_id" : null,
    "id" : 25403456,
    "iid" : 1,
    "last_edited_at" : null,
    "last_edited_by_id" : null,
    "merge_commit_sha" : "6ae8e8d439809edb618f06340535539862334a34",
    "merge_error" : null,
    "merge_params" : {
      "force_remove_source_branch" : "1"
    },
    "merge_status" : "can_be_merged",
    "merge_user_id" : null,
    "merge_when_pipeline_succeeds" : false,
    "milestone_id" : null,
    "source_branch" : "add-working-operator",
    "source_project_id" : 11209262,
    "state" : "merged",
    "target_branch" : "master",
    "target_project_id" : 11209262,
    "time_estimate" : 0,
    "title" : "Add working operator",
    "updated_at" : "2019-03-07T23:30:25.698Z",
    "updated_by_id" : null,
    "url" : "https://gitlab.com/REDACTED/merge_requests/1",
    "source" : {
      "id" : 11209262,
      "name" : "ITCM NGM Operator",
      "description" : "REDACTED",
      "web_url" : "https://gitlab.com/REDACTED",
      "avatar_url" : null,
      "git_ssh_url" : "git@gitlab.com:REDACTED.git",
      "git_http_url" : "https://gitlab.com/REDACTED.git",
      "namespace" : "REDACTED",
      "visibility_level" : 0,
      "path_with_namespace" : "REDACTED",
      "default_branch" : "master",
      "ci_config_path" : null,
      "homepage" : "https://gitlab.com/REDACTED",
      "url" : "git@gitlab.com:REDACTED.git",
      "ssh_url" : "git@gitlab.com:REDACTED.git",
      "http_url" : "https://gitlab.com/REDACTED.git"
    },
    "target" : {
      "id" : 11209262,
      "name" : "REDACTED",
      "description" : "The Operator for NGM ITCM",
      "web_url" : "https://gitlab.com/REDACTED",
      "avatar_url" : null,
      "git_ssh_url" : "git@gitlab.com:REDACTED.git",
      "git_http_url" : "https://gitlab.com/REDACTED.git",
      "namespace" : "REDACTED",
      "visibility_level" : 0,
      "path_with_namespace" : "REDACTED",
      "default_branch" : "master",
      "ci_config_path" : null,
      "homepage" : "https://gitlab.com/REDACTED",
      "url" : "git@gitlab.com:REDACTED.git",
      "ssh_url" : "git@gitlab.com:REDACTED.git",
      "http_url" : "https://gitlab.com/REDACTED.git"
    },
    "last_commit" : {
      "id" : "REDACTED",
      "message" : "REDACTED\n",
      "timestamp" : "2019-03-07T23:05:19Z",
      "url" : "https://gitlab.com/REDACTED/commit/REDACTED",
      "author" : {
        "name" : "REDACTED",
        "email" : "REDACTED"
      }
    },
    "work_in_progress" : false,
    "total_time_spent" : 0,
    "human_total_time_spent" : null,
    "human_time_estimate" : null
  },
  "labels" : [ ],
  "changes" : {
    "assignee" : {
      "previous" : null,
      "current" : {
        "name" : "REDACTED",
        "username" : "REDACTED",
        "avatar_url" : "https://secure.gravatar.com/avatar/REDACTED?s=80&d=identicon"
      }
    },
    "total_time_spent" : {
      "previous" : null,
      "current" : 0
    }
  },
  "repository" : {
    "name" : "REDACTED",
    "url" : "git@gitlab.com:REDACTED.git",
    "description" : "REDACTED",
    "homepage" : "https://gitlab.com/REDACTED"
  },
  "assignee" : {
    "name" : "REDACTED",
    "username" : "REDACTED",
    "avatar_url" : "https://secure.gravatar.com/avatar/REDACTED?s=80&d=identicon"
  }
}
```
