### ISSUE TITLE
'java.lang.NullPointerException: sourceRepoHomepage must not be null' on MR triggers

### ISSUE THREAD

**Issue by omehegan** [jenkinsci/gitlab-plugin#273]
Running GitLab 7.14.3 and version 1.2.0 of the plugin, I get the exception shown above when a push or MR tries to trigger a build. Strangely, when I use the 'Test Hook' button, the build triggers OK. This fails with both Freestyle and Pipeline builds. I'm guessing that this value may not be set in older versions of GitLab? @dblessing any thoughts on this?

Full exception log:

2016-04-26 22:55:27.122219500 java.lang.reflect.InvocationTargetException
2016-04-26 22:55:27.122221500   at sun.reflect.GeneratedMethodAccessor249.invoke(Unknown Source)
2016-04-26 22:55:27.122222500   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2016-04-26 22:55:27.122224500   at java.lang.reflect.Method.invoke(Method.java:606)
2016-04-26 22:55:27.122241500   at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:320)
2016-04-26 22:55:27.122242500   at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:163)
2016-04-26 22:55:27.122244500   at org.kohsuke.stapler.MetaClass$11.dispatch(MetaClass.java:378)
2016-04-26 22:55:27.122245500   at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
2016-04-26 22:55:27.122246500   at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
2016-04-26 22:55:27.122252500   at org.kohsuke.stapler.MetaClass$11.dispatch(MetaClass.java:380)
2016-04-26 22:55:27.122254500   at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
2016-04-26 22:55:27.122255500   at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
2016-04-26 22:55:27.122257500   at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
2016-04-26 22:55:27.122258500   at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
2016-04-26 22:55:27.122265500   at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
2016-04-26 22:55:27.122267500   at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
2016-04-26 22:55:27.122268500   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
2016-04-26 22:55:27.122270500   at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
2016-04-26 22:55:27.122271500   at com.cloudbees.jenkins.support.slowrequest.SlowRequestFilter.doFilter(SlowRequestFilter.java:37)
2016-04-26 22:55:27.122276500   at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
2016-04-26 22:55:27.122278500   at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:58)
2016-04-26 22:55:27.122279500   at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
2016-04-26 22:55:27.122281500   at jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:117)
2016-04-26 22:55:27.122285500   at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
2016-04-26 22:55:27.122287500   at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126)
2016-04-26 22:55:27.122289500   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
2016-04-26 22:55:27.122290500   at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
2016-04-26 22:55:27.122296500   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
2016-04-26 22:55:27.122298500   at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
2016-04-26 22:55:27.122299500   at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
2016-04-26 22:55:27.122301500   at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
2016-04-26 22:55:27.122317500   at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
2016-04-26 22:55:27.122319500   at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
2016-04-26 22:55:27.122320500   at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
2016-04-26 22:55:27.122322500   at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
2016-04-26 22:55:27.122326500   at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:135)
2016-04-26 22:55:27.122328500   at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
2016-04-26 22:55:27.122330500   at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
2016-04-26 22:55:27.122337500   at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
2016-04-26 22:55:27.122338500   at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
2016-04-26 22:55:27.122340500   at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
2016-04-26 22:55:27.122341500   at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
2016-04-26 22:55:27.122346500   at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
2016-04-26 22:55:27.122348500   at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
2016-04-26 22:55:27.122349500   at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
2016-04-26 22:55:27.122351500   at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
2016-04-26 22:55:27.122355500   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
2016-04-26 22:55:27.122357500   at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
2016-04-26 22:55:27.122359500   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
2016-04-26 22:55:27.122361500   at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
2016-04-26 22:55:27.122366500   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
2016-04-26 22:55:27.122368500   at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
2016-04-26 22:55:27.122370500   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
2016-04-26 22:55:27.122372500   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
2016-04-26 22:55:27.122376500   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
2016-04-26 22:55:27.122377500   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
2016-04-26 22:55:27.122379500   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
2016-04-26 22:55:27.122381500   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
2016-04-26 22:55:27.122385500   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
2016-04-26 22:55:27.122387500   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
2016-04-26 22:55:27.122388500   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
2016-04-26 22:55:27.122390500   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
2016-04-26 22:55:27.122396500   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
2016-04-26 22:55:27.122397500   at org.eclipse.jetty.server.Server.handle(Server.java:370)
2016-04-26 22:55:27.122399500   at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
2016-04-26 22:55:27.122400500   at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
2016-04-26 22:55:27.122410500   at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
2016-04-26 22:55:27.122412500   at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
2016-04-26 22:55:27.122414500   at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
2016-04-26 22:55:27.122415500   at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
2016-04-26 22:55:27.122420500   at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
2016-04-26 22:55:27.122422500   at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
2016-04-26 22:55:27.122424500   at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
2016-04-26 22:55:27.122425500   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
2016-04-26 22:55:27.122431500   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
2016-04-26 22:55:27.122433500   at java.lang.Thread.run(Thread.java:745)
2016-04-26 22:55:27.122434500 Caused by: java.lang.NullPointerException: sourceRepoHomepage must not be null.
2016-04-26 22:55:27.122436500   at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:204)
2016-04-26 22:55:27.122437500   at com.dabsquared.gitlabjenkins.cause.CauseData.<init>(CauseData.java:48)
2016-04-26 22:55:27.122442500   at com.dabsquared.gitlabjenkins.cause.CauseDataBuilder.build(CauseDataBuilder.java:324)
2016-04-26 22:55:27.122444500   at com.dabsquared.gitlabjenkins.trigger.handler.merge.MergeRequestHookTriggerHandlerImpl.retrieveCauseData(MergeRequestHookTriggerHandlerImpl.java:82)
2016-04-26 22:55:27.122445500   at com.dabsquared.gitlabjenkins.trigger.handler.merge.MergeRequestHookTriggerHandlerImpl.retrieveCauseData(MergeRequestHookTriggerHandlerImpl.java:26)
2016-04-26 22:55:27.122450500   at com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler.createActions(AbstractWebHookTriggerHandler.java:50)
2016-04-26 22:55:27.122452500   at com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler.handle(AbstractWebHookTriggerHandler.java:38)
2016-04-26 22:55:27.122459500   at com.dabsquared.gitlabjenkins.trigger.handler.merge.MergeRequestHookTriggerHandlerImpl.handle(MergeRequestHookTriggerHandlerImpl.java:39)
2016-04-26 22:55:27.122461500   at com.dabsquared.gitlabjenkins.trigger.handler.merge.MergeRequestHookTriggerHandlerImpl.handle(MergeRequestHookTriggerHandlerImpl.java:26)
2016-04-26 22:55:27.122463500   at com.dabsquared.gitlabjenkins.GitLabPushTrigger.onPost(GitLabPushTrigger.java:186)
2016-04-26 22:55:27.122467500   at com.dabsquared.gitlabjenkins.webhook.build.MergeRequestBuildAction$1.run(MergeRequestBuildAction.java:37)
2016-04-26 22:55:27.122468500   at hudson.security.ACL.impersonate(ACL.java:198)
2016-04-26 22:55:27.122470500   at com.dabsquared.gitlabjenkins.webhook.build.MergeRequestBuildAction.execute(MergeRequestBuildAction.java:33)
2016-04-26 22:55:27.122471500   at com.dabsquared.gitlabjenkins.webhook.GitLabWebHook.getDynamic(GitLabWebHook.java:44)
2016-04-26 22:55:27.122475500   ... 75 more

**Comment by coder-hugo** [comment]
@omehegan this is strange cause I always tested my changes with GitLab 7.14.3 and the latest GitLab 8.x. You could add a logger for "com.dabsquared.gitlabjenkins" in your Jenkins. There you should see some more details and also the incoming request.

**Comment by omehegan** [comment]
Homepage is definitely not present in the JSON when I open a merge request. Here's the JSON from a merge request: https://gist.github.com/omehegan/57e16c230e15d050ad26ce061031f8e3 

Turns out that pushes work OK, the webhook I was using initially was only set up for MR.

**Comment by omehegan** [comment]
@coder-hugo https://github.com/jenkinsci/gitlab-plugin/commit/f737542f8ae6b04c58d567ccc671eb32e391f565 resolves this issue for me, although it may not be the best way to do so.
