### ISSUE TITLE
Handle GitLab API deprecations >= 8.5.0

### ISSUE THREAD

**Issue by xasx** [jenkinsci/gitlab-plugin#275]
There are some Merge Request related API changes in recent GitLab versions which are not reflected in `GitLabApi`.

See https://github.com/gitlabhq/gitlabhq/blob/master/CHANGELOG#L385

Essentially, it is the MR comment API that is now a 'note' API.
Furthermore it is `merge_requests` now (instead of former singular).

**Comment by xasx** [comment]
Currently getting 

```
Failed to add message to merge request.
```

Furthermore, no build information is attached or updated.

**Comment by mattiasb** [comment]
> Furthermore, no build information is attached or updated.

Build information in the form of notes/comments added to the MR? Does the [Build Status](https://cloud.githubusercontent.com/assets/1341313/14884979/e4267510-0d48-11e6-8f8e-c73d18438371.png) thing still work for you? 
I'm asking since we're considering upgrading GitLab at my work soon. :)

**Comment by coder-hugo** [comment]
Can you add a Logger for "com.dabsquared.gitlabjenkins" to your Jenkins and paste its output here.
According:

> Furthermore, no build information is attached or updated.

Can you just check if your Jenkins job has got the Post-Build step "Publish build status to GitLab commit (GitLab 8.1+ required)".

**Comment by xasx** [comment]
> Build information in the form of notes/comments added to the MR? Does the Build Status thing still work for you? 

Neither works.

> Can you just check if your Jenkins job has got the Post-Build step "Publish build status to GitLab commit (GitLab 8.1+ required)".

Wasn't aware of that, but totally makes sense since it is not related to any API change.
Will try and report back soon

**Comment by xasx** [comment]
Using the post-build action, I get this exception

```
Checking out Revision d519ad86345fcdbf54bd42e7184974dc94c045f3 (Core Middleware/minorCleanUPs, HEAD, origin/master)
ERROR: Processing failed due to a bug in the code. Please report this to jenkinsci-users@googlegroups.com
java.lang.NullPointerException
    at org.jboss.resteasy.util.ReadFromStream.readFromStream(ReadFromStream.java:30)
    at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.bufferEntity(ClientResponse.java:307)
    at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:48)
    at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104)
    at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64)
    at com.sun.proxy.$Proxy124.headCommit(Unknown Source)
    at com.dabsquared.gitlabjenkins.publisher.GitLabCommitStatusPublisher.existsCommit(GitLabCommitStatusPublisher.java:88)
    at com.dabsquared.gitlabjenkins.publisher.GitLabCommitStatusPublisher.updateCommitStatus(GitLabCommitStatusPublisher.java:76)
    at com.dabsquared.gitlabjenkins.publisher.GitLabCommitStatusPublisher.prebuild(GitLabCommitStatusPublisher.java:47)
    at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:837)
    at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:832)
    at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:664)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
    at hudson.model.Run.execute(Run.java:1738)
    at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:531)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
```

**Comment by xasx** [comment]
I can sucessfully

```
HEAD /api/v3/projects/61/repository/commits/d519ad86345fcdbf54bd42e7184974dc94c045f3
```

However, the question is which `projectId` you pass.

**Comment by coder-hugo** [comment]
You should see the id if you configure a Logger in your Jenkins for "com.dabsquared.gitlabjenkins" at least for FINEST. This prints several information about the invoked requests.

**Comment by xasx** [comment]
Seems some placeholder isn't correctly substituted. The request is done against:

`https://mygitlabhost/api/v3/projects/$%7BgitlabSourceRepoURL%7D/repository/commits/d519ad86345fcdbf54bd42e7184974dc94c045f3`

**Comment by xasx** [comment]
Regarding the commenting issue:

`https://mygitlabhost/api/v3/projects/150/merge_request/177/comments?note=%3A%2B1%3A+Jenkins+Build+Failed%0A%0AResults+available+at%3A+%5BJenkins+%5BBlablabla%2F177%2F%29` leads to 404 (maybe due to the API change as noted above).
