### ISSUE TITLE
Build the merge, not only the source branch

### ISSUE THREAD

**Issue by angely-dev** [jenkinsci/gitlab-plugin#286]
Hi,

This plugin works well but is it normal that only the source branch (e.g., a feature) is built and not the merge with the target branch (e.g., develop) ? Maybe a dumb question but that seems surprising to me. In Atlassian Bamboo, it is possible to do both (thanks to a checkbox) : build the source branch and build the merge.

Besides, this leads to an inconsistency in the GitLab Merge Request page in case of merge conflicts: GitLab warns the user with a message but Jenkins says that the build is successful (see image below).

![gitlab_mr](https://cloud.githubusercontent.com/assets/4362224/14983217/1616d596-113c-11e6-82eb-e91d1e548657.png)

Thanks for your contribution.

**Comment by demaniak** [comment]
Hi @champidead  - did you set up your SCM section as described in the [readme](https://github.com/jenkinsci/gitlab-plugin#jenkins-job-configuration)?

Specifically the _Additional Behaviours_ section is important.

This caught me out the first time.

**Comment by angely-dev** [comment]
Hi @demaniak, thanks for your answer. I set up the SCM as described and the merge seems to work. However, an exception is now triggered: 

```
Merging Revision 73bf4ee77234767a99467a60af19d700db98ad94 (origin/feature/sth) to origin/develop, UserMergeOptions{mergeRemote='origin', mergeTarget='${gitlabTargetBranch}', mergeStrategy='default', fastForwardMode='--ff'}
 > git rev-parse origin/develop^{commit} # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f origin/develop
 > git merge --ff 73bf4ee77234767a99467a60af19d700db98ad94 # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 73bf4ee77234767a99467a60af19d700db98ad94
FATAL: null
java.lang.NullPointerException
    at hudson.plugins.git.extensions.impl.PreBuildMerge.decorateRevisionToBuild(PreBuildMerge.java:88)
    at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:1009)
    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1098)
    at hudson.scm.SCM.checkout(SCM.java:485)
    at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
    at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
    at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
    at hudson.model.Run.execute(Run.java:1738)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Finished: FAILURE
```

I tried to follow #184 but no success.

**Comment by demaniak** [comment]
Hm @champidead ,  at the top you mentioned Gitlab reporting merge conflicts - have those been resolved?

**Comment by angely-dev** [comment]
This is partially resolved since the merge is still not really working in Jenkins. But I can close this issue and open another one related to the NPE. Thanks @demaniak.

**Comment by demaniak** [comment]
@champidead good luck!
