### ISSUE TITLE
Error fetching remote repo when there are spaces in GitLab repo name

### ISSUE THREAD

**Issue by tnucera** [jenkinsci/gitlab-plugin#292]
Hello,

Jenkins 2.1
Git plugin 2.4.4
GitLab plugin 1.2.1

```
> git -c core.askpass=true fetch --tags --progress git@gitlab.tld.fr:agonze/portail_fournisseur.git +refs/heads/*:refs/remotes/Portail Fournisseur/*
ERROR: Error fetching remote repo 'Portail Fournisseur'
hudson.plugins.git.GitException: Failed to fetch from git@gitlab.tld.fr:agonze/portail_fournisseur.git
    at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:810)
    at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1066)
    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1097)
    at hudson.scm.SCM.checkout(SCM.java:485)
    at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
    at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
    at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
    at hudson.model.Run.execute(Run.java:1738)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Caused by: hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress git@gitlab.tld.fr:agonze/portail_fournisseur.git +refs/heads/*:refs/remotes/Portail Fournisseur/*" returned status code 128:
stdout: 
stderr: fatal: Invalid refspec '+refs/heads/*:refs/remotes/Portail Fournisseur/*'

    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1719)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1463)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:63)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:314)
    at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:152)
    at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:145)
    at hudson.remoting.UserRequest.perform(UserRequest.java:120)
    at hudson.remoting.UserRequest.perform(UserRequest.java:48)
    at hudson.remoting.Request$2.run(Request.java:332)
    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at ......remote call to SI-REC(Native Method)
    at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
    at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
    at hudson.remoting.Channel.call(Channel.java:781)
    at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:145)
    at sun.reflect.GeneratedMethodAccessor243.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:131)
    at com.sun.proxy.$Proxy88.execute(Unknown Source)
    at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:808)
    ... 11 more
ERROR: null
```

Log

```
  "repository" : {
    "name" : "Portail Fournisseur",
    "url" : "git@gitlab.tld.fr:carma/portail_fournisseur.git",
    "description" : "",
    "homepage" : "https://gitlab.tld.fr/carma/portail_fournisseur"
  },
  "source" : {
      "name" : "Portail Fournisseur",
      "ssh_url" : "git@gitlab.tld.fr:agonze/portail_fournisseur.git",
      "http_url" : "https://gitlab.tld.fr/agonze/portail_fournisseur.git",
      "web_url" : "https://gitlab.tld.fr/agonze/portail_fournisseur",
      "namespace" : "agonze",
      "visibility_level" : 10
    },
    "target" : {
      "name" : "Portail Fournisseur",
      "ssh_url" : "git@gitlab.tld.fr:carma/portail_fournisseur.git",
      "http_url" : "https://gitlab.tld.fr/carma/portail_fournisseur.git",
      "web_url" : "https://gitlab.tld.fr/carma/portail_fournisseur",
      "namespace" : "CARMA",
      "visibility_level" : 10
    },
```

The Jenkins conf is the same as explained in the plugin doc.

**Comment by xasx** [comment]
Does not seem to be related to GitLab plugin in particular.

It is rather something with the Git plugin itself, check: https://github.com/jenkinsci/git-plugin

**Comment by omehegan** [comment]
Correct, the GitLab plugin only triggers the job, it's up to the git plugin to do the clone. Are you sure your config is correct? It looks like there should be an _ instead of the space.

**Comment by tnucera** [comment]
@omehegan 

When I remove the space in the project name on GitLab, it works :

![capture d ecran 2016-05-04 a 17 40 45](https://cloud.githubusercontent.com/assets/10210667/15019707/634d8d3a-121f-11e6-9535-aa02154dbda7.png)

KO ->

```
  "repository" : {
    "name" : "Portail Fournisseur",
```

OK ->

```
  "repository" : {
    "name" : "PortailFournisseur",
```

It's an issue of the plugin no ??

Otherwise, you should specify in the doc that the project name in GitLab should not contain spaces.

**Comment by omehegan** [comment]
@tnucera it's an issue with the Git plugin, not the GitLab plugin. The Git plugin is unable to check out a repo whose refspec contains a space. I don't know whether that's really a bug with that plugin, or if GitLab should not let you create such project names. Regardless, it's not an issue with our code.

**Comment by xasx** [comment]
@tnucera The question is why is the refspec name apparently derived from the Project name that is set in GitLab, right?
