### ISSUE TITLE
Create trigger fail in Jenkins2.5

### ISSUE THREAD

**Issue by amsz** [jenkinsci/gitlab-plugin#328]
- GitLab plugin 1.2.2
- GitLab version 8.7.0
- Jenkins version 2.5

When save configure after checked 'Build when a change is pushed to GitLab': 

```
javax.servlet.ServletException: java.lang.Error: Failed to instantiate class com.dabsquared.gitlabjenkins.GitLabPushTrigger from {"triggerOnMergeRequest":true,"triggerOnPush":true,"triggerOpenMergeRequestOnPush":"","ciSkip":true,"setBuildDescription":true,"addNoteOnMergeRequest":true,"addVoteOnMergeRequest":true,"acceptMergeRequestOnSuccess":false,"branchFilterType":"All","includeBranchesSpec":"","excludeBranchesSpec":"","targetBranchRegex":""}
    at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:796)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
    at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:233)
    at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
    at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
    at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
    at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
    at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
    at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:80)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
    at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
    at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
    at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
    at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
    at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
    at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1160)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
    at org.eclipse.jetty.server.Server.handle(Server.java:518)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Error: Failed to instantiate class com.dabsquared.gitlabjenkins.GitLabPushTrigger from {"triggerOnMergeRequest":true,"triggerOnPush":true,"triggerOpenMergeRequestOnPush":"","ciSkip":true,"setBuildDescription":true,"addNoteOnMergeRequest":true,"addVoteOnMergeRequest":true,"acceptMergeRequestOnSuccess":false,"branchFilterType":"All","includeBranchesSpec":"","excludeBranchesSpec":"","targetBranchRegex":""}
    at hudson.model.Descriptor.newInstance(Descriptor.java:598)
    at hudson.model.AbstractProject.buildDescribable(AbstractProject.java:1890)
    at hudson.model.AbstractProject.submit(AbstractProject.java:1868)
    at hudson.model.Project.submit(Project.java:230)
    at hudson.model.Job.doConfigSubmit(Job.java:1229)
    at hudson.model.AbstractProject.doConfigSubmit(AbstractProject.java:795)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:324)
    at org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:52)
    at org.kohsuke.stapler.PreInvokeInterceptedFunction.invoke(PreInvokeInterceptedFunction.java:26)
    at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:167)
    at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:100)
    at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:124)
    at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
    at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
    ... 63 more
Caused by: java.lang.IllegalArgumentException: Failed to instantiate class com.dabsquared.gitlabjenkins.GitLabPushTrigger from {"triggerOnMergeRequest":true,"triggerOnPush":true,"triggerOpenMergeRequestOnPush":"","ciSkip":true,"setBuildDescription":true,"addNoteOnMergeRequest":true,"addVoteOnMergeRequest":true,"acceptMergeRequestOnSuccess":false,"branchFilterType":"All","includeBranchesSpec":"","excludeBranchesSpec":"","targetBranchRegex":""}
    at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:676)
    at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:478)
    at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:474)
    at hudson.model.Descriptor.newInstance(Descriptor.java:590)
    ... 80 more
Caused by: java.lang.IllegalArgumentException: Failed to convert the triggerOpenMergeRequestOnPush parameter of the constructor public com.dabsquared.gitlabjenkins.GitLabPushTrigger(boolean,boolean,com.dabsquared.gitlabjenkins.trigger.TriggerOpenMergeRequest,boolean,boolean,boolean,boolean,boolean,boolean,com.dabsquared.gitlabjenkins.trigger.filter.BranchFilterType,java.lang.String,java.lang.String,java.lang.String)
    at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:773)
    at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:83)
    at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:674)
    ... 83 more
Caused by: java.lang.IllegalArgumentException: No enum constant com.dabsquared.gitlabjenkins.trigger.TriggerOpenMergeRequest.
    at java.lang.Enum.valueOf(Enum.java:238)
    at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:726)
    at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:478)
    at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:771)
    ... 85 more
```

**Comment by omehegan** [comment]
I just tried this with Jenkins 2.5 and the current version of the plugin, and could not replicate it. Can you give some more information about your job configuration? What type of job, what settings did you use, etc.

I tested in a totally clean install of Jenkins 2.5 because I'm still using 1.6 in test and production. Did you upgrade Jenkins or the plugin from an earlier version before you encountered this issue? Did it ever work?

**Comment by amsz** [comment]
I found reason: my web server proxy config error and can't request gitlab plugin data,  so 'Rebuild open Merge Requests' select is nothing in web interface, submit JSON data is `"triggerOpenMergeRequestOnPush": ""` and issue above exception.

Now it work well, thanks for you reply.

**Comment by lenis0012** [comment]
Im having this issue too
@amsz Could you explain how to resolve it :)

**Comment by amsz** [comment]
In my case, the nginx  is block some web requests like `http://xx.com/job/proj1/descriptorByName/com.dabsquared.gitlabjenkins.GitLabPushTrigger/fillTriggerOpenMergeRequestOnPushItems`, and submit the invalid JSON data to gitlab plugin when save project config.

I just direct access jenkins by host:port without nginx and fix it.
