### ISSUE TITLE
Timeout when "Add note with build status on merge requests" runs

### ISSUE THREAD

**Issue by AlbertoPeon** [jenkinsci/gitlab-plugin#342]
Hi,

In our workflow, a jenkins build is run every time a merge request is open, which gets merge automatically if the build success.

We want to display the status of the build in a comment in the merge request (either if it has succeed or not) and for that, we use the option 'Add note with build status on merge requests'.

The problem we see is that the message with the status is not always displayed, only sometimes. In the jenkins logs, we see a timeout matching the time frame of the merge requests.

```
May 31, 2016 1:22:12 PM hudson.model.listeners.RunListener report
WARNING: RunListener failed
javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request
    at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:287)
    at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:436)
    at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:102)
    at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64)
    at com.sun.proxy.$Proxy81.acceptMergeRequest(Unknown Source)
    at com.dabsquared.gitlabjenkins.listener.GitLabMergeRequestRunListener.acceptMergeRequestIfNecessary(GitLabMergeRequestRunListener.java:54)
    at com.dabsquared.gitlabjenkins.listener.GitLabMergeRequestRunListener.onCompleted(GitLabMergeRequestRunListener.java:36)
    at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
    at hudson.model.Run.execute(Run.java:1783)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Caused by: java.net.SocketTimeoutException: Read timed out
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
    at java.net.SocketInputStream.read(SocketInputStream.java:170)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
    at sun.security.ssl.InputRecord.read(InputRecord.java:503)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
    at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
    at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
    at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:160)
    at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:84)
    at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:273)
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
    at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283)
    at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:251)
    at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:197)
    at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
    at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
    at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
    at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:283)
... 11 more
```

After taking a look at the code, I think this happens because the timeout of the GitlabClient is hardcoded to [10 seconds](https://github.com/jenkinsci/gitlab-plugin/blob/fb63a3376344b7d5e1192bedfcc3c6c1fa49e934/src/main/java/com/dabsquared/gitlabjenkins/gitlab/GitLabClientBuilder.java#L61) and it's not big enough for us (in most of the cases).

Could this value be increased or made configurable?

**Comment by coder-hugo** [comment]
This stacktrace displays a read timeout for the accept merge request method. Unfortunately this exception isn't caught which causes your described behavior that the note isn't added to the MR. So I think there are more issues than just the timeout.
1. we should change the order of the steps: first add the note, then accept the MR which should make more sense reading the history of a MR
2. catch all exceptions that can occur during the communication with GitLab not only a `WebApplicationException`
3. add the possibility to configure the timeouts per GitLab connection
