### ISSUE TITLE
gitlabCommitStatus: Gitlab in non-root location

### ISSUE THREAD

**Issue by schmitzhermes** [jenkinsci/gitlab-plugin#364]
### Context
- **Gitlab plugin version**: 1.2.3
- **Gitlab version**: 8.7.6
- **Jenkins version**: 2.3
### Logs & Traces

> SEVERE: Failed to update Gitlab commit status for project 'gitlab/group/project'
> javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
>     at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:209)
>     at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:50)
>     at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104)
>     at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64)
>     at com.sun.proxy.$Proxy103.getCommit(Unknown Source)
>     at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.existsCommit(CommitStatusUpdater.java:80)
>     at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.updateCommitStatus(CommitStatusUpdater.java:43)
>     at com.dabsquared.gitlabjenkins.workflow.GitLabCommitStatusStep$Execution$1.onSuccess(GitLabCommitStatusStep.java:48)
>     at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$SuccessAdapter.receive(CpsBodyExecution.java:303)
>     at com.cloudbees.groovy.cps.Outcome.resumeFrom(Outcome.java:73)
>     at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:146)
>     at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
>     at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:32)
>     at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:29)
>     at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
>     at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:29)
>     at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:164)
>     at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:276)
>     at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$000(CpsThreadGroup.java:78)
>     at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:185)
>     at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:183)
>     at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:47)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>     at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
>     at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
>     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at java.lang.Thread.run(Thread.java:745)
### Problem description

_Describe your problem in a meaningful way_:
I use the `gitlabCommitStatus { ... } pipeline feature. It tries to inform my Gitlab installation about the success of the commit, but it can't because my Gitlab does not run in a root-location. It does run under "http://myurl.com/gitlab/". 

As far as I could see the GitlabProjectId is implictily determined based on the remoteUrl. 
The `ProjectIdUtil`, however, does not take that into account whether gitlab runs in a root-location or not and just substrings from the first occurence of a slash until ".git" (see: https://github.com/jenkinsci/gitlab-plugin/blob/master/src/main/java/com/dabsquared/gitlabjenkins/util/ProjectIdUtil.java#L16-L21) 

Is there any chance to set the GitlabProjectId explicitly? If not, I'd be glad to submit a PR that improves the ProjectIdUtil in that way... As far as I know a Gitlab project can only have one group and one project; that makes changing the ProjectIdUtil pretty easy.

Thanks for your information...
Jan

**Comment by schmitzhermes** [comment]
That was pretty fast, thanks ;-)
