### ISSUE TITLE
Jenkins can't install plugin

### ISSUE THREAD

**Issue by ray65536** [jenkinsci/gitlab-plugin#366]
I'm not sure, that it's related to plugin itself - but it reproduced on two different version of _clean_ installation of Jenkins. 
I had tried openjdk7 and oracle java7, with no difference, on both systems.
### Context
- **Gitlab plugin version**: 1.2.4
- **Gitlab version**: no matter
- **Jenkins version**: 2.10 and 1.651.3 
### Logs & Traces

**Jenkins log:**

```
июн 26, 2016 9:00:11 PM hudson.model.UpdateCenter$DownloadJob run
INFO: Starting the installation of GitLab Plugin on behalf of eugene
июн 26, 2016 9:00:11 PM hudson.model.UpdateCenter$UpdateCenterConfiguration download
INFO: Downloading GitLab Plugin
июн 26, 2016 9:00:11 PM hudson.PluginManager dynamicLoad
INFO: Attempting to dynamic load /var/lib/jenkins/plugins/gitlab-plugin.jpi
июн 26, 2016 9:00:12 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started initialization
июн 26, 2016 9:00:12 PM jenkins.InitReactorRunner$1 onAttained
INFO: Listed all plugins
июн 26, 2016 9:00:12 PM jenkins.InitReactorRunner$1 onAttained
INFO: Prepared all plugins
июн 26, 2016 9:00:12 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started all plugins
июн 26, 2016 9:00:12 PM jenkins.InitReactorRunner$1 onAttained
INFO: Augmented all extensions
июн 26, 2016 9:00:12 PM jenkins.InitReactorRunner$1 onAttained
INFO: Loaded all jobs
июн 26, 2016 9:00:12 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed GitLabConnection.migrate
java.lang.Error: java.lang.reflect.InvocationTargetException
    at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
    at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
    at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
    at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
    at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
    ... 7 more
Caused by: java.lang.NoClassDefFoundError: org/jenkinsci/plugins/plaincredentials/impl/StringCredentialsImpl
    at com.dabsquared.gitlabjenkins.connection.GitLabConnection.migrate(GitLabConnection.java:83)
    ... 12 more
Caused by: java.lang.ClassNotFoundException: org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl
    at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1376)
    at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
    at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 13 more

июн 26, 2016 9:00:12 PM hudson.model.UpdateCenter$DownloadJob run
SEVERE: Failed to install GitLab Plugin
java.io.IOException: Failed to dynamically deploy this plugin
    at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1867)
    at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1624)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:110)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Failed to initialize gitlab-plugin plugin
    at hudson.PluginManager.dynamicLoad(PluginManager.java:849)
    at hudson.PluginManager.dynamicLoad(PluginManager.java:775)
    at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1863)
    ... 5 more
Caused by: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
    at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:269)
    at jenkins.InitReactorRunner.run(InitReactorRunner.java:45)
    at hudson.PluginManager.dynamicLoad(PluginManager.java:847)
    ... 7 more
Caused by: java.lang.Error: java.lang.reflect.InvocationTargetException
    at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
    at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
    at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
    at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
    at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
    ... 7 more
Caused by: java.lang.NoClassDefFoundError: org/jenkinsci/plugins/plaincredentials/impl/StringCredentialsImpl
    at com.dabsq
```
### Problem description

Can't install plugin. Jenkins failed to install it, and failed to start, if jenkins/plugins/gitlab-plugin.jpi exists.

**Comment by zhmg23** [comment]
Recommended in China：
https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/update-center.json
