### ISSUE TITLE
Generated Jenkins job XML is missing Gitlab connection property

### ISSUE THREAD

**Issue by g-dx** [jenkinsci/gitlab-plugin#377]
### Context
- **Gitlab plugin version**: 1.2.5
- **Gitlab version**: 8.7.5
- **Jenkins version**: 1.651.3
### Logs & Traces

_Please include any relevant log that could serve to better understand the source of your issue_

```
Hook execution failed: <!DOCTYPE html> Jenkins [Jenkins]var isRunAsTest=false; var rootURL="/jenkins"; var resURL="/jenkins/static/b954a68c";crumb.init("", "");var Q=jQuery.noConflict()Skip to content log in createSearchBox("/jenkins/search/");Jenkins Jenkins project Bug tracker Mailing Lists Twitter: @jenkinsci Oops!A problem occurred while processing the request. Please check our bug tracker to see if a similar problem has already been reported. If it is already reported, please vote and put a comment on it to let us gauge the impact of the problem. If you think this is a new issue, please file a new issue. When you file an issue, make sure to add the entire stack trace, along with the version of Jenkins and relevant plugins. The users list might be also useful in understanding what has happened.Stack trace

javax.servlet.ServletException: java.lang.NullPointerException at 
org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:796) at 
org.kohsuke.stapler.Stapler.invoke(Stapler.java:876) at 
org.kohsuke.stapler.MetaClass$11.dispatch(MetaClass.java:380) at 
org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746) at 
org.kohsuke.stapler.Stapler.invoke(Stapler.java:876) at 
org.kohsuke.stapler.Stapler.invoke(Stapler.java:649) at 
org.kohsuke.stapler.Stapler.service(Stapler.java:238) at 
javax.servlet.http.HttpServlet.service(HttpServlet.java:848) at 
org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686) at 
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494) at 
hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135) at 
com.smartcodeltd.jenkinsci.plugin.assetbundler.filters.LessCSS.doFilter(LessCSS.java:47) at 
hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132) at 
hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:59) at 
hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132) at 
hudson.plugins.audit_trail.AuditTrailFilter.doFilter(AuditTrailFilter.java:95) at 
hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132) at 
hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126) at 
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482) at 
hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49) at 
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482) at 
hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84) at 
hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51) at 
hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87) at 
jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117) at 
hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87) at 
org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessing
Filter.java:125) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87) at 
org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:135) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87) at 
org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271) at 
hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87) at 
jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93) at 
hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87) at 
org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249) at 
hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87) at 
hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76) at 
hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171) at 
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482) at 
org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49) at 
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482) at 
hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81) at 
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482) at 
org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30) at 
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474) at 
org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499) at 
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) at 
org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533) at 
org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) at 
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086) at 
org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428) at 
org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) at 
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020) at 
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) at 
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) at 
org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:68) at 
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) at 
org.eclipse.jetty.server.Server.handle(Server.java:370) at 
org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489) at 
org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960) at 
org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.jav
a:1021) at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865) at 
org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) at 
org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) at 
org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668) at 
org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52) at 
winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77) at 
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at 
java.lang.Thread.run(Thread.java:745) 
Caused by: java.lang.NullPointerException at 
com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler.setCommitStatusPendingIfNecessary(AbstractWebHookTriggerHandler.java:62) at 
com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler.handle(AbstractWebHookTriggerHandler.java:47) at 
com.dabsquared.gitlabjenkins.trigger.handler.push.PushHookTriggerHandlerImpl.handle(PushHookTriggerHandlerImpl.java:28) at 
com.dabsquared.gitlabjenkins.trigger.handler.push.PushHookTriggerHandlerImpl.handle(PushHookTriggerHandlerImpl.java:21) at 
com.dabsquared.gitlabjenkins.trigger.handler.push.PushHookTriggerHandlerList.handle(PushHookTriggerHandlerList.java:23) at 
com.dabsquared.gitlabjenkins.trigger.handler.push.PushHookTriggerHandlerList.handle(PushHookTriggerHandlerList.java:12) at 
com.dabsquared.gitlabjenkins.GitLabPushTrigger.onPost(GitLabPushTrigger.java:206) at 
com.dabsquared.gitlabjenkins.webhook.build.PushBuildAction$1.run(PushBuildAction.java:65) at 
hudson.security.ACL.impersonate(ACL.java:198) at 
com.dabsquared.gitlabjenkins.webhook.build.PushBuildAction.execute(PushBuildAction.java:61) at 
com.dabsquared.gitlabjenkins.webhook.build.BuildWebHookAction.execute(BuildWebHookAction.java:15) at 
com.dabsquared.gitlabjenkins.webhook.GitLabWebHook.getDynamic(GitLabWebHook.java:44) at 
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at 
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at 
java.lang.reflect.Method.invoke(Method.java:497) at 
org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:320) at 
org.kohsuke.stapler.Function.bindAndInvoke(Function.java:163) at 
org.kohsuke.stapler.MetaClass$11.dispatch(MetaClass.java:378) at 
org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746) ... 70 more Page generated: Jul 7, 2016 11:50:05 AM BSTREST APIJenkins ver. 1.651.3 Help us localize this page var footer = document.getElementById('l10n-footer'); var f = document.getElementById('footer'); f.insertBefore(footer,f.firstChild); footer.style.display="block"; var translation={}; translation.bundles = "G1GOekHSwS+rru6VzsRAWGCGvNhuXKTS8LGp2YIfZthNmAr4qDNXb1PNTZgvzqG+AyjwP3RWSSap9FwRfG4sacp4MCHWSIJiXAGPRb/aZaXIEGXHVGIOchMv+NUo1I7FthftYxds6upljVHoRJsVoHR0LsgMZHDWNQQUmyAYfR4C/gbkGS/kGd06j7Ffyeszu8AEqefakEAx1/ySfQgw3o329X4WvVL6Zc2n1d4mUPopggs9mQUvabvhqVFoC9EyrFnab0zQriQDzjFXQGY+qm/r1hX8w9bxdLxM+TcEKu6n749YYhsDssA66Y3j3cnFHU3ucgnVilHWFBtDo/C+ltP1MSvCC0u7qNEP6Sb4mBP9HJWAgp3vI35edT1cK5nsHo8UIF++qU1B1Y37XlgG87QyeA6T8jV5haFic7V8AiVhfcNFn9DuxsycOzY74K3EoSoX0XiVCScegLImR/7UjU59ks1EZIWxaa/4ex2aSbQ="; translation.detectedLocale = ""; function showTranslationDialog() { if(!translation.launchDialog) loadScript("/jenkins/static/b954a68c/plugin/translation/dialog.js"); else translation.launchDialog(); return false; }
```
### Problem description

_Describe your problem in a meaningful way_:
- what were you doing (simple push, merge request, MR with fork, ...)
  - Attempting to test a gitlab -> jenkins webhook.
- what was expected
  - The hook execution would be successful.
- what occured finally
  - The hook failed with the stacktrace above.
### Further Information

 We use the Jenkins DSL to generate our job definitions. I found that the generated XML for the job we were triggering from Gitlab was missing the following XML block. This was the root cause of the stacktrace above:

```
<com.dabsquared.gitlabjenkins.connection.GitLabConnectionProperty plugin="gitlab-plugin@1.2.5">
    <gitLabConnection>...our jenkins URL...</gitLabConnection>
</com.dabsquared.gitlabjenkins.connection.GitLabConnectionProperty>
```

The fix for this issue was to add the following Jenkins DSL code to our job definition:

```
properties {
   gitLabConnectionProperty {
      gitLabConnection "<...our Jenkins URL...>"
   }
}
```

This then fixed the webhook test execution and everything now works correctly.

However it is my understanding that because we have defined these details at the _global level_ we should _not_ have to repeat this configuration at the individual job level. Is this correct? 

If so, there appears to be a bug with adding default configuration XML to newly created jobs?

**Comment by coder-hugo** [comment]
As you are able to configure multiple GitLab connections at the global level you have to select one of them for your job. This is the reason why you have to set the gitLabConnectionProperty for every job.

**Comment by g-dx** [comment]
Is there a way to refer to the connection by ID rather than duplicating our Gitlab URL in multiple places?

The thing that confused me most when trying to debug this was that if I edited my Jenkins job and then saved it again _without changing anything_ the necessary XML block for the gitlab connection property would be added for me.

That is why I assumed it was a bug.

**Comment by coder-hugo** [comment]
A gitlabConnection is identified by its name not by the URL. You can use any name you want at the global configuration for a GitLabConnection and use this also in your job definition.

**Comment by g-dx** [comment]
Ah, I didn't realise that. Well, that's all my questions answered.

Thanks again for your timely response and all the hard work you and others are doing to facilitate Gitlab <-> Jenkins integration. It really is great!

**Comment by Str8AWay** [comment]
Do you have an example of some dsl referencing a globally defined GitLabConnection?

**Comment by floriantraber** [comment]
@Str8AWay 
```
job {
      properties {
            gitLabConnection {
                gitLabConnection('My Gitlab Connection')
            }
        }
}  
```

**Comment by andrcuns** [comment]
Can someone explain how the snippet above could work? From what I could tell, job-dsl plugin doesn't have gitlabConnection in properties context.
P.S. Never mind, I realised that gitlabConnection is automatically generated which means it is not available in online API viewer or IDE autocompletion which got me confused a little bit.
