### ISSUE TITLE
Push/MR posted: no environment variables are set

### ISSUE THREAD

**Issue by DoCode** [jenkinsci/gitlab-plugin#380]
## Issue

Jenkins master(Linux) -> Jenkins slave(Windows): No git-(*) environment variables are set.
### Context
- **GitLab plugin version**: 1.3.0
- **GitLab version**: 8.9.6-ee
- **Jenkins version**: 2.13
### Problem description

When a push/MR is posted to Jenkins no environment variables set.

**Comment by coder-hugo** [comment]
Could you provide some more information: job configuration, logs, ...

**Comment by atcol** [comment]
Here's an example problem log:

```
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url http://blah/project.git # timeout=10
Fetching upstream changes from http://blah/project.git
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress http://blah/project.git +refs/merge-requests/*/head:refs/remotes/origin/merge-requests/*
 > git rev-parse refs/remotes/origin/${gitlabSourceBranch}^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/${gitlabSourceBranch}^{commit} # timeout=10
 > git rev-parse origin/${gitlabSourceBranch}^{commit} # timeout=10
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job
```

**Comment by DoCode** [comment]
# Console Output

```
Branch indexing
[EnvInject] - Loading node environment variables.
Building remotely on XXXXXX in workspace D:\jenkins\workspace\XXXXXX\ci\header-versioning-scheme
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://XXXXXX.git # timeout=10
Fetching upstream changes from https://XXXXXX.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials buildbot@XXXXXX
 > git fetch --tags --progress https://XXXXXX.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse "origin/header-versioning-scheme^{commit}" # timeout=10
Merging Revision 0d18ce9e2b17a6ea1b63de706ca7991cc7bfadcd (origin/header-versioning-scheme) to origin/${gitlabTargetBranch}, UserMergeOptions{mergeRemote='origin', mergeTarget='${gitlabTargetBranch}', mergeStrategy='default', fastForwardMode='--ff'}
 > git rev-parse "origin/${gitlabTargetBranch}^{commit}" # timeout=10
FATAL: Command "git rev-parse "origin/${gitlabTargetBranch}^{commit}"" returned status code 128:
stdout: origin/${gitlabTargetBranch}^{commit}

stderr: fatal: ambiguous argument 'origin/${gitlabTargetBranch}^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

hudson.plugins.git.GitException: Command "git rev-parse "origin/${gitlabTargetBranch}^{commit}"" returned status code 128:
stdout: origin/${gitlabTargetBranch}^{commit}

stderr: fatal: ambiguous argument 'origin/${gitlabTargetBranch}^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1739)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1712)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1708)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1378)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1390)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.revParse(CliGitAPIImpl.java:679)
    at hudson.plugins.git.GitAPI.revParse(GitAPI.java:316)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:884)
    at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:859)
    at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:818)
    at hudson.remoting.UserRequest.perform(UserRequest.java:153)
    at hudson.remoting.UserRequest.perform(UserRequest.java:50)
    at hudson.remoting.Request$2.run(Request.java:332)
    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at hudson.remoting.Engine$1$1.run(Engine.java:85)
    at java.lang.Thread.run(Unknown Source)
    at ......remote call to XXXXXX(Native Method)
    at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
    at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
    at hudson.remoting.Channel.call(Channel.java:781)
    at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:249)
    at com.sun.proxy.$Proxy80.revParse(Unknown Source)
    at org.jenkinsci.plugins.gitclient.RemoteGitImpl.revParse(RemoteGitImpl.java:551)
    at hudson.plugins.git.extensions.impl.PreBuildMerge.decorateRevisionToBuild(PreBuildMerge.java:64)
    at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:994)
    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1083)
    at hudson.scm.SCM.checkout(SCM.java:495)
    at hudson.model.AbstractProject.checkout(AbstractProject.java:1270)
    at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
    at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
    at hudson.model.Run.execute(Run.java:1720)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:404)
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level D:\jenkins\workspace\XXXXXX\ci\header-versioning-scheme\_build\testresults to /var/lib/jenkins/jobs/XXXXXX/jobs/ci/branches/header-versioning-scheme/builds/2/htmlreports/XXXXXX
Sending e-mails to: XXXXXX.com
Finished: FAILURE
```

# Environment Variables

```
ALLUSERSPROFILE C:\ProgramData
APPDATA C:\Users\jenkinsbuildservice\AppData\Roaming
ARTIFACTS_FOLDER    D:\artifacts\
BASE    D:\jenkins
BUILD_CAUSE BRANCHINDEXINGCAUSE
BUILD_CAUSE_BRANCHINDEXINGCAUSE true
BUILD_DISPLAY_NAME  #2
BUILD_ID    2
BUILD_NUMBER    2
BUILD_TAG   jenkins-XXXXXX-ci-header-versioning-scheme-2
BUILD_URL   https://XXXXXX.com/job/XXXXXX/job/ci/job/header-versioning-scheme/2/
CodeContractsInstallDir C:\Program Files (x86)\Microsoft\Contracts\
CommonProgramFiles  C:\Program Files\Common Files
CommonProgramFiles(x86) C:\Program Files (x86)\Common Files
CommonProgramW6432  C:\Program Files\Common Files
COMPUTERNAME    XXXXXX
ComSpec C:\Windows\system32\cmd.exe
DeploymentShare D:\deploymentshare\
EAZFUSCATOR_NET_HOME    C:\Program Files (x86)\Eazfuscator.NET
EXECUTOR_NUMBER 1
FP_NO_HOST_CHECK    NO
GIT_LFS_PATH    C:\Program Files\Git LFS
XXXXXX_CLAMAV_SERVICE   D:\apps\XXXXXX-clamav-service
HUDSON_HOME /var/lib/jenkins
HUDSON_SERVER_COOKIE    d4ee06a2090681d8
HUDSON_URL  https://XXXXXX.com/
JAVA_HOME   C:\Program Files\Java\jdk1.8.0_66
JENKINS_HOME    /var/lib/jenkins
JENKINS_SERVER_COOKIE   d4ee06a2090681d8
JENKINS_URL https://XXXXXX.com/
JOB_BASE_NAME   header-versioning-scheme
JOB_NAME    XXXXXX/ci/header-versioning-scheme
JOB_URL https://XXXXXX.com/job/XXXXXX/job/ci/job/header-versioning-scheme/
LOCALAPPDATA    C:\Users\jenkinsbuildservice\AppData\Local
NODE_LABELS XXXXXX
NODE_NAME   XXXXXX
NUMBER_OF_PROCESSORS    4
OS  Windows_NT
Path    C:\Program Files (x86)\Eazfuscator.NET;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Users\Administrator\.dnx\bin;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin;C:\Program Files\Java\jdk1.8.0_66\bin;C:\Program Files\Git LFS;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\TortoiseHg\;C:\Program Files (x86)\nodejs\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\dotnet\
PATHEXT .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE  AMD64
PROCESSOR_IDENTIFIER    Intel64 Family 6 Model 44 Stepping 2, GenuineIntel
PROCESSOR_LEVEL 6
PROCESSOR_REVISION  2c02
ProgramData C:\ProgramData
ProgramFiles    C:\Program Files
ProgramFiles(x86)   C:\Program Files (x86)
ProgramW6432    C:\Program Files
PSModulePath    C:\Windows\system32\WindowsPowerShell\v1.0\Modules\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\;C:\Program Files\WindowsPowerShell\Modules\;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement\;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\Storage\
PUBLIC  C:\Users\Public
ROOT_BUILD_CAUSE    BRANCHINDEXINGCAUSE
ROOT_BUILD_CAUSE_BRANCHINDEXINGCAUSE    true
SERVICE_ID  jenkinsslave-D__jenkins
SystemDrive C:
SystemRoot  C:\Windows
TEMP    C:\Users\JENKIN~1\AppData\Local\Temp
TMP C:\Users\JENKIN~1\AppData\Local\Temp
USERDOMAIN  XXXXXX
USERNAME    jenkinsbuildservice
USERPROFILE C:\Users\jenkinsbuildservice
VcsPassword XXXXXX
VcsUsername buildbot
VS110COMNTOOLS  C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\
VS120COMNTOOLS  C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\
VS140COMNTOOLS  C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
VSSDK140Install C:\Program Files (x86)\Microsoft Visual Studio 14.0\VSSDK\
windir  C:\Windows
WINSW_EXECUTABLE    D:\jenkins\jenkins-slave.exe
```

**Comment by coder-hugo** [comment]
@DoCode this information isn't very helpful. I asked for things like the job configuration (which job kind is used, how is the gitlab-plugin configured for this job, ...). Furthermore the Console Output of the build doesn't tells me anything about the things done by the gitlab-plugin. For this I need the [log output of the plugin](https://github.com/jenkinsci/gitlab-plugin#user-support)

**Comment by DoCode** [comment]
@coder-hugo OK, here the job config for the _freestyle multi branch project_: It lives under a folder in jenkins: 

```
<?xml version='1.0' encoding='UTF-8'?>
<freestyle-multi-branch-project plugin="multi-branch-project-plugin@0.5.1">
  <actions/>
  <description></description>
  <properties/>
  <views>
    <branch-list-view>
      <owner class="freestyle-multi-branch-project" reference="../../.."/>
      <name>All</name>
      <filterExecutors>false</filterExecutors>
      <filterQueue>false</filterQueue>
      <properties class="hudson.model.View$PropertyList"/>
      <jobNames>
        <comparator class="hudson.util.CaseInsensitiveComparator"/>
      </jobNames>
      <jobFilters/>
      <columns>
        <hudson.views.StatusColumn/>
        <hudson.views.WeatherColumn/>
        <hudson.views.JobColumn/>
        <hudson.views.LastSuccessColumn/>
        <hudson.views.LastFailureColumn/>
        <hudson.views.LastDurationColumn/>
        <hudson.views.BuildButtonColumn/>
        <org.jenkinsci.plugins.gitlablogo.GitlabLogoColumn plugin="gitlab-logo@1.0.1"/>
      </columns>
      <includeRegex>.*</includeRegex>
      <recurse>false</recurse>
    </branch-list-view>
  </views>
  <viewsTabBar class="hudson.views.DefaultViewsTabBar"/>
  <healthMetrics>
    <com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric plugin="cloudbees-folder@5.12"/>
  </healthMetrics>
  <icon class="com.cloudbees.hudson.plugins.folder.icons.StockFolderIcon" plugin="cloudbees-folder@5.12"/>
  <orphanedItemStrategy class="com.cloudbees.hudson.plugins.folder.computed.DefaultOrphanedItemStrategy" plugin="cloudbees-folder@5.12">
    <pruneDeadBranches>true</pruneDeadBranches>
    <daysToKeep>0</daysToKeep>
    <numToKeep>0</numToKeep>
  </orphanedItemStrategy>
  <triggers/>
  <sources class="jenkins.branch.MultiBranchProject$BranchSourceList" plugin="branch-api@1.10">
    <data>
      <jenkins.branch.BranchSource>
        <source class="jenkins.plugins.git.GitSCMSource" plugin="git@3.0.0-beta2">
          <id>223c7e7b-9a24-498a-877e-f246041bb734</id>
          <remote>https://XXXX.com/XXXX/XXXX.git</remote>
          <credentialsId>c2ed0433-8c19-482a-9082-3667bea5009c</credentialsId>
          <includes>*</includes>
          <excludes></excludes>
          <ignoreOnPushNotifications>false</ignoreOnPushNotifications>
          <extensions>
            <hudson.plugins.git.extensions.impl.PreBuildMerge>
              <options>
                <mergeRemote>origin</mergeRemote>
                <mergeTarget>${gitlabTargetBranch}</mergeTarget>
                <mergeStrategy>default</mergeStrategy>
                <fastForwardMode>FF</fastForwardMode>
              </options>
            </hudson.plugins.git.extensions.impl.PreBuildMerge>
          </extensions>
        </source>
        <strategy class="jenkins.branch.DefaultBranchPropertyStrategy">
          <properties class="empty-list"/>
        </strategy>
      </jenkins.branch.BranchSource>
    </data>
    <owner class="freestyle-multi-branch-project" reference="../.."/>
  </sources>
  <factory class="com.github.mjdetullio.jenkins.plugins.multibranch.FreeStyleBranchProjectFactory">
    <owner class="freestyle-multi-branch-project" reference="../.."/>
  </factory>
  <disabled>false</disabled>
  <disabledSubProjects/>
</freestyle-multi-branch-project>
```

Under the _template_ folder this config file exists:

```
<?xml version='1.0' encoding='UTF-8'?>
<project>
  <keepDependencies>false</keepDependencies>
  <properties>
    <com.dabsquared.gitlabjenkins.connection.GitLabConnectionProperty plugin="gitlab-plugin@1.3.0">
      <gitLabConnection>XXXX.com</gitLabConnection>
    </com.dabsquared.gitlabjenkins.connection.GitLabConnectionProperty>
    <org.jenkinsci.plugins.gitlablogo.GitlabLogoProperty plugin="gitlab-logo@1.0.1">
      <repositoryName></repositoryName>
    </org.jenkinsci.plugins.gitlablogo.GitlabLogoProperty>
  </properties>
  <scm class="hudson.scm.NullSCM"/>
  <assignedNode>XXXX</assignedNode>
  <canRoam>false</canRoam>
  <disabled>true</disabled>
  <blockBuildWhenDownstreamBuilding>false</blockBuildWhenDownstreamBuilding>
  <blockBuildWhenUpstreamBuilding>false</blockBuildWhenUpstreamBuilding>
  <triggers/>
  <concurrentBuild>false</concurrentBuild>
  <builders>
    <hudson.tasks.BatchFile>
      <command>CALL build.cmd -BuildParams &apos;ArtifactsFolder=&quot;%ARTIFACTS_FOLDER%%JOB_NAME%&quot;;BuildTriggerType=Ci;__SkipTest=true&apos; -BuildTarget Build</command>
    </hudson.tasks.BatchFile>
  </builders>
  <publishers>
    <htmlpublisher.HtmlPublisher plugin="htmlpublisher@1.11">
      <reportTargets>
        <htmlpublisher.HtmlPublisherTarget>
          <reportName>XXXX</reportName>
          <reportDir>_build\testresults</reportDir>
          <reportFiles>Index.html</reportFiles>
          <alwaysLinkToLastBuild>true</alwaysLinkToLastBuild>
          <keepAll>true</keepAll>
          <allowMissing>true</allowMissing>
        </htmlpublisher.HtmlPublisherTarget>
      </reportTargets>
    </htmlpublisher.HtmlPublisher>
    <hudson.tasks.Mailer plugin="mailer@1.17">
      <recipients>XXXX@XXXX.com</recipients>
      <dontNotifyEveryUnstableBuild>false</dontNotifyEveryUnstableBuild>
      <sendToIndividuals>true</sendToIndividuals>
    </hudson.tasks.Mailer>
  </publishers>
  <buildWrappers/>
</project>
```

And under a _branches_ folder this config:

```
<?xml version="1.0" encoding="UTF-8"?><project>
  <keepDependencies>false</keepDependencies>
  <properties>
    <com.dabsquared.gitlabjenkins.connection.GitLabConnectionProperty plugin="gitlab-plugin@1.3.0">
      <gitLabConnection>XXXX.com</gitLabConnection>
    </com.dabsquared.gitlabjenkins.connection.GitLabConnectionProperty>
    <org.jenkinsci.plugins.gitlablogo.GitlabLogoProperty plugin="gitlab-logo@1.0.1">
      <repositoryName/>
    </org.jenkinsci.plugins.gitlablogo.GitlabLogoProperty>
  </properties>
  <scm class="hudson.scm.NullSCM"/>
  <assignedNode>XXXX</assignedNode>
  <canRoam>false</canRoam>
  <disabled>true</disabled>
  <blockBuildWhenDownstreamBuilding>false</blockBuildWhenDownstreamBuilding>
  <blockBuildWhenUpstreamBuilding>false</blockBuildWhenUpstreamBuilding>
  <triggers/>
  <concurrentBuild>false</concurrentBuild>
  <builders>
    <hudson.tasks.BatchFile>
      <command>CALL build.cmd -BuildParams 'ArtifactsFolder="%ARTIFACTS_FOLDER%%JOB_NAME%";BuildTriggerType=Ci;__SkipTest=true' -BuildTarget Build</command>
    </hudson.tasks.BatchFile>
  </builders>
  <publishers>
    <htmlpublisher.HtmlPublisher plugin="htmlpublisher@1.11">
      <reportTargets>
        <htmlpublisher.HtmlPublisherTarget>
          <reportName>XXXX</reportName>
          <reportDir>_build\testresults</reportDir>
          <reportFiles>Index.html</reportFiles>
          <alwaysLinkToLastBuild>true</alwaysLinkToLastBuild>
          <keepAll>true</keepAll>
          <allowMissing>true</allowMissing>
        </htmlpublisher.HtmlPublisherTarget>
      </reportTargets>
    </htmlpublisher.HtmlPublisher>
    <hudson.tasks.Mailer plugin="mailer@1.17">
      <recipients>XXXX@XXXX.com</recipients>
      <dontNotifyEveryUnstableBuild>false</dontNotifyEveryUnstableBuild>
      <sendToIndividuals>true</sendToIndividuals>
    </hudson.tasks.Mailer>
  </publishers>
  <buildWrappers/>
</project>
```

**Comment by coder-hugo** [comment]
@DoCode mutitbranch projects aren't fully supported by this plugin. Multibranch projects work similar to [multibranch pipelines](https://github.com/jenkinsci/gitlab-plugin#git-configuration-for-multibranch-pipelineworkflow-jobs). For such jobs the gitlab-plugin just notifies the "parent" project about changes. When such a project gets notified about changes it starts a branch indexing (fetch all remote branches and look for changes). If the branch indexing detects changes it schedules a build for this branch and there is no way for the gitlab-plugin to pass any additional information to these builds.

**Comment by DoCode** [comment]
@coder-hugo, thanks for your support.
