### ISSUE TITLE
Jenkins does not started execution build on the "Tag Push Events" trigger from Gitlab. NPE error

### ISSUE THREAD

**Issue by asn80** [jenkinsci/gitlab-plugin#405]
### Context
- **Gitlab plugin version**: 1.1.32
- **Gitlab version**: 7.0.0
- **Jenkins version**: 1.650
### Problem description

Web hooks from Gitlab does not run triggering "Tag Push Event" build on Jenkins.

Our configuration.
GitLab settings:
Service / GitLab CI:
enabled "Active"
Token ="erwerwedsfsd"
Project Url =http://our-jenkins-server/project/distrbuild

Web Hook configuration:
URL = http://our-jenkins-server/project/distrbuild
Trigger = "Tag push events"

Jenkins configuration:
In Source Code Management from Gitlab:
In the Advanced settings, set its Name to origin and its refspec to +refs/heads/_:refs/remotes/origin/_ +refs/merge-requests/_/head:refs/remotes/origin/merge-requests/_ +refs/tags/_:refs/remotes/origin/tags/_
Branch specifier: origin/${gitlabSourceBranch}

Build triggers/
enabled - "Build when a change is pushed to GitLab. GitLab CI Service URL: http://our-jenkins-server/project/distrbuild"
enabled - "Build on Push Events"
Аccept merge request on success selected "Allow all branches to trigger this job"
- what was expected
  Expected that the Jenkins perform build when a new tag is pushed on Gitlab
- what occured finally
  Jenkins not started execution build on the "Tag Push Events". We have an NPE error

_Jenkins system logs:_
Sep 02, 2016 12:54:06 AM INFO com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
WebHook called with url: 
Sep 02, 2016 12:54:06 AM INFO com.dabsquared.gitlabjenkins.GitLabPushTrigger onPost
distrbuild triggered for push.
Sep 02, 2016 12:54:06 AM INFO com.dabsquared.gitlabjenkins.GitLabPushTrigger createActions
GitLab Push Request from branch refs/tags/v0.0.45.
Sep 02, 2016 12:54:06 AM WARNING org.eclipse.jetty.util.log.JavaUtilLog warn
Error while serving http://our-jenkins-server/project/distrbuild
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
    at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
    at org.kohsuke.stapler.MetaClass$13.dispatch(MetaClass.java:409)
    at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
    at org.kohsuke.stapler.MetaClass$13.dispatch(MetaClass.java:411)
    at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
    at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
    at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
    at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:123)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
    at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
    at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
    at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
    at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
    at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
    at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:370)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
    at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
    at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at com.dabsquared.gitlabjenkins.GitLabPushTrigger.createActions(GitLabPushTrigger.java:281)
    at com.dabsquared.gitlabjenkins.GitLabPushTrigger.onPost(GitLabPushTrigger.java:238)
    at com.dabsquared.gitlabjenkins.GitLabWebHook.generatePushBuild(GitLabWebHook.java:378)
    at com.dabsquared.gitlabjenkins.GitLabWebHook.generateBuild(GitLabWebHook.java:338)
    at com.dabsquared.gitlabjenkins.GitLabWebHook.getDynamic(GitLabWebHook.java:146)
    ... 55 more

_Jenkins Gitlab Plugin logs:_
Sep 02, 2016 12:54:06 AM INFO com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
WebHook called with url: 
Sep 02, 2016 12:54:06 AM FINE com.dabsquared.gitlabjenkins.GitLabWebHook
data: {
    "ref": "refs/tags/v0.0.45",
    "before": "0000000000000000000000000000000000000000",
    "after": "4834ff59e4d022149a64ee6630cd6416fbed5efe",
    "user_id": 16,
    "user_name": "user name",
    "project_id": 155,
    "repository":     {
        "name": "distrbuild",
        "url": "ssh://git@gitlab-server/ci/distrbuild.git",
        "description": "Creating a distribution project based environment list",
        "homepage": "https://gitlab-server/ci/distrbuild"
    }
}
Sep 02, 2016 12:54:06 AM INFO com.dabsquared.gitlabjenkins.GitLabPushTrigger onPost
distrbuild triggered for push.
Sep 02, 2016 12:54:06 AM INFO com.dabsquared.gitlabjenkins.GitLabPushTrigger createActions
GitLab Push Request from branch refs/tags/v0.0.45.

Thanks in advance

**Comment by coder-hugo** [comment]
Please upgrade at least the gitlab-plugin. The current version is 1.3.2. Between version 1.1.x and 1.2.x the plugin was rewritten almost completely including several bug fixes. Furthermore you are using a pretty old version of GitLab (8.11 is the most recent one) we can't guarantee that the plugin will work properly with this version.

**Comment by asn80** [comment]
Thank you for your answer. After update gitlab-plugin version to 1.3.2. We got anothe message in gitlab plugin logs

**Comment by asn80** [comment]
Sep 02, 2016 3:59:33 PM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/distrbuild
Sep 02, 2016 3:59:33 PM FINE com.dabsquared.gitlabjenkins.webhook.ActionResolver
Missing X-Gitlab-Event header

What it's all about?

**Comment by coder-hugo** [comment]
Looks like your old GitLab installation doesn't includes the HTTP Header `X-Gitlab-Event` when sending a web hook to the Jenkins. This is required for the plugin to distinguish between the different types of web hooks (push, merge request, comment, ...).
If you want to use this plugin you should upgrade your GitLab as well. We don't support any version prior to GitLab 8.1 officially. Which means it may work with older version but if not your are out of luck.
