### ISSUE TITLE
Jenkins build error while fetch the repo

### ISSUE THREAD

**Issue by thangam105** [jenkinsci/gitlab-plugin#484]
Machine configuration:
windows 10
Jenkins version 2.32.1,
Git version 2.11.0
============================================================
**Jenkins configuration**

configuration system
![image](https://cloud.githubusercontent.com/assets/13119007/21817544/65c4e30c-d78a-11e6-8547-2c0f2c7c0388.png)

Jenkins Job:

![image](https://cloud.githubusercontent.com/assets/13119007/21817599/a10c7fd8-d78a-11e6-87b7-a7ff19a0e0af.png)

![image](https://cloud.githubusercontent.com/assets/13119007/21817613/b0804cf6-d78a-11e6-99b2-8f08d4adcba0.png)

![image](https://cloud.githubusercontent.com/assets/13119007/21817622/bf26a1d8-d78a-11e6-8760-7d3344591bb6.png)

==============================================================
**Gitlab configuration:**
  Added webhooks in corresponding repository.

![image](https://cloud.githubusercontent.com/assets/13119007/21817702/0ede1de6-d78b-11e6-8fe8-7595fba5a965.png)
=============================================================
If i will commit anything in repo. Jenkins build is running. But its throw the some error.

```
Started by GitLab push by Thangavel E
Building in workspace C:\Program Files (x86)\Jenkins\workspace\ej1-listview-component
Cloning the remote Git repository
Cloning repository http://gitlab.com/thangavele/ej1-listview-component.git
 > git.exe init C:\Program Files (x86)\Jenkins\workspace\ej1-listview-component # timeout=10
Fetching upstream changes from http://gitlab.com/thangavele/ej1-listview-component.git
 > git.exe --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git.exe fetch --tags --progress http://gitlab.com/thangavele/ej1-listview-component.git +refs/heads/*:refs/remotes/origin/*
ERROR: Timeout after 10 minutes
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git.exe fetch --tags --progress http://gitlab.com/thangavele/ej1-listview-component.git +refs/heads/*:refs/remotes/origin/*" returned status code -1:
stdout: 
stderr: 
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1772)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1516)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:67)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:318)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:515)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1054)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1094)
	at hudson.scm.SCM.checkout(SCM.java:495)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1278)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1728)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
ERROR: null
Finished: FAILURE
====================================================
```
How to resolve this? Please suggest to me

Regards,
Thangavel E

**Comment by omehegan** [comment]
This is not a GitLab plugin problem; the build is triggering correctly, but Jenkins is unable to clone your Git repo. I can't tell why, but, "Timeout after 10 minutes" would suggest to me that maybe Jenkins is unable to connect back to GitLab to clone. I would suggest setting your branch specifier to 'origin/master' and running the build manually. Once you get that cloning working, the trigger via the GitLab plugin should also work.

**Comment by ChenMin46** [comment]
have you solved the problem? @thangam105 
i have the same issue.

**Comment by nissaba** [comment]
I am having same problem. I have the setup where we have a shared user called Jenkins. 
I tied to run the git fetch commonage in shell impersonating the Jenkins suer. The system asked me to create a keychain as there where none to be found. this is normal as the Jenkins user created by the installer is not a lovable user. So I let the system create a keychain gave it a password. this let me from the shell clone the repo. Still for now I am not able to get the Jenkins server to do this... maybe it needs some file access to a fake or external keychain

**Comment by gauravsrivastav** [comment]
###  **`ERROR: Timeout after 10 minutes
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git.exe fetch --tags --progress 
returned status code -1:
stdout: 
stderr: 
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java: 1903)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1622)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:71)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:348)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:545)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1067)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1107)
	at hudson.scm.SCM.checkout(SCM.java:495)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1212)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:560)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:485)
	at hudson.model.Run.execute(Run.java:1735)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:415)
ERROR: null
Finished: FAILURE`**

Answer: Solution 

**Right GitLab plugin only triggers the job.   Also i got this issue so i had just restart my Jenkins server (Jenkins Service),  after that it help to build successfully So try and see if it helps in your case.`**

**Comment by carl1990** [comment]
@gauravsrivastav  I face to the same problem, have you resolves?

**Comment by kishoredr** [comment]
@omehegan I'm also facing the same issue how to resolve it?

**Comment by smkart** [comment]
Same issue just installed Jenkins this morning

**Comment by lucaspalavecino46** [comment]
i have the same issue

**Comment by bernadinm** [comment]
I also ran into this with github (not gitlab) and a restart of the jenkins was a workaround this issue for me. It would be nice to get a root cause and permanent fix.

**Comment by rhlpandey1** [comment]
Failed to connect to repository : Error performing git command: git.exe ls-remote -h https://github.com/rhlpandey1/PythonSeleniumFramework.git HEAD

Getting this while pasting the git repo url

Any clue?

**Comment by apgallon** [comment]
> Failed to connect to repository : Error performing git command: git.exe ls-remote -h https://github.com/rhlpandey1/PythonSeleniumFramework.git HEAD
> 
> Getting this while pasting the git repo url
> 
> Any clue?

Could you fix it? I'm getting the same message

**Comment by orlys** [comment]
![image](https://user-images.githubusercontent.com/25500990/106585949-da722680-6582-11eb-8134-5615a21a6005.png)
I have no idea😥😥😥
Can somebody help?

**Comment by Shubhamjpg** [comment]
Hi did you solve this problem.

**Comment by gauravsrivastav** [comment]
@Orlys Please cross-check the SCM step that the repo URL and credential are
correct and also check the webhook URL in case you have set up some pool
SCM steps.

As per the error you have shared it seems like not able to checkout with ur
repo's updated code so re-check the source code

Or 

 Restart your Jenkins server (Jenkins Service), after that it help to build successfully So try and see if it helps in your case.
