### ISSUE TITLE
SNI extension for TLS not working

### ISSUE THREAD

**Issue by MartinNowak** [jenkinsci/gitlab-plugin#497]
## Issue

Connecting to gitlab via HTTPS/TLS does not support the SNI extension, hence doesn't work with multiple HTTPS/TLS applications on the same server.

### Context
- **Gitlab plugin version**: 1.4.4
- **Gitlab version**: 8.16.4
- **Jenkins version**: 2.35

### Logs & Traces

```
java.lang.NullPointerException
	at org.jboss.resteasy.util.ReadFromStream.readFromStream(ReadFromStream.java:30)
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.bufferEntity(ClientResponse.java:307)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:48)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64)
	at com.sun.proxy.$Proxy90.headCurrentUser(Unknown Source)
```
```
avax.ws.rs.ServiceUnavailableException: HTTP 503 Service Unavailable
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:211)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:174)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:59)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64)
	at com.sun.proxy.$Proxy90.getCurrentUser(Unknown Source)
```

### Problem description

Took me quite a while to debug why the connection to gitlab did not work, the gitlab-plugin (it's resteasy client) does not support [Server Name Indication](https://en.wikipedia.org/wiki/Server_Name_Indication).

According to [[RESTEASY-1089] Server Name Indication (SNI) Support - JBoss Issue Tracker](https://issues.jboss.org/browse/RESTEASY-1089), updating httpclient from [4.3.1](https://github.com/jenkinsci/gitlab-plugin/blob/f37e53b7c355296956f18bdbf08861bac19c8e7d/pom.xml#L215) to 4.3.2 would solve the problem.

**Comment by omehegan** [comment]
I built a snapshot release of the plugin which upgrades httpclient to 4.3.2. You can download it here: http://repo.jenkins-ci.org/snapshots/org/jenkins-ci/plugins/gitlab-plugin/1.4.5-SNAPSHOT/gitlab-plugin-1.4.5-20170208.215900-1.hpi  Can you please install this and see if it fixes your problem?

**Comment by omehegan** [comment]
@MartinNowak I would like to do a release soon and incorporate this fix if it works for you. Any chance you will have a chance to test this soon?

**Comment by MartinNowak** [comment]
No, unfortunately the requests still don't seem to support SNI.

**Comment by coder-hugo** [comment]
IIRC to use SNI with resteasy you have to upgrade to version 3.1.0.Final of resteasy.

**Comment by omehegan** [comment]
RestEasy > 3.0.19 requires JDK 1.8, and I don't think it's a good idea to break 1.7 support for the plugin yet. Jenkins still officially supports 1.7, though not for much longer I don't think. But from reading the RestEasy bug @MartinNowak linked to, I think 3.0.19 may be good enough to fix this. I have built a new snapshot of the plugin with resteasy 3.0.19.Final and httpclient 4.3.2. Let me know if this helps.

http://repo.jenkins-ci.org/snapshots/org/jenkins-ci/plugins/gitlab-plugin/1.4.6-SNAPSHOT/gitlab-plugin-1.4.6-20170310.234415-1.hpi
