### ISSUE TITLE
Jenkins fails to add comments and votes on merge requests

### ISSUE THREAD

**Issue by abohne** [jenkinsci/gitlab-plugin#505]
### Context
- **Gitlab plugin version**: 1.4.4
- **Gitlab version**: 8.15.2
- **Jenkins version**: 2.19.4
- **Job type**: Freestyle

### Problem description

Gitlab triggers a build of our project when a merge request is updated.  The build completes and should be posting a success/failure comment and up/down vote on that merge request.  The comment and vote and not showing up on the merge request.  Upon further review, it looks like the jenkins plugin is trying to use the `id` instead of the `iid` when trying to add the comment and vote.  The POST to gitlab results in a 404 because the URL does not exist.

### Logs & Traces
jenkins gitlab plugin log:
```
Feb 15, 2017 12:56:33 PM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/ETS/puppet-modules-lint
Feb 15, 2017 12:56:33 PM FINE com.dabsquared.gitlabjenkins.webhook.build.NoteBuildAction
Note: {
  "object_kind" : "note",
  "user" : {
    "name" : "Andy Bohne",
    "username" : "abohne",
    "avatar_url" : "https://secure.gravatar.com/avatar/4b4604281d3c5c1ab2d3bf625325e08d?s=80&d=identicon"
  },
  "project_id" : 4,
  "project" : {
    "name" : "puppet-modules",
    "description" : "",
    "web_url" : "https://gitlab.confidential.com/enterprise-technology-services/puppet-modules",
    "avatar_url" : null,
    "git_ssh_url" : "git@gitlab.confidential.com:enterprise-technology-services/puppet-modules.git",
    "git_http_url" : "https://gitlab.confidential.com/enterprise-technology-services/puppet-modules.git",
    "namespace" : "Enterprise Technology Services",
    "visibility_level" : 0,
    "path_with_namespace" : "enterprise-technology-services/puppet-modules",
    "default_branch" : "development",
    "homepage" : "https://gitlab.confidential.com/enterprise-technology-services/puppet-modules",
    "url" : "git@gitlab.confidential.com:enterprise-technology-services/puppet-modules.git",
    "ssh_url" : "git@gitlab.confidential.com:enterprise-technology-services/puppet-modules.git",
    "http_url" : "https://gitlab.confidential.com/enterprise-technology-services/puppet-modules.git"
  },
  "object_attributes" : {
    "id" : 1027,
    "note" : "!build",
    "noteable_type" : "MergeRequest",
    "author_id" : 2,
    "created_at" : "2017-02-15 17:56:31 UTC",
    "updated_at" : "2017-02-15 17:56:31 UTC",
    "project_id" : 4,
    "attachment" : null,
    "line_code" : null,
    "commit_id" : "",
    "noteable_id" : 471,
    "st_diff" : null,
    "system" : false,
    "updated_by_id" : null,
    "type" : null,
    "position" : null,
    "original_position" : null,
    "resolved_at" : null,
    "resolved_by_id" : null,
    "discussion_id" : "0b4d8611a6944794daa8fee17e9d637602261a2d",
    "original_discussion_id" : null,
    "url" : "https://gitlab.confidential.com/enterprise-technology-services/puppet-modules/merge_requests/431#note_1027"
  },
  "repository" : {
    "name" : "puppet-modules",
    "url" : "git@gitlab.confidential.com:enterprise-technology-services/puppet-modules.git",
    "description" : "",
    "homepage" : "https://gitlab.confidential.com/enterprise-technology-services/puppet-modules"
  },
  "merge_request" : {
    "id" : 471,
    "target_branch" : "development",
    "source_branch" : "informatica_profile",
    "source_project_id" : 4,
    "author_id" : 2,
    "assignee_id" : null,
    "title" : "Informatica server profile",
    "created_at" : "2016-09-26 20:21:26 UTC",
    "updated_at" : "2017-02-15 17:56:32 UTC",
    "milestone_id" : null,
    "state" : "opened",
    "merge_status" : "can_be_merged",
    "target_project_id" : 4,
    "iid" : 431,
    "description" : "",
    "position" : 0,
    "locked_at" : null,
    "updated_by_id" : null,
    "merge_error" : null,
    "merge_params" : { },
    "merge_when_build_succeeds" : false,
    "merge_user_id" : null,
    "merge_commit_sha" : null,
    "deleted_at" : null,
    "in_progress_merge_commit_sha" : null,
    "lock_version" : null,
    "source" : {
      "name" : "puppet-modules",
      "description" : "",
      "web_url" : "https://gitlab.confidential.com/enterprise-technology-services/puppet-modules",
      "avatar_url" : null,
      "git_ssh_url" : "git@gitlab.confidential.com:enterprise-technology-services/puppet-modules.git",
      "git_http_url" : "https://gitlab.confidential.com/enterprise-technology-services/puppet-modules.git",
      "namespace" : "Enterprise Technology Services",
      "visibility_level" : 0,
      "path_with_namespace" : "enterprise-technology-services/puppet-modules",
      "default_branch" : "development",
      "homepage" : "https://gitlab.confidential.com/enterprise-technology-services/puppet-modules",
      "url" : "git@gitlab.confidential.com:enterprise-technology-services/puppet-modules.git",
      "ssh_url" : "git@gitlab.confidential.com:enterprise-technology-services/puppet-modules.git",
      "http_url" : "https://gitlab.confidential.com/enterprise-technology-services/puppet-modules.git"
    },
    "target" : {
      "name" : "puppet-modules",
      "description" : "",
      "web_url" : "https://gitlab.confidential.com/enterprise-technology-services/puppet-modules",
      "avatar_url" : null,
      "git_ssh_url" : "git@gitlab.confidential.com:enterprise-technology-services/puppet-modules.git",
      "git_http_url" : "https://gitlab.confidential.com/enterprise-technology-services/puppet-modules.git",
      "namespace" : "Enterprise Technology Services",
      "visibility_level" : 0,
      "path_with_namespace" : "enterprise-technology-services/puppet-modules",
      "default_branch" : "development",
      "homepage" : "https://gitlab.confidential.com/enterprise-technology-services/puppet-modules",
      "url" : "git@gitlab.confidential.com:enterprise-technology-services/puppet-modules.git",
      "ssh_url" : "git@gitlab.confidential.com:enterprise-technology-services/puppet-modules.git",
      "http_url" : "https://gitlab.confidential.com/enterprise-technology-services/puppet-modules.git"
    },
    "last_commit" : {
      "id" : "b72d9ccb545337c98b9849bf5b00e1c10595e2cb",
      "message" : "Updated informatica profile to include home directories\n",
      "timestamp" : "2016-10-14T11:15:27-04:00",
      "url" : "https://gitlab.confidential.com/enterprise-technology-services/puppet-modules/commit/b72d9ccb545337c98b9849bf5b00e1c10595e2cb",
      "author" : {
        "name" : "Andy Bohne",
        "email" : "bohne.andrew@confidential.com"
      }
    },
    "work_in_progress" : false
  }
}
Feb 15, 2017 12:56:33 PM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
ETS/puppet-modules-lint triggered for note.
Feb 15, 2017 12:58:11 PM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder
Call GitLab:
HTTP method: POST
URL: https://gitlab.confidential.com/api/v3/projects/4/merge_requests/471/notes
Request headers: [
Accept = [application/json],
Content-Type = [application/x-www-form-urlencoded],
PRIVATE-TOKEN = [****FILTERED****]
]
Feb 15, 2017 12:58:11 PM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder
Got response from GitLab:
URL: https://gitlab.confidential.com/api/v3/projects/4/merge_requests/471/notes
Status: 404 Not Found
Response headers: [
Cache-Control = [no-cache],
Connection = [close],
Content-Length = [35],
Content-Type = [application/json],
Date = [Wed, 15 Feb 2017 17:58:11 GMT],
Strict-Transport-Security = [max-age=15768000],
Vary = [Origin],
X-Request-Id = [71b93fda-ebf7-439d-89e4-238541ad32a7],
X-Runtime = [0.071029]
]
Response body: {
  "message" : "404 Project Not Found"
}
Feb 15, 2017 12:58:11 PM SEVERE com.dabsquared.gitlabjenkins.publisher.GitLabMessagePublisher perform
Failed to add comment on Merge Request for project '4'
javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:201)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:50)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64)
	at com.sun.proxy.$Proxy109.createMergeRequestNote(Unknown Source)
	at com.dabsquared.gitlabjenkins.publisher.GitLabMessagePublisher.perform(GitLabMessagePublisher.java:101)
	at com.dabsquared.gitlabjenkins.publisher.MergeRequestNotifier.perform(MergeRequestNotifier.java:35)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)

Feb 15, 2017 12:58:11 PM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder
Call GitLab:
HTTP method: POST
URL: https://gitlab.confidential.com/api/v3/projects/4/merge_requests/471/notes
Request headers: [
Accept = [application/json],
Content-Type = [application/x-www-form-urlencoded],
PRIVATE-TOKEN = [****FILTERED****]
]
Feb 15, 2017 12:58:11 PM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder
Got response from GitLab:
URL: https://gitlab.confidential.com/api/v3/projects/4/merge_requests/471/notes
Status: 404 Not Found
Response headers: [
Cache-Control = [no-cache],
Connection = [close],
Content-Length = [35],
Content-Type = [application/json],
Date = [Wed, 15 Feb 2017 17:58:11 GMT],
Strict-Transport-Security = [max-age=15768000],
Vary = [Origin],
X-Request-Id = [881b79cc-cfa3-4451-a563-314a1824954f],
X-Runtime = [0.055237]
]
Response body: {
  "message" : "404 Project Not Found"
}
Feb 15, 2017 12:58:11 PM SEVERE com.dabsquared.gitlabjenkins.publisher.GitLabVotePublisher perform
Failed to add vote on Merge Request for project '4'
javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:201)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:50)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64)
	at com.sun.proxy.$Proxy109.createMergeRequestNote(Unknown Source)
	at com.dabsquared.gitlabjenkins.publisher.GitLabVotePublisher.perform(GitLabVotePublisher.java:49)
	at com.dabsquared.gitlabjenkins.publisher.MergeRequestNotifier.perform(MergeRequestNotifier.java:35)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
```

**Comment by omehegan** [comment]
Were you ever able to resolve this issue? Comments and votes have generally been working AFAIK. I use the vote feature in my own installation.

**Comment by llorllale** [comment]
This is working on my setup:

* Gitlab plugin version: 1.4.8
* Gitlab version: 10.0.3
* Jenkins version: 2.73.2
* Job type: Freestyle

**Comment by ChenMin46** [comment]
I have met the same question。

- Gitlab plugin version: 1.5.3
- Jenkins version: 2.98
- Job type: Multijob
