### ISSUE TITLE
why gitlab-plugin 's advanced subomodule can't work together with Env Injector Plugin?

### ISSUE THREAD

**Issue by Joeylulu** [jenkinsci/gitlab-plugin#509]
## Issue

- **Gitlab plugin version**: 1.4.4
- **Gitlab version**: 8.9.6
- **Jenkins version**: 2.7.4
- **Job type**: Freestyle,
- **Env Injector Plugin**:  1.92.1

### Logs & Traces
```
09:23:33  > git rev-parse refs/remotes/origin/feature/20170216_popo_robot_template^{commit} # timeout=10
09:23:34 Checking out Revision ce93df73db6a7662f93649b72960b9daa0273076 (refs/remotes/origin/feature/20170216_popo_robot_template)
09:23:34  > git config core.sparsecheckout # timeout=10
09:23:34  > git checkout -f ce93df73db6a7662f93649b72960b9daa0273076
09:23:34  > git rev-list ce93df73db6a7662f93649b72960b9daa0273076 # timeout=10
09:23:34 FATAL: wrong number of arguments
09:23:34 java.lang.IllegalArgumentException: wrong number of arguments
09:23:34 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:23:34 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09:23:34 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:23:34 	at java.lang.reflect.Method.invoke(Method.java:498)
09:23:34 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:274)
09:23:34 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:255)
09:23:34 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:215)
09:23:34 	at hudson.remoting.UserRequest.perform(UserRequest.java:118)
09:23:34 	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
09:23:34 	at hudson.remoting.Request$2.run(Request.java:287)
09:23:34 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
09:23:34 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09:23:34 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
09:23:34 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
09:23:34 	at hudson.remoting.Engine$1$1.run(Engine.java:60)
09:23:34 	at java.lang.Thread.run(Thread.java:745)
09:23:34 	at ......remote call to jnlp_builder01(Native Method)
09:23:34 	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
09:23:34 	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
09:23:34 	at hudson.remoting.Channel.call(Channel.java:781)
09:23:34 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:249)
09:23:34 	at com.sun.proxy.$Proxy77.hasGitModules(Unknown Source)
09:23:34 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl.hasGitModules(RemoteGitImpl.java:592)
09:23:34 	at hudson.plugins.git.extensions.impl.SubmoduleOption.onCheckoutCompleted(SubmoduleOption.java:92)
09:23:34 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1149)
09:23:34 	at hudson.scm.SCM.checkout(SCM.java:485)
09:23:34 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
09:23:34 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
09:23:34 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
09:23:34 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
09:23:34 	at hudson.model.Run.execute(Run.java:1741)
09:23:34 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
09:23:34 	at hudson.model.ResourceController.execute(ResourceController.java:98)
09:23:34 	at hudson.model.Executor.run(Executor.java:410)
09:23:35 Finished: FAILURE
```

### Problem description

My Jenkins jobs always failed when i use Advanced sub-modules behaviors -> checked Recursively update submodules and Update tracking submodules to tip of branch.  when i canceled the function of  advanced sub-modules behaviors , the job can be done successfully. 

I use the Env Injector Plugin to execute an initialization script after a SCM checkout .. 

1. I had already checked the Node level configuration , choose the Prepare job env check box and Unset System Environment Variables check box. 

2. My jenkins runs in Master/Slave mode， which the slave node connect the master via JNLP and enable Security of Global Security Configuration. I am very curious about that the job can be done sometimes when i disable Slave-Master Access Control. 

I feel a little bit frustrated with it.(actually really )

**Comment by omehegan** [comment]
Anything you are configuring in the Git clone advanced behaviors is unrelated to the GitLab plugin. The GitLab plugin only triggers builds and sends status back to GitLab; the Git plugin handles cloning your repo. The stack trace in your error log does not reference this plugin at all. So the issue seems to be someplace else, most likely in the Git plugin. I would suggest opening a bug against that.
