### ISSUE TITLE
NullPointerException shows in gitlab-plugin 1.4.5 (fresh install)

### ISSUE THREAD

**Issue by marslo** [jenkinsci/gitlab-plugin#521]
### Context
- **Gitlab plugin version**: 1.4.5
- **Gitlab version**: 8.15.4
- **Jenkins version**: 2.32.3 LTS (+ LDAP Credential)
- **Job type**: Freestyle
- I've already read the issue #473, but this Jenkins and the plugin was installed just a couple of days before. The plugin is installed directly, not upgrade from `1.1.x`

### Logs & Traces

_Please include any relevant log that could serve to better understand the source of your issue_
For Jenkins Gitlab Plugin logs, follow instruction in [User Support section](https://github.com/jenkinsci/gitlab-plugin#user-support).
For Gitlab logs, ask an administrator to provide you the relevant Gitlab logs.

#### What I did:
Go to Jenkins **Manage Jenkins** -> **Configure System** -> **Gitlab**, click **Test Connection**.

### The `http://<JENKINS_URL>/log/gitlab-jenkins.log` shows:
```
Mar 06, 2017 5:27:26 PM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder
Call GitLab:
HTTP method: HEAD
URL: http://<GITLAB-URL>/api/v3/user
Request headers: [
Accept = [application/json],
PRIVATE-TOKEN = [****FILTERED****]
]
Mar 06, 2017 5:30:26 PM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder
Got response from GitLab:
URL: http://<GITLAB-URL>/api/v3/user
Status: 504 Gateway Timeout
Response headers: [
Connection = [close],
Content-Length = [1140],
Content-Type = [text/html],
Date = [Mon, 06 Mar 2017 09:30:38 GMT],
Server = [squid/2.7.STABLE9],
Via = [1.0 USER001.MY.COMPANY.COM:8080 (squid/2.7.STABLE9)],
X-Cache = [MISS from USER001.MY.COMPANY.COM],
X-Squid-Error = [ERR_CONNECT_FAIL 110]
]
Response body: 
Mar 06, 2017 5:37:57 PM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder
Call GitLab:
HTTP method: HEAD
URL: http://<GITLAB-URL>/api/v3/user
Request headers: [
Accept = [application/json],
PRIVATE-TOKEN = [****FILTERED****]
]
Mar 06, 2017 5:40:57 PM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder
Got response from GitLab:
URL: http://<GITLAB-URL>/api/v3/user
Status: 504 Gateway Timeout
Response headers: [
Connection = [close],
Content-Length = [1140],
Content-Type = [text/html],
Date = [Mon, 06 Mar 2017 09:41:09 GMT],
Server = [squid/2.7.STABLE9],
Via = [1.0 USER001.MY.COMPANY.COM:8080 (squid/2.7.STABLE9)],
X-Cache = [MISS from USER001.MY.COMPANY.COM],
X-Squid-Error = [ERR_CONNECT_FAIL 110]
]
Response body: 
```

### The `Configure System (http://<JENKINS_URL>/configure)` shows:
![gitalb-1](https://cloud.githubusercontent.com/assets/5822057/23605257/e1e9a544-0296-11e7-9cf4-8dbb4096fadc.png)

```
ERROR
A problem occurred while processing the request. Please check our bug tracker to see if a similar problem has already been reported. If it is already reported, please vote and put a comment on it to let us gauge the impact of the problem. If you think this is a new issue, please file a new issue. When you file an issue, make sure to add the entire stack trace, along with the version of Jenkins and relevant plugins. The users list might be also useful in understanding what has happened.

Stack trace

javax.servlet.ServletException: java.lang.NullPointerException
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:796)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:236)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
	at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:225)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at com.smartcodeltd.jenkinsci.plugin.assetbundler.filters.LessCSS.doFilter(LessCSS.java:47)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:59)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:80)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.jboss.resteasy.util.ReadFromStream.readFromStream(ReadFromStream.java:30)
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.bufferEntity(ClientResponse.java:307)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:48)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64)
	at com.sun.proxy.$Proxy115.headCurrentUser(Unknown Source)
	at com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig.doTestConnection(GitLabConnectionConfig.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:335)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:175)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:108)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:124)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	... 68 more
```

### The `/var/log/jenkins/jenkins.log` shows:
```
Mar 06, 2017 5:40:57 PM org.eclipse.jetty.util.log.JavaUtilLog warn
WARNING: Error while serving http://<JENKINS_URL>/descriptorByName/com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig/testConnection
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:335)
        at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:175)
        at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:108)
        at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:124)
        at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
        at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:236)
        at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
        at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
        at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:225)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
        at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
        at com.smartcodeltd.jenkinsci.plugin.assetbundler.filters.LessCSS.doFilter(LessCSS.java:47)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
        at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:59)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
        at jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
        at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:80)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
        at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
        at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
        at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.jboss.resteasy.util.ReadFromStream.readFromStream(ReadFromStream.java:30)
        at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.bufferEntity(ClientResponse.java:307)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:48)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64)
        at com.sun.proxy.$Proxy115.headCurrentUser(Unknown Source)
        at com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig.doTestConnection(GitLabConnectionConfig.java:130)
        ... 78 more

```

The Gitlab API token should be right. Cause Gitlab API URL can be visit succeed by using `provivate_token`:
![gitlab-2](https://cloud.githubusercontent.com/assets/5822057/23605303/104fa74e-0297-11e7-968d-f291542b5282.png)

### Problem description

_Describe your problem in a meaningful way_:
- what were you doing 
The configuration.
- what was expected
Jenkins can connect to Gitlab successfully
- what occurred finally
The error shows up.

**Comment by marslo** [comment]
From the `http://<JENKINS_URL>/log/gitlab-jenkins.log`, looks it's stuck at the LDAP certification? `USER001.MY.COMPANY.COM:8080` is the our LDAP server. But, normally, we are using the LDAP server without port `8080`.

**Comment by omehegan** [comment]
This looks mostly like a GitLab issue - it is returning a 504 for our requests. I don't really know why that would be. I would check the GitLab server logs and see if there is any more information there.

We should probably handle this case more gracefully though.

**Comment by marslo** [comment]
Thanks @omehegan, if you need any logs or something, I can help.

**Comment by Restage** [comment]
@omehegan I've got the same problem and no influence on the used GitLab version. Do you have any suggestions for a workaround?

**Comment by marslo** [comment]
Hi @omehegan, I've upgraded the Gitlab to the latest version `9.0.0`. However, this issue still exists.
I've check the Gitlab, and found something, maybe related with this issue. The **Jenkins CI** cannot be found in _Project_ -> **Settings** -> **Integrations** -> **Project services**. And, it's actually introduced in [gitlab official website](https://docs.gitlab.com/ee/integration/jenkins.html#jenkins-service)

Here the screenshot:
![gitlab-jenkins](https://cloud.githubusercontent.com/assets/5822057/24252590/d2753558-1018-11e7-9e82-e4d4de1a813d.png)

**Comment by marslo** [comment]
@Restage, right now, I'm using the [webhook function](http://pww.gitlab.cdi.philips.com/help/user/project/integrations/webhooks) in Gitlab Project Settings. And setup `Authentication Token` in Jenkins `Trigger builds remotely`. It's kind of annoying, you have to setup webhook for each Project independently. And if there's something changed, you have to setup webhook URL again (e.g. with parameter or not).
Here screenshot in Gitlab -> _Project_ -> **Settings** -> **Integrations**:
![webhook](https://cloud.githubusercontent.com/assets/5822057/24252997/05bdf566-101a-11e7-939a-496402f28fa5.png)

**Comment by omehegan** [comment]
I don't think this is necessarily a bug in GitLab or in the plugin. It looks like a GitLab configuration issue. I would try using `sudo gitlab-ctl tail` to observe the GitLab logs when it is returning a 403 to Jenkins. That may shed some light on why it is doing that.

**Comment by marslo** [comment]
Hi @omehegan, is there any workaround to fix it?
Thanks.

**Comment by marslo** [comment]
Hi @omehengan,

Well.... I 'fixed' this issue. Maybe it's not a issue actually.

Here is my situation:
Due to the company network environment, the Jenkins has been setup the proxy in **Manage Jenkins** -> **Manage Plugins** -> **Advanced** -> **HTTP Proxy Configuration** (http://<jenkins.url>/pluginManager/advanced). And somehow this proxy server has connect problem with gitlab server, even Jenkins server and Gitlab server are all in the same subnet. Looks like after the HTTP Proxy Configuration will effect the all connections.

Here is what I did:
I've added the Gitlab url in the `No Proxy Host` input box, and it works now....

Here the comparison:
- Before setup the `No Proxy Host`
![jks-2](https://cloud.githubusercontent.com/assets/5822057/25171240/b84c7972-251f-11e7-9eb8-0f0293b2c99b.png)

- After setup the `No Proxy Host`
![jks](https://cloud.githubusercontent.com/assets/5822057/25171251/bf49380a-251f-11e7-82eb-75a8b3b0660f.png)
![jks-3](https://cloud.githubusercontent.com/assets/5822057/25172307/2a0bc682-2523-11e7-970f-da3142383d23.png)

**Comment by omehegan** [comment]
OK. So mostly an environment issue. On the plugin side, we should improve the behavior so we don't throw an exception when we get this error back (from the proxy server, in this case).

**Comment by marslo** [comment]
Yes. I didn't also realized it was caused of proxy settings in plugin management.

**Comment by huayaoyue6** [comment]
Maybe chose the exactly option in checkbox named "API-LEVEL" can help  :smile: .  @omehegan
