### ISSUE TITLE
Failed to render status.png

### ISSUE THREAD

**Issue by JozoVilcek** [jenkinsci/gitlab-plugin#55]
I am getting an error when gitlab tries to render a status image for my project. Going to the URL, jenkins shows following error:
```
javax.servlet.ServletException: java.lang.IllegalArgumentException: This repo does not use git.
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:795)
	...
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.IllegalArgumentException: This repo does not use git.
	at com.dabsquared.gitlabjenkins.GitLabWebHook.generateStatusPNG(GitLabWebHook.java:237)
	at com.dabsquared.gitlabjenkins.GitLabWebHook.getDynamic(GitLabWebHook.java:146)
	at sun.reflect.GeneratedMethodAccessor2082.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
	at org.kohsuke.stapler.MetaClass$12.dispatch(MetaClass.java:389)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:745)
	... 70 more
```
I reckon this is because my project uses Multiple SCMs?

**Comment by bassrock** [comment]
@JozoVilcek yes that would be the case I bet. Open to any pull request for this.

**Comment by kevindashgit** [comment]
@JozoVilcek where would that log output be that you found above (`java.lang.IllegalArgumentException`)? 

I'm getting a similar issue - the error on the client side simply indicates: 

```
HTTP ERROR 404

Problem accessing /job/<JobName>//status.png. Reason:

    Not Found
https://<JenkinsServer>/job/<JobName>//status.png?ref=master
```

(I replaced `JenkinsServer` and `JobName` in this output).

**Comment by JozoVilcek** [comment]
@kevindashgit sorry, I do not remember exact URL, but it was the one, gitlab was using to render a status image on a project home page (taken from HTML).

**Comment by kevindashgit** [comment]
Actually, my problem seems to be two-fold (and do let me know if it makes more sense to open a new issue):

1) 404'd on status.png (see my previous comment)
2) On a merge request, the plugin displays: `Cannot connect to CI server. Please check your setting`. 

I wonder if it could be an authentication thing? I'm on `GitLab 6.3.0` and `gitlab-plugin v1.1.28`

Any ideas welcome!

**Comment by omehegan** [comment]
@kevindashgit GitLab 6.x is pretty old. The original author of this plugin updated his GitLab version, and this plugin as a result, pretty frequently. I don't think he did any backwards-compatibility testing of the plugin early on, so it's possible that your version is just not supported. Just putting it out there.
