### ISSUE TITLE
Merge before build + tag fails

### ISSUE THREAD

**Issue by phaza** [jenkinsci/gitlab-plugin#573]
### Context
- **Gitlab plugin version**: 1.4.5
- **Gitlab version**: 9.12.5
- **Jenkins version**: 2.46.3
- **Job type**: Freestyle

### Logs & Traces

```
00:00:11.860 Fetching upstream changes from git@xxx.git
00:00:11.861 using GIT_SSH to set credentials jenkins ssh
00:00:11.865  > git.exe fetch --tags --progress git@xxx.git +refs/heads/*:refs/remotes/origin/* +refs/merge-requests/*/head:refs/remotes/origin/merge-requests/* +refs/tags/*:refs/remotes/origin/tags/*
00:00:12.828  > git.exe rev-parse "refs/tags/7.8.997^{commit}" # timeout=10
00:00:12.865  > git.exe branch -a -v --no-abbrev --contains 48d36b6c791fb753f9d603ba72dc69335f8558cb # timeout=10
00:00:12.914 Merging Revision 48d36b6c791fb753f9d603ba72dc69335f8558cb (origin/monolith, origin/tags/7.8.997) to origin/refs/tags/7.8.997, UserMergeOptions{mergeRemote='origin', mergeTarget='${gitlabTargetBranch}', mergeStrategy='default', fastForwardMode='--ff'}
00:00:12.933  > git.exe rev-parse "origin/refs/tags/7.8.997^{commit}" # timeout=10
00:00:12.964 FATAL: Command "git.exe rev-parse "origin/refs/tags/7.8.997^{commit}"" returned status code 128:
00:00:12.964 stdout: origin/refs/tags/7.8.997^{commit}
00:00:12.964 
00:00:12.964 stderr: fatal: ambiguous argument 'origin/refs/tags/7.8.997^{commit}': unknown revision or path not in the working tree.
00:00:12.964 Use '--' to separate paths from revisions, like this:
00:00:12.964 'git <command> [<revision>...] -- [<file>...]'
00:00:12.964 
00:00:12.964 hudson.plugins.git.GitException: Command "git.exe rev-parse "origin/refs/tags/7.8.997^{commit}"" returned status code 128:
00:00:12.964 stdout: origin/refs/tags/7.8.997^{commit}
00:00:12.964 
00:00:12.964 stderr: fatal: ambiguous argument 'origin/refs/tags/7.8.997^{commit}': unknown revision or path not in the working tree.
00:00:12.964 Use '--' to separate paths from revisions, like this:
00:00:12.964 'git <command> [<revision>...] -- [<file>...]'
00:00:12.964 
00:00:12.964 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1903)
00:00:12.964 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1871)
00:00:12.964 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1867)
00:00:12.964 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1512)
00:00:12.964 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1524)
00:00:12.964 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.revParse(CliGitAPIImpl.java:718)
00:00:12.964 	at hudson.plugins.git.GitAPI.revParse(GitAPI.java:316)
00:00:12.964 	at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
00:00:12.964 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:00:12.964 	at java.lang.reflect.Method.invoke(Method.java:498)
00:00:12.964 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:895)
00:00:12.964 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:870)
00:00:12.964 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:829)
00:00:12.964 	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
00:00:12.964 	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
00:00:12.964 	at hudson.remoting.Request$2.run(Request.java:336)
00:00:12.964 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
00:00:12.964 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:00:12.964 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
00:00:12.964 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
00:00:12.964 	at hudson.remoting.Engine$1$1.run(Engine.java:94)
00:00:12.964 	at java.lang.Thread.run(Thread.java:748)
00:00:12.964 	at ......remote call to JNLP4-connect connection from 10.0.254.179/10.0.254.179:49736(Native Method)
00:00:12.964 	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1545)
00:00:12.964 	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
00:00:12.964 	at hudson.remoting.Channel.call(Channel.java:830)
00:00:12.964 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:257)
00:00:12.964 	at com.sun.proxy.$Proxy57.revParse(Unknown Source)
00:00:12.964 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl.revParse(RemoteGitImpl.java:558)
00:00:12.964 	at hudson.plugins.git.extensions.impl.PreBuildMerge.decorateRevisionToBuild(PreBuildMerge.java:65)
00:00:12.964 	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:1015)
00:00:12.964 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1108)
00:00:12.964 	at hudson.scm.SCM.checkout(SCM.java:496)
00:00:12.964 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1281)
00:00:12.964 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
00:00:12.964 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
00:00:12.964 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
00:00:12.964 	at hudson.model.Run.execute(Run.java:1728)
00:00:12.964 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
00:00:12.964 	at hudson.model.ResourceController.execute(ResourceController.java:98)
00:00:12.964 	at hudson.model.Executor.run(Executor.java:405)
```

### Problem description
Everything is working great for normal pushes and merge requests, however when I create a tag in gitlab the above error occurs.

Repo is setup with:
* Name: origin
* refspec: +refs/heads/*:refs/remotes/origin/* +refs/merge-requests/*/head:refs/remotes/origin/merge-requests/* +refs/tags/*:refs/remotes/origin/tags/*
* Branches to build: origin/${gitlabSourceBranch}

Merge before build is setup as follows:
* Name of repository: origin
* Branch to merge to: ${gitlabTargetBranch}
* Merge strategy: default
* FF-mode: --ff

Now I know I can just create a new build config that doesn't have merge before build behavior, but since we have quite many build steps, I'm reluctant to have two configurations to keep in sync.

**Comment by LoicGombeaud** [comment]
Hi @phaza, I have the same issue, did you find a solution after all?

**Comment by phaza** [comment]
We stopped using Jenkins and moved to gitlab’s CI. Best decision ever :)

**Comment by LoicGombeaud** [comment]
Ha, we're considering doing the same thing :) Thanks for the quick feedback!

**Comment by omehegan** [comment]
@LoicAG feel free to open a new issue about this and provide whatever info you can. I never responded to the original issue because the author closed it without comment after two days, and now it's 18 months later. It looks like an issue with the data being passed to the git client for cloning; we should be able to figure it out.

**Comment by koverly** [comment]
I'm experiencing the same problem and can reproduce it pretty easily.

Here's the relevant console output:
 > git.exe branch -a -v --no-abbrev --contains 4321808c18bbc399808f8f54d6f111e764971d51 # timeout=10
Merging Revision 4321808c18bbc399808f8f54d6f111e764971d51 (origin/tags/TEST2, origin/master) to origin/refs/tags/TEST2, UserMergeOptions{mergeRemote='origin', mergeTarget='refs/tags/TEST2', mergeStrategy='default', fastForwardMode='--ff'}
 > git.exe rev-parse "origin/refs/tags/TEST2^{commit}" # timeout=10
FATAL: Command "git.exe rev-parse "origin/refs/tags/TEST2^{commit}"" returned status code 128:
stdout: origin/refs/tags/TEST2^{commit}
stderr: fatal: ambiguous argument 'origin/refs/tags/TEST2^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
hudson.plugins.git.GitException: Command "git.exe rev-parse "origin/refs/tags/TEST2^{commit}"" returned status code 128:
stdout: origin/refs/tags/TEST2^{commit}
stderr: fatal: ambiguous argument 'origin/refs/tags/TEST2^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
