### ISSUE TITLE
Trouble connecting back to gitlab 8.17 from Jenkins 2.60.1

### ISSUE THREAD

**Issue by mmucklo** [jenkinsci/gitlab-plugin#577]
## Issue
"Manage Jenkins"
"Configure System"
"Gitlab -> GitLab connections" section

When trying to configure the Gitlab plugin, even with the right API token, Jenkins is instantly responding "Connection Refused" when clicking Test.

No traffic is seen in tcpdump

curl --url [gitlab url] works from the command line, traffic is seen in tcpdump.

### Context
- **Gitlab plugin version**: 1.4.5
- **Gitlab version**: 8.17.5-ee
- **Jenkins version**: 2.60.1

java version "1.8.0"
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) 64-Bit Server VM (build 25.0-b70, mixed mode)

### Logs & Traces

We have enabled the system logs for gitlab plugin as specified in the [User Support section](https://github.com/jenkinsci/gitlab-plugin#user-support).

However this is about the only thing we eventually get in the logs:

```Jul 05, 2017 3:09:10 PM com.dabsquared.gitlabjenkins.util.CommitStatusUpdater updateCommitStatus
SEVERE: Failed to update Gitlab commit status for project '....'
javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request
        at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:287)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:436)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:102)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64)
        at com.sun.proxy.$Proxy112.getCommit(Unknown Source)
        at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.existsCommit(CommitStatusUpdater.java:97)
        at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.updateCommitStatus(CommitStatusUpdater.java:47)
        at com.dabsquared.gitlabjenkins.publisher.GitLabCommitStatusPublisher.prebuild(GitLabCommitStatusPublisher.java:42)
        at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:789)
        at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:784)
        at hudson.model.Build$BuildExecution.doRun(Build.java:145)
        at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:490)
        at hudson.model.Run.execute(Run.java:1735)
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
        at hudson.model.ResourceController.execute(ResourceController.java:97)
        at hudson.model.Executor.run(Executor.java:405)
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:120)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:179)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:328)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:612)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:447)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
        at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:283)
        ... 15 more
```

**Comment by omehegan** [comment]
Well, connection refused... I would double and triple check that you are looking at the right thing with tcpdump (port 80 vs 443?), and I would also look at the logs on the GitLab side to see if it is showing anything. I'm doubtful that this is anything other than a configuration error.

**Comment by mmucklo** [comment]
@omehegan 

The tcpdump was regardless of port.

We saw traffic from:

```
curl --url https://gitlab.server.host

git+ssh connections (performed during normal builds).
```

Standard webhooks between jenkins and gitlab are working fine (which is how we're triggering builds, however the status is not updated back).

Is there any way to trace out what the precise url, or host and port that java.net.ConnectException is being triggered on?

Is there any possibility of an internal Java thing that's not set correctly with our version of Java that's running (and perhaps some kind of simple test we could compile and run to verify)?

**Comment by mmucklo** [comment]
I created a simple java test application using a java.net.URL, passing in the token as a query string and it works, even over https

Something seems to be a bit more fundamentally wrong internal to jenkins/gitlab plugin.

Any clues?

**Comment by omehegan** [comment]
I would look at the logs on the GitLab server, it should be logging the refused connection. That might offer more clues. Have you set up the necessary API authentication for Jenkins to use when it talks to GitLab to send the status? Also, if you have increased the plugin log level per the instructions in the User Support section, I *think* it should be showing you the API calls with URLs.

**Comment by mmucklo** [comment]
Update:

After uninstalling 1.4.5, and upgrading every single plugin that needed upgrading, and then reinstalling version 1.4.6 of the GitLab plugin, things are now working! Hallelujah!

Serious thorn in my side for the past few days or so...
