### ISSUE TITLE
Failed to update Gitlab commit status for project '<project>/<repo>': HTTP 404 Not Found

### ISSUE THREAD

**Issue by lmayorga1980** [jenkinsci/gitlab-plugin#601]
I am not able to get the report back to gitlab and the Gitlab CE Integrations tab is able to connect to Jenkins by using http://jenkinserver/job/<job_name> instead of the suggested #htttp://jenkinsserver/project/<job_name>.

Jenkins Version: 2.7.4
Gitlab Plugin: 1.4.7
Gitlab Server. 8.17.0
```
Aug 01, 2017 4:16:08 PM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds

Retrieving gitlab project ids

Aug 01, 2017 4:16:08 PM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater addGitLabBranchBuild

Retrieving the gitlab project id from remote url git@mygitlabserver:root/puppet-control.git

Aug 01, 2017 4:16:08 PM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Call GitLab:
HTTP method: GET
URL: https://mygitlabserver/api/v3/projects/root%2Fpuppet-control/repository/commits/9ebfeb5321d35ee118fb9f0851067ce06dbe54b7
Request headers: [
Accept = [application/json],
PRIVATE-TOKEN = [****FILTERED****]
]

Aug 01, 2017 4:16:09 PM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Got response from GitLab:
URL: https://mygitlabserver/api/v3/projects/root%2Fpuppet-control/repository/commits/9ebfeb5321d35ee118fb9f0851067ce06dbe54b7
Status: 200 OK
Response headers: [
Cache-Control = [max-age=0, private, must-revalidate],
Connection = [keep-alive],
Content-Length = [575],
Content-Type = [application/json],
Date = [Tue, 01 Aug 2017 21:16:09 GMT],
Etag = [W/"49c81fa956216552d60aa53029755e68"],
Server = [nginx],
Vary = [Origin],
X-Request-Id = [92c13b3b-b726-4238-9b6d-364c1680b39c],
X-Runtime = [0.071609]
]
Response body: {
  "id" : "9ebfeb5321d35ee118fb9f0851067ce06dbe54b7",
  "short_id" : "9ebfeb53",
  "title" : "fix Gemfile source url",
  "message" : "fix Gemfile source url\n",
  "parent_ids" : [ "f7b63c1b508bed5ba212b827a9e5e4b31f0a09b5" ],
  "committed_date" : "2017-08-01T10:10:53.000-05:00",
  "authored_date" : "2017-08-01T10:10:53.000-05:00",
  "stats" : {
    "additions" : 1,
    "deletions" : 1,
    "total" : 2
  },
  "status" : null
}

Aug 01, 2017 4:16:09 PM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Call GitLab:
HTTP method: POST
URL: https://mygitlabserver/api/v3/projects/root%2Fpuppet-control/statuses/9ebfeb5321d35ee118fb9f0851067ce06dbe54b7
Request headers: [
Accept = [application/json],
Content-Type = [application/x-www-form-urlencoded],
PRIVATE-TOKEN = [****FILTERED****]
]

Aug 01, 2017 4:16:09 PM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Got response from GitLab:
URL: https://mygitlabserver/api/v3/projects/root%2Fpuppet-control/statuses/9ebfeb5321d35ee118fb9f0851067ce06dbe54b7
Status: 404 Not Found
Response headers: [
Cache-Control = [no-cache],
Connection = [keep-alive],
Content-Length = [49],
Content-Type = [application/json],
Date = [Tue, 01 Aug 2017 21:16:09 GMT],
Server = [nginx],
Vary = [Origin],
X-Request-Id = [2fe8236f-ae98-44a4-81c6-530580f785b4],
X-Runtime = [0.034499]
]
Response body: {
  "message" : "404 References for commit Not Found"
}

Aug 01, 2017 4:16:09 PM SEVERE com.dabsquared.gitlabjenkins.util.CommitStatusUpdater updateCommitStatus

Failed to update Gitlab commit status for project 'root/puppet-control'
javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:201)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:50)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64)
	at com.sun.proxy.$Proxy90.changeBuildStatus(Unknown Source)
	at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.updateCommitStatus(CommitStatusUpdater.java:57)
	at com.dabsquared.gitlabjenkins.publisher.GitLabCommitStatusPublisher.prebuild(GitLabCommitStatusPublisher.java:45)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:834)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:829)
	at hudson.model.Build$BuildExecution.doRun(Build.java:144)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
```
#399

**Comment by omehegan** [comment]
@lmayorga1980 triggering the Jenkins job using the /job endpoint rather than /project bypasses this plugin entirely, and does not allow GitLab to pass Jenkins any information to populate variable for the build. So yes, that will work, but only in a very limited way. It's not the way this plugin should be used.

Other people occasionally see this issue, and as you noticed in #399 it is often caused by Apache. But you said you aren't using that. I'm not sure how else to debug this. Somewhere that Jenkins needs to request is getting mangled. I believe we get that from the JSON payload from GitLab. Was this build manually triggered by you in Jenkins, or triggered by GitLab?

**Comment by lmayorga1980** [comment]
Maybe is the way i am using the endpoint on the gitlab ce integrations page.  I triggered this build manually from the GUI. Does this plugin only supports automatic build from gitlab only?

**Comment by lmayorga1980** [comment]
Update:

**Jenkins Version**: 2.60.2
**Gitlab Plugin**: 1.4.7

After updating Gitlab CE Integrations Page with http://jenkinsurl:8080/project/<project_name> I did not receive any HTTP 404 errors.

**Comment by omehegan** [comment]
@lmayorga1980 you might have found a bug; there's no reason you shouldn't be able to build manually. My theory is that the plugin receives the necessary URL from the GitLab JSON payload when a build is triggered by GitLab, but has to compose the URL itself if you trigger the build manually. It looks to me like that compose step does improper encoding of the / character when it puts together the $NAMESPACE/$PROJECT string. I will track this elsewhere, maybe we can find the cause. Thank you!
