### ISSUE TITLE
Getting HTTP 403 Forbidden on Open Merge Requests

### ISSUE THREAD

**Issue by lmayorga1980** [jenkinsci/gitlab-plugin#602]
**Jenkins Version:** 2.7.4
**Gitlab Plugin:** 1.4.7
**Gitlab Server:** 8.17.0

It seems that the commit status works fine after the Merge Request is merged and I am able to see the build status on the resulting commit but could not see the **Commit Status** when the MR is still open but the build is triggered successfully.

The jenkins user in gitlab has the **Developer** role assigned to the repository. Are there any other permissions that need to be set?

```
Response body: {
  "message" : "403 Forbidden"
}

Aug 02, 2017 9:43:16 AM SEVERE com.dabsquared.gitlabjenkins.util.CommitStatusUpdater updateCommitStatus

Failed to update Gitlab commit status for project '96'
javax.ws.rs.ClientErrorException: HTTP 403 Forbidden
    at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:216) 
    at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:50) 
    at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104) 
    at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64) 
    at com.sun.proxy.$Proxy92.changeBuildStatus(Unknown Source)
    at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.updateCommitStatus(CommitStatusUpdater.java:57) 
    at com.dabsquared.gitlabjenkins.publisher.GitLabCommitStatusPublisher.prebuild(GitLabCommitStatusPublisher.java:45) 
    at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:789) 
    at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:784) 
    at hudson.model.Build$BuildExecution.doRun(Build.java:145)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:490) 
    at hudson.model.Run.execute(Run.java:1735)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:97)
    at hudson.model.Executor.run(Executor.java:405)
```

**Comment by omehegan** [comment]
That is strange that it gets a 403 when the MR is open, but not after it is closed... something strange is happening on the GitLab side. I would check the logs there and see if there is any more information. Developer permission should be all that is necessary, but I have a vague memory of someone discovering that they needed to make sure Developer users can also access the API or something. Not normally a problem, but they had locked down GitLab a little more than it is by default. I can't find the specific issue where this was mentioned though.

**Comment by lmayorga1980** [comment]
@omehegan , I will check if there is any API permission that is missing.

**Comment by lmayorga1980** [comment]
The developer role on the specific repository did not do it for me. However by changing the Access Level actually helped me out on reporting on the Open Merge Request.

@omehegan I believe you should update the `README.md` unless you need a PR I will be glad to contribute.

![gitlab](https://user-images.githubusercontent.com/3172378/28895385-2d6d0ec8-77a6-11e7-83b7-e683d4cfe4db.png)

**Comment by omehegan** [comment]
@lmayorga1980 I don't think you should need to make the user an admin of the whole GitLab instance.

@dblessing if you have a chance, can you take a look at this? Historically people have just needed the GitLab user to have Developer permissions in order for API calls to work, I've never heard of this not being enough.
