### ISSUE TITLE
Cloning the remote Git repository

### ISSUE THREAD

**Issue by trollcodelord** [jenkinsci/gitlab-plugin#689]
Cloning the remote Git repository

Cloning repository git@github.com:trollcodelord/Newman-Jenk.git
 > git init /Users/Shared/Jenkins/Home/workspace/newman-jenkin@2 # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Could not init /Users/Shared/Jenkins/Home/workspace/newman-jenkin@2
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:747)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:539)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1083)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1123)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:113)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:85)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:75)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: hudson.plugins.git.GitException: Error performing command: git init /Users/Shared/Jenkins/Home/workspace/newman-jenkin@2
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1977)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1938)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1934)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1572)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:745)
	... 14 more
Caused by: java.io.IOException: Cannot run program "git" (in directory "/Users/Shared/Jenkins/Home/workspace/newman-jenkin@2"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at hudson.Proc$LocalProc.<init>(Proc.java:249)
	at hudson.Proc$LocalProc.<init>(Proc.java:218)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:930)
	at hudson.Launcher$ProcStarter.start(Launcher.java:450)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1966)
	... 18 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 23 more

**Comment by mreichel** [comment]
To me it looks like your git is not configured correctly in Jenkins. You should set that up in the Jenkins settings.

**Comment by trollcodelord** [comment]
Please guide how to configure GIT on jenkin

**Comment by mreichel** [comment]
Please use documentation available on the internet (eg. https://stackoverflow.com/questions/8639501/jenkins-could-not-run-git )

**Comment by omehegan** [comment]
This plugin does not clone repos, it only triggers builds based on events in GitLab. If you need help with the Git plugin, please follow the documentation and support options from https://wiki.jenkins.io/display/JENKINS/Git+Plugin

**Comment by vonkdoth-solutions** [comment]
Started by timer
Building in workspace /var/lib/jenkins/workspace/DB_backup
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/vonkdoth-solutions/MillionAuthors.git # timeout=10
Fetching upstream changes from https://github.com/vonkdoth-solutions/MillionAuthors.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --tags --progress https://github.com/vonkdoth-solutions/MillionAuthors.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision 5de22ec867c0b5f74bec2c7f8183ebae603d8ab5 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 5de22ec867c0b5f74bec2c7f8183ebae603d8ab5
FATAL: Could not checkout 5de22ec867c0b5f74bec2c7f8183ebae603d8ab5
hudson.plugins.git.GitException: Command "git checkout -f 5de22ec867c0b5f74bec2c7f8183ebae603d8ab5" returned status code 137:
stdout: 
stderr: 
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2016)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$800(CliGitAPIImpl.java:72)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2315)
Caused: hudson.plugins.git.GitException: Could not checkout 5de22ec867c0b5f74bec2c7f8183ebae603d8ab5
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2339)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1236)
	at hudson.scm.SCM.checkout(SCM.java:504)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
	at hudson.model.Run.execute(Run.java:1819)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
How can I fix this.

**Comment by AndreaBasile97** [comment]
If the jenkins pipeline was working and after a while this happen, you can simply safeRestart the jenkins using '/safeRestart' command
