### ISSUE TITLE
Build on successful pipeline events

### ISSUE THREAD

**Issue by sleepypikachu** [jenkinsci/gitlab-plugin#723]
### Context
- **Gitlab plugin version**: 1.5.3
- **Gitlab version**: 9.1.4
- **Jenkins version**: 2.89.4
- **Job type**: Pipeline

### Logs & Traces

Nothing appears in the logs when I perform this action.

### Problem description

_Describe your problem in a meaningful way_:
When I set  *Build on successful pipeline events* on my build trigger and save the job it is unset when I re-open the job.
- what was expected
The setting would persist and my build would be triggered by pipeline events.
- what occurred finally
The setting does not persist.

**Comment by sleepypikachu** [comment]
Seems similar to https://github.com/jenkinsci/gitlab-plugin/issues/711 but I've checked with the Job Config History plugin and even when the value is set on the UI it does not appear in the diff.

**Comment by sleepypikachu** [comment]
If I modify the XML by hand then I can get the PipelineHook to trigger but unfortunately the event seems to be missing some required information. (See logs below)

I set the loglevel for `com.dabsquared.gitlabjenkins` to `fine` but this did not produce any additional log output on subsqequent runs.
```
Caused by: java.lang.NullPointerException: sourceProjectId must not be null.
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:204)
        at com.dabsquared.gitlabjenkins.cause.CauseData.<init>(CauseData.java:71)
        at com.dabsquared.gitlabjenkins.cause.CauseDataBuilder.build(CauseDataBuilder.java:632)
        at com.dabsquared.gitlabjenkins.trigger.handler.pipeline.PipelineHookTriggerHandlerImpl.retrieveCauseData(PipelineHookTriggerHandlerImpl.java:122)
        at com.dabsquared.gitlabjenkins.trigger.handler.pipeline.PipelineHookTriggerHandlerImpl.retrieveCauseData(PipelineHookTriggerHandlerImpl.java:32)
        at com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler.createActions(AbstractWebHookTriggerHandler.java:85)
        at com.dabsquared.gitlabjenkins.trigger.handler.pipeline.PipelineHookTriggerHandlerImpl.handle(PipelineHookTriggerHandlerImpl.java:69)
        at com.dabsquared.gitlabjenkins.trigger.handler.pipeline.PipelineHookTriggerHandlerImpl.handle(PipelineHookTriggerHandlerImpl.java:32)
        at com.dabsquared.gitlabjenkins.GitLabPushTrigger.onPost(GitLabPushTrigger.java:426)
        at com.dabsquared.gitlabjenkins.webhook.build.PipelineBuildAction$1.performOnPost(PipelineBuildAction.java:62)
        at com.dabsquared.gitlabjenkins.webhook.build.BuildWebHookAction$TriggerNotifier.run(BuildWebHookAction.java:54)
        at hudson.security.ACL.impersonate(ACL.java:243)
        at com.dabsquared.gitlabjenkins.webhook.build.PipelineBuildAction.execute(PipelineBuildAction.java:59)
        at com.dabsquared.gitlabjenkins.webhook.build.BuildWebHookAction.execute(BuildWebHookAction.java:31)
        at com.dabsquared.gitlabjenkins.webhook.GitLabWebHook.getDynamic(GitLabWebHook.java:44)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
        at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
        ... 74 more
```

**Comment by omehegan** [comment]
I can confirm this. I'll look into it.

**Comment by omehegan** [comment]
@mreichel I was thinking this might be caused by a missing getter, but it looks like there is one. I believe this is your code, can you figure out what might be missing?

**Comment by omehegan** [comment]
I merged the fix and released a snapshot of it for now (not ready to do a full release yet). If you want this fix immediately, you can download http://repo.jenkins-ci.org/snapshots/org/jenkins-ci/plugins/gitlab-plugin/1.5.5-SNAPSHOT/gitlab-plugin-1.5.5-20180325.233657-1.hpi and manually install it.

**Comment by sleepypikachu** [comment]
Thanks for the expedient fix. Unfortunately I think this is only a partial fix (set the property from the UI).

As you can see from the attached logs in my earlier comment (https://github.com/jenkinsci/gitlab-plugin/issues/723#issuecomment-372686617) even when the property is set to true by hand the trigger fails with an NPE.

**Comment by omehegan** [comment]
@sleepypikachu I see, I thought the problem was being caused by the setting not staying saved. Apparently sourceProjectId is null when it should not be. Can you please check the custom logger settings you used? You should see a dump of the JSON that was sent by GitLab, among other things, when the webhook triggers a build. We need to see if GitLab is sending us the right info.

I don't use GitLab pipelines. If you can give me some direction on how to set up a mock one I can try to reproduce this.

**Comment by sleepypikachu** [comment]
I've since left the project that was working on this. I've handed this issue onto them but unfortunately I'm unable to provide the information you've requested.

**Comment by Eduard3000** [comment]
Hello 
@omehegan sorry, to drop in, but where does it say in
https://docs.gitlab.com/ce/user/project/integrations/webhooks.html#pipeline-events
sourceProjectId is a supplied field?

Yes Merge-Request has that, Pipeline has project.id!?

I would like that feature also to work, have post pipeline job to do, would be nice if somebody could have a look!?

Oh and when you start, why only on sucess? I would like to open an issue at the developer too if 
status == 'failed' 
:nerd_face:

**Comment by mreichel** [comment]
@Eduard3000 we map the project.id to the sourceProjectId. Which worked fine, but there is some change in the plugin that broke the feature and I unfortunately can't work on it. The feature was build as a feature request that is why builds only on success.

**Comment by Eduard3000** [comment]
@mreichel I wrote my own webhook handler using nodejs&npm's
node-gitlab-webhook and jenkins client to trigger other jobs with my own rules,
sending "spam" with nodemailer
and custom js to notify MS teams channels.

But thanks for the effort, the working stuff goes well with this plugin :+1: :100:

**Comment by tmc9031** [comment]
@omehegan

Context
Gitlab plugin version: 1.5.10
Gitlab version: 11.2
Jenkins version: 2.138.1
Job type: Pipeline

also same problem when enable "Build on successful pipeline events"
```
Caused by: java.lang.NullPointerException: sourceProjectId must not be null.
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:204)
	at com.dabsquared.gitlabjenkins.cause.CauseData.<init>(CauseData.java:74)
	at com.dabsquared.gitlabjenkins.cause.CauseDataBuilder.build(CauseDataBuilder.java:632)
	at com.dabsquared.gitlabjenkins.trigger.handler.pipeline.PipelineHookTriggerHandlerImpl.retrieveCauseData(PipelineHookTriggerHandlerImpl.java:128)
```

**Comment by omehegan** [comment]
@tmc9031 if you can enable debug logging as described in https://github.com/jenkinsci/gitlab-plugin#getting-help and then attach logs that show the JSON payload received in this case, it might be helpful.

**Comment by Moln** [comment]
Gitlab plugin version: 1.5.11
Gitlab version: 11.6.5
Jenkins version: 2.150.2

## Gitlab request details:

Trigger: `Pipeline Hook`

Request headers:

```
Content-Type: application/json
X-Gitlab-Event: Pipeline Hook
X-Gitlab-Token: ae62e6179cf828bfa3ec48da3ab26270
```

Request body:

```
{
  "object_kind": "pipeline",
  "object_attributes": {
    "id": 2704,
    "ref": "3.x",
    "tag": false,
    "sha": "eb85c8445fa63c2f80ebcb506d4b6605aa836c13",
    "before_sha": "9cf89e6281aaa90f4c3955415fe5cc6bf0143ea4",
    "status": "success",
    "detailed_status": "passed",
    "stages": [
      "test"
    ],
    "created_at": "2018-05-31 11:31:30 UTC",
    "finished_at": "2018-05-31 11:37:47 UTC",
    "duration": 78,
    "variables": [

    ]
  },
  "user": {
    "name": "",
    "username": "",
    "avatar_url": ""
  },
  "project": {
    "id": 80,
    "name": "auth",
    "description": "[library]",
    "web_url": "xxxxxxxxxxxxxxxx",
    "avatar_url": null,
    "git_ssh_url": "git@xxxxxx:xxxxxxxxxx.git",
    "git_http_url": "https://xxxxxx/xxxxxxxxx.git",
    "namespace": "js-packages",
    "visibility_level": 20,
    "path_with_namespace": "xxxxxxxxx",
    "default_branch": "master",
    "ci_config_path": null
  },
  "commit": {
    "id": "eb85c8445fa63c2f80ebcb506d4b6605aa836c13",
    "message": "CI\n",
    "timestamp": "2018-05-31T11:29:45Z",
    "url": "https://xxxxxxxxxxx/commit/eb85c8445fa63c2f80ebcb506d4b6605aa836c13",
    "author": {
      "name": "xxx",
      "email": "xxxx"
    }
  },
  "builds": [
    {
      "id": 4327,
      "stage": "test",
      "name": "test",
      "status": "success",
      "created_at": "2018-05-31 11:36:28 UTC",
      "started_at": "2018-05-31 11:36:28 UTC",
      "finished_at": "2018-05-31 11:37:47 UTC",
      "when": "on_success",
      "manual": false,
      "user": {
        "name": "xxxxxx",
        "username": "xxxxxxxxxxx",
        "avatar_url": "https://xxxxxxxxxxxxx"
      },
      "runner": {
        "id": 4,
        "description": "xxxxxxxxx",
        "active": true,
        "is_shared": true
      },
      "artifacts_file": {
        "filename": null,
        "size": 2139
      }
    },
    {
      "id": 4326,
      "stage": "test",
      "name": "test",
      "status": "success",
      "created_at": "2018-05-31 11:31:30 UTC",
      "started_at": "2018-05-31 11:34:15 UTC",
      "finished_at": "2018-05-31 11:36:07 UTC",
      "when": "on_success",
      "manual": false,
      "user": {
        "name": "xxxxxxx",
        "username": "xxxxxxxxxxxx",
        "avatar_url": "https://xxxxxxxxxxxxx"
      },
      "runner": {
        "id": 4,
        "description": "xxxxxxxx",
        "active": true,
        "is_shared": true
      },
      "artifacts_file": {
        "filename": null,
        "size": 2134
      }
    }
  ]
}
```

-------------

## Jenkins system log:

```
Error while serving http://192.168.80.159:8000/project/test
java.lang.NullPointerException: sourceProjectId must not be null.
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:204)
	at com.dabsquared.gitlabjenkins.cause.CauseData.<init>(CauseData.java:74)
	at com.dabsquared.gitlabjenkins.cause.CauseDataBuilder.build(CauseDataBuilder.java:632)
	at com.dabsquared.gitlabjenkins.trigger.handler.pipeline.PipelineHookTriggerHandlerImpl.retrieveCauseData(PipelineHookTriggerHandlerImpl.java:128)
	at com.dabsquared.gitlabjenkins.trigger.handler.pipeline.PipelineHookTriggerHandlerImpl.retrieveCauseData(PipelineHookTriggerHandlerImpl.java:32)
	at com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler.createActions(AbstractWebHookTriggerHandler.java:85)
	at com.dabsquared.gitlabjenkins.trigger.handler.pipeline.PipelineHookTriggerHandlerImpl.handle(PipelineHookTriggerHandlerImpl.java:70)
	at com.dabsquared.gitlabjenkins.trigger.handler.pipeline.PipelineHookTriggerHandlerImpl.handle(PipelineHookTriggerHandlerImpl.java:32)
	at com.dabsquared.gitlabjenkins.GitLabPushTrigger.onPost(GitLabPushTrigger.java:481)
	at com.dabsquared.gitlabjenkins.webhook.build.PipelineBuildAction$1.performOnPost(PipelineBuildAction.java:76)
	at com.dabsquared.gitlabjenkins.webhook.build.BuildWebHookAction$TriggerNotifier.run(BuildWebHookAction.java:54)
	at hudson.security.ACL.impersonate(ACL.java:273)
	at com.dabsquared.gitlabjenkins.webhook.build.PipelineBuildAction.execute(PipelineBuildAction.java:73)
	at com.dabsquared.gitlabjenkins.webhook.build.BuildWebHookAction.execute(BuildWebHookAction.java:31)
	at com.dabsquared.gitlabjenkins.webhook.GitLabWebHook.getDynamic(GitLabWebHook.java:44)
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
Caused: java.lang.reflect.InvocationTargetException
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:400)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
	at org.kohsuke.stapler.MetaClass$9.dispatch(MetaClass.java:456)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.MetaClass$9.dispatch(MetaClass.java:458)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:668)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at com.dabsquared.gitlabjenkins.webhook.GitLabWebHook$GitlabWebHookCrumbExclusion.process(GitLabWebHook.java:53)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:73)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:135)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Unknown Source)

```

**Comment by Moln** [comment]
@omehegan 

In PipelineHook , it does not have a `project_id` property.

Need to use `hook.getProject().getId()` instead.

https://github.com/jenkinsci/gitlab-plugin/blob/71b282bf44561971328a64cd91159e4e1a29ce03/src/main/java/com/dabsquared/gitlabjenkins/trigger/handler/pipeline/PipelineHookTriggerHandlerImpl.java#L103

https://github.com/jenkinsci/gitlab-plugin/blob/71b282bf44561971328a64cd91159e4e1a29ce03/src/main/java/com/dabsquared/gitlabjenkins/trigger/handler/pipeline/PipelineHookTriggerHandlerImpl.java#L112

**Comment by omehegan** [comment]
@Moln thanks for looking into this! I don't understand why the same code would work OK in `trigger/handler/push/PushHookTriggerHandlerImpl.java` though. Any idea?

**Comment by Moln** [comment]
@omehegan 

Because `push` event have a key-value `project_id`.

But `pipeline` event does not.

**Comment by junguchina** [comment]
Same issue like this, has anyone to look it?
@omehegan @mreichel 

Gitlab plugin version: 1.5.11
Gitlab version: 11.9.1 (86f0b5dd)
Jenkins version: 2.164.1

With `Build on successful pipeline events` option checked in jenkins, after the pipeline of gitlab successful completed, the logs of jenkins's system like below:
```
Apr 03, 2019 8:20:55 AM com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
INFO: WebHook called with url: /project/Test
Apr 03, 2019 8:20:55 AM com.dabsquared.gitlabjenkins.trigger.handler.pipeline.PipelineHookTriggerHandlerImpl handle
INFO: Test triggered for pipeline event.
Apr 03, 2019 8:20:55 AM org.eclipse.jetty.server.handler.ContextHandler$Context log
WARNING: Error while serving http://jenkins.tt/project/Test
java.lang.reflect.InvocationTargetException
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:400)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
	at org.kohsuke.stapler.MetaClass$9.dispatch(MetaClass.java:456)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.MetaClass$9.dispatch(MetaClass.java:458)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:668)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at com.dabsquared.gitlabjenkins.webhook.GitLabWebHook$GitlabWebHookCrumbExclusion.process(GitLabWebHook.java:53)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:73)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:135)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: sourceProjectId must not be null.
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:204)
	at com.dabsquared.gitlabjenkins.cause.CauseData.<init>(CauseData.java:74)
	at com.dabsquared.gitlabjenkins.cause.CauseDataBuilder.build(CauseDataBuilder.java:632)
	at com.dabsquared.gitlabjenkins.trigger.handler.pipeline.PipelineHookTriggerHandlerImpl.retrieveCauseData(PipelineHookTriggerHandlerImpl.java:128)
	at com.dabsquared.gitlabjenkins.trigger.handler.pipeline.PipelineHookTriggerHandlerImpl.retrieveCauseData(PipelineHookTriggerHandlerImpl.java:32)
	at com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler.createActions(AbstractWebHookTriggerHandler.java:85)
	at com.dabsquared.gitlabjenkins.trigger.handler.pipeline.PipelineHookTriggerHandlerImpl.handle(PipelineHookTriggerHandlerImpl.java:70)
	at com.dabsquared.gitlabjenkins.trigger.handler.pipeline.PipelineHookTriggerHandlerImpl.handle(PipelineHookTriggerHandlerImpl.java:32)
	at com.dabsquared.gitlabjenkins.GitLabPushTrigger.onPost(GitLabPushTrigger.java:481)
	at com.dabsquared.gitlabjenkins.webhook.build.PipelineBuildAction$1.performOnPost(PipelineBuildAction.java:76)
	at com.dabsquared.gitlabjenkins.webhook.build.BuildWebHookAction$TriggerNotifier.run(BuildWebHookAction.java:54)
	at hudson.security.ACL.impersonate(ACL.java:273)
	at com.dabsquared.gitlabjenkins.webhook.build.PipelineBuildAction.execute(PipelineBuildAction.java:73)
	at com.dabsquared.gitlabjenkins.webhook.build.BuildWebHookAction.execute(BuildWebHookAction.java:31)
	at com.dabsquared.gitlabjenkins.webhook.GitLabWebHook.getDynamic(GitLabWebHook.java:44)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
	... 75 more
```
The keyword `sourceProjectId must not be null` .

**Comment by ebenezarisaac** [comment]
Is this issue resolved yet perhaps in a later version of the plugin, if so can anyone provide me that, we are on 1.5.10. 
@omehegan @mreichel anyone?

**Comment by faikabouthalja** [comment]
I'am having this issue with GitLab Plugin 1.5.12 , test with pipeline event returns code 200 but no build is launched on Jenkins and when new pipeline event happens I see return code 200 when pipeline is still running but when it finish on success and is supposed to trigger Jenkins Job I get return code 500 and error seems to be in response body: java.lang.NullPointerException: sourceProjectId must not be null.

**Comment by nwps8716** [comment]
I'am use Gitlab Plugin 1.5.13, it has the same problem.
