### ISSUE TITLE
IndexOutOfBoundsException on force push on target branch

### ISSUE THREAD

**Issue by asirbu2002** [jenkinsci/gitlab-plugin#729]
## Issue
In jenkins I activate plugin on Merge requests and on any push on the source or target branch.

If I do a force-push on target branch, a stacktrace IndexOutOfBoundsException occurs

### Context
- **Gitlab plugin version**: 1.5.3
- **Gitlab version**: 8.3.4
- **Jenkins version**: 1.6.16
- **Job type**: Pipeline, Freestyle, Matrix, etc.

### Logs & Traces
```
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dabsquared.gitlabjenkins.trigger.handler.push.OpenMergeRequestPushHookTriggerHandler.retrieveCauseData(OpenMergeRequestPushHookTriggerHandler.java:149)
	at com.dabsquared.gitlabjenkins.trigger.handler.push.OpenMergeRequestPushHookTriggerHandler.handleMergeRequest(OpenMergeRequestPushHookTriggerHandler.java:118)
	at com.dabsquared.gitlabjenkins.trigger.handler.push.OpenMergeRequestPushHookTriggerHandler.handle(OpenMergeRequestPushHookTriggerHandler.java:69)
	at com.dabsquared.gitlabjenkins.trigger.handler.push.OpenMergeRequestPushHookTriggerHandler.handle(OpenMergeRequestPushHookTriggerHandler.java:45)
	at com.dabsquared.gitlabjenkins.trigger.handler.push.PushHookTriggerHandlerList.handle(PushHookTriggerHandlerList.java:24)
	at com.dabsquared.gitlabjenkins.trigger.handler.push.PushHookTriggerHandlerList.handle(PushHookTriggerHandlerList.java:13)
	at com.dabsquared.gitlabjenkins.GitLabPushTrigger.onPost(GitLabPushTrigger.java:393)
	at com.dabsquared.gitlabjenkins.webhook.build.PushBuildAction$1.performOnPost(PushBuildAction.java:72)
	at com.dabsquared.gitlabjenkins.webhook.build.BuildWebHookAction$TriggerNotifier.run(BuildWebHookAction.java:54)
	at hudson.security.ACL.impersonate(ACL.java:198)
	at com.dabsquared.gitlabjenkins.webhook.build.PushBuildAction.execute(PushBuildAction.java:69)
	at com.dabsquared.gitlabjenkins.webhook.build.BuildWebHookAction.execute(BuildWebHookAction.java:31)
	at com.dabsquared.gitlabjenkins.webhook.GitLabWebHook.getDynamic(GitLabWebHook.java:44)
	... 71 more
```

**Comment by omehegan** [comment]
Can you clarify what version of Jenkins you are using? 1.6.16 is not a valid Jenkins version. Also, do you experience this error when you do a normal, non-forced push?

**Comment by asirbu2002** [comment]
Jenkins version is 1.616 and no, the error doesn't occurs on non-forced push.

**Comment by omehegan** [comment]
@asirbu2002 wow, a 3 year old version of Jenkins? There are a thousand reasons why you should look into upgrading, not the least of which is that your version is vulnerable to tons of published security flaws.

I'll try to reproduce this. It's possible that a force push results in something unusual being sent to Jenkins which throws off the plugin.
