### ISSUE TITLE
Doesn't work with GitLab API v4

### ISSUE THREAD

**Issue by troizky** [jenkinsci/gitlab-plugin#780]
## Issue
API V3 was unsupported from GitLab 9.5, released on August 22, 2017. API v3 was removed in GitLab 11.0. (See here: https://docs.gitlab.com/ce/api/v3_to_v4.html)

### Context
- **Gitlab plugin version**: 1.5.6
- **Gitlab version**: 11.0.0
- **Jenkins version**: 2.107.3
- **Job type**: Freestyle

### Logs & Traces
java.lang.Error: java.io.FileNotFoundException: https://gitlab.com/api/v3/projects
        at org.gitlab.api.http.GitlabHTTPRequestor$1.fetch(GitlabHTTPRequestor.java:239)
        at org.gitlab.api.http.GitlabHTTPRequestor$1.hasNext(GitlabHTTPRequestor.java:193)
        at org.gitlab.api.http.GitlabHTTPRequestor.getAll(GitlabHTTPRequestor.java:161)
        at org.gitlab.api.GitlabAPI.getProjects(GitlabAPI.java:560)
        at org.jenkinsci.plugins.gitlab.GitlabRepository.getProjectForPath(GitlabRepository.java:101)
        at org.jenkinsci.plugins.gitlab.GitlabRepository.checkState(GitlabRepository.java:42)
        at org.jenkinsci.plugins.gitlab.GitlabRepository.init(GitlabRepository.java:33)
        at org.jenkinsci.plugins.gitlab.GitlabMergeRequestBuilder.build(GitlabMergeRequestBuilder.java:60)
        at org.jenkinsci.plugins.gitlab.GitlabBuildTrigger.start(GitlabBuildTrigger.java:64)
        at org.jenkinsci.plugins.gitlab.GitlabBuildTrigger.start(GitlabBuildTrigger.java:23)
        at hudson.model.AbstractProject.onLoad(AbstractProject.java:313)
        at hudson.model.Project.onLoad(Project.java:97)
        at hudson.model.Items.load(Items.java:372)
        at jenkins.model.Jenkins$15.run(Jenkins.java:3125)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1068)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: https://gitlab.com/api/v3/projects
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
        at org.gitlab.api.http.GitlabHTTPRequestor.parse(GitlabHTTPRequestor.java:324)
        at org.gitlab.api.http.GitlabHTTPRequestor.access$200(GitlabHTTPRequestor.java:28)
        at org.gitlab.api.http.GitlabHTTPRequestor$1.fetch(GitlabHTTPRequestor.java:232)
        ... 21 more

### Problem description
GitLab plugins don't detect GitLab API v4.

**Comment by troizky** [comment]
My mistake. It was another plugin.

**Comment by marrrschine** [comment]
@troizky, which one?

**Comment by troizky** [comment]
@marrrschine, this one [org.jenkinsci.plugins.gitlab.GitlabMergeRequestBuilder](https://github.com/timols/jenkins-gitlab-merge-request-builder-plugin)
