### ISSUE TITLE
gitlabCommitStatus

### ISSUE THREAD

**Issue by esquires** [jenkinsci/gitlab-plugin#839]
### Context
- **Gitlab plugin version**: 1.5.8
- **Gitlab version**: GitLab Community Edition 10.8.3
- **Jenkins version**: 2.121.2
- **Job type**: Pipeline

### Logs & Traces

```
Project (350) and commit (10572669f1f4776f9f70a6edbe0966d2533af48c) combination not found

Sep 25, 2018 1:37:05 AM SEVERE com.dabsquared.gitlabjenkins.workflow.AcceptGitLabMergeRequestStep$AcceptGitLabMergeRequestStepExecution run

Failed to accept merge request for project '350'
javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:201)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:50)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.$Proxy90.acceptMergeRequest(Unknown Source)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.ResteasyGitLabClient.acceptMergeRequest(ResteasyGitLabClient.java:75)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$10.execute(AutodetectingGitLabClient.java:148)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$10.execute(AutodetectingGitLabClient.java:145)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.execute(AutodetectingGitLabClient.java:296)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.execute(AutodetectingGitLabClient.java:302)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.access$100(AutodetectingGitLabClient.java:293)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.execute(AutodetectingGitLabClient.java:289)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.acceptMergeRequest(AutodetectingGitLabClient.java:144)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$10.execute(AutodetectingGitLabClient.java:148)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$10.execute(AutodetectingGitLabClient.java:145)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.execute(AutodetectingGitLabClient.java:296)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.execute(AutodetectingGitLabClient.java:302)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.access$100(AutodetectingGitLabClient.java:293)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.execute(AutodetectingGitLabClient.java:289)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.acceptMergeRequest(AutodetectingGitLabClient.java:144)
	at com.dabsquared.gitlabjenkins.workflow.AcceptGitLabMergeRequestStep$AcceptGitLabMergeRequestStepExecution.run(AcceptGitLabMergeRequestStep.java:97)
	at com.dabsquared.gitlabjenkins.workflow.AcceptGitLabMergeRequestStep$AcceptGitLabMergeRequestStepExecution.run(AcceptGitLabMergeRequestStep.java:73)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution.start(AbstractSynchronousStepExecution.java:42)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:229)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:153)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
	at sun.reflect.GeneratedMethodAccessor2352.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:157)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:133)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:155)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:159)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:129)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:57)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:82)
	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
	at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:122)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:261)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$101(SandboxContinuable.java:34)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.lambda$run0$0(SandboxContinuable.java:59)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:58)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:174)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:332)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:83)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:244)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:232)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

### Problem description

I am trying to do a couple things. First, I am trying to show the Jenkins build status in gitlab. The first couple of lines of the pasted log indicate it is failing because it can't find the commit in gitlab although I have verified that this commit exists in the repo in gitlab (it is what triggered the Jenkins build).

Second, I see that the auto merge is failing but I am getting a 404 error. These may be related errors so I included both in this ticket.

This was initiated with a merge request (not from a fork). Can you help me identify where I should look to debug this error? Thanks.

**Comment by omehegan** [comment]
@esquires the exception you are seeing seems to indicate that the commit ID you have does not exist in the repo you are referencing (GitLab project ID 350). This can happen if you are using Pipeline libraries and you put the commit status Pipeline step in the wrong place - the plugin tries to send the status to the library repo instead of your project repo. Can you share your Pipeline code?

**Comment by esquires** [comment]
Certainly. It is below. I only changed the url and the project name in the docker.build step. 

```[groovy]
#!/usr/bin/env groovy

node('docker-host') {
  try {

    // If the gitlabBranch doesn't exist, default to master
    env.defaultBranch = "master"
    if (!env.gitlabBranch) {
      env.gitlabBranch = env.defaultBranch
    }


    if (env.gitlabMergeRequestId) {
      print("JENKINSFILE: Merge request detected. Merging before build.")

      checkout([$class: 'GitSCM',
      branches: [[name: 'origin/${gitlabSourceBranch}']],
      doGenerateSubmoduleConfigurations: false,
      extensions: [[$class: 'CleanCheckout'],
                   [$class: 'SubmoduleOption', disableSubmodules: false, parentCredentials: true, recursiveSubmodules: true, reference: '', trackingSubmodules: false],
                   [$class: 'PreBuildMerge', options: [mergeRemote: 'origin', mergeTarget: '${gitlabTargetBranch}']]],
      submoduleCfg: [],
      userRemoteConfigs: [[credentialsId: 'jenkins_gitlab_key', name: 'origin', refspec: '+refs/heads/*:refs/remotes/origin/* +refs/merge-requests/*/head:refs/remotes/origin/merge-requests/*', url: 'path_to_internal_url.git']]])

    } else {
      def origin_branch = '*/' + env.gitlabBranch
      print('JENKINSFILE: No merge request detected. Checking out: ' + origin_branch)

      checkout([$class: 'GitSCM',
      branches: [[name: origin_branch]],
      doGenerateSubmoduleConfigurations: false,
      extensions: [[$class: 'CleanCheckout']],
      submoduleCfg: [],
      userRemoteConfigs: [[credentialsId: 'jenkins_gitlab_key', url: 'path_to_internal_url.git']]])
    }

    def app_env
    stage ('Build') {
      gitlabCommitStatus("build") {
        docker.withRegistry('http://localhost:5000') {
          app_env = docker.build("localhost:5000/project_name:latest", "--pull -f ci/Dockerfile .")
        }
      }
    }

    stage ('Push Image') {
      gitlabCommitStatus("push image") {
        docker.withRegistry('http://localhost:5000') {
          app_env.push('latest')
        }
      }
    }

    currentBuild.result = "SUCCESS"
    if (env.gitlabMergeRequestId) {
      if (env.gitlabMergeRequestAssignee) {
        String email_lastname = env.gitlabUserEmail.tokenize('@').first().tokenize('.').last()
        print("email_lastname is " + email_lastname)
        print("The merge assignee is " + env.gitlabMergeRequestAssignee)
        if (env.gitlabMergeRequestAssignee.contains(email_lastname)) {
          print('JENKINSFILE: Automatically accepting GitLab merge request.')
          acceptGitLabMR(useMRDescription: true, removeSourceBranch: false)
        } else {
          print('JENKINSFILE: Not automatically merging because requestor does not match merge assignee.')
        }
      } else {
        emailext(body:  'Select an assignee and do a manual merge. ' + '${DEFAULT_CONTENT}',
                 mimeType: 'text/html',
                 attachLog: true,
                 compressLog: true,
                 replyTo: '$DEFAULT_REPLYTO',
                 subject: 'Merge request for ' + env.gitlabSourceBranch + ' passed CI but not merged',
                 to: env.gitlabUserEmail)
      }
    }
  } catch (err) {
    currentBuild.result = 'FAILURE'

    // Send an e-mail to the developers that broke this build
    emailext(body: '${DEFAULT_CONTENT}',
             mimeType: 'text/html',
             attachLog: true,
             compressLog: true,
             replyTo: '$DEFAULT_REPLYTO', subject: '${DEFAULT_SUBJECT}',
             to: emailextrecipients([[$class: 'CulpritsRecipientProvider'],
                                     [$class: 'RequesterRecipientProvider']]))
  } finally {
    if (env.gitlabBranch == env.defaultBranch) {
      step( [$class:                  'Mailer',
             notifyEveryUnstableBuild: true,
             recipients:               'eric.squires@gtri.gatech.edu',
             sendToIndividuals:        true] )
    }
  }
}
```

**Comment by omehegan** [comment]
@esquires Looking at the logs you included in your initial request, are those an exact copy, or are they three different log entries that you pulled? I'm just trying to understand if these are all related to the 'accept merge request' action, or if one of them is related to sending build status.

I have a feeling that the plugin is getting confused about which repo/branch to perform these operations on, but I have never used this feature myself so I am not sure how it should work. @sbrassely or @ptzafrir you have both worked on this code, can you see if this user is doing anything wrong?

**Comment by esquires** [comment]
Hi @omehegan . Thanks for your reply. Those are from the same log. I went ahead and re-ran it with the "finer" setting and am pasting everything that was logged except for substituting some urls. Let me know if you need to see something different.

``0de38465c7d17ec07ff9f7a88978d19f85bb6c3e`` is the commit that triggered the build.

```
Sep 25, 2018 10:31:41 PM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic

WebHook called with url: /project/project_name

Sep 25, 2018 10:31:41 PM FINE com.dabsquared.gitlabjenkins.webhook.build.MergeRequestBuildAction

MergeRequest: {
  "object_kind" : "merge_request",
  "event_type" : "merge_request",
  "user" : {
    "name" : "Squires, Eric G",
    "username" : "esquires3",
    "avatar_url" : "https://secure.gravatar.com/avatar/aed39440fe7eabb0793fbfb8a6583616?s=80&d=identicon"
  },
  "project" : {
    "id" : 350,
    "name" : "project_name",
    "description" : "",
    "web_url" : "https://project_url/project_group/project_name",
    "avatar_url" : null,
    "git_ssh_url" : "ssh://git@project_url:port/project_group/project_name.git",
    "git_http_url" : "https://project_url/project_group/project_name.git",
    "namespace" : "project_name",
    "visibility_level" : 0,
    "path_with_namespace" : "project_group/project_name",
    "default_branch" : "master",
    "ci_config_path" : null,
    "homepage" : "https://project_url/project_group/project_name",
    "url" : "ssh://git@project_url:port/project_group/project_name.git",
    "ssh_url" : "ssh://git@project_url:port/project_group/project_name.git",
    "http_url" : "https://project_url/project_group/project_name.git"
  },
  "object_attributes" : {
    "assignee_id" : 8,
    "author_id" : 8,
    "created_at" : "2018-09-22 17:43:36 UTC",
    "description" : "",
    "head_pipeline_id" : null,
    "id" : 284,
    "iid" : 22,
    "last_edited_at" : null,
    "last_edited_by_id" : null,
    "merge_commit_sha" : null,
    "merge_error" : null,
    "merge_params" : {
      "force_remove_source_branch" : "0"
    },
    "merge_status" : "unchecked",
    "merge_user_id" : null,
    "merge_when_pipeline_succeeds" : false,
    "milestone_id" : null,
    "source_branch" : "email",
    "source_project_id" : 350,
    "state" : "opened",
    "target_branch" : "master",
    "target_project_id" : 350,
    "time_estimate" : 0,
    "title" : "foo",
    "updated_at" : "2018-09-25 22:31:37 UTC",
    "updated_by_id" : 8,
    "url" : "https://project_url/project_group/project_name/merge_requests/22",
    "source" : {
      "id" : 350,
      "name" : "project_name",
      "description" : "",
      "web_url" : "https://project_url/project_group/project_name",
      "avatar_url" : null,
      "git_ssh_url" : "ssh://git@project_url:port/project_group/project_name.git",
      "git_http_url" : "https://project_url/project_group/project_name.git",
      "namespace" : "project_name",
      "visibility_level" : 0,
      "path_with_namespace" : "project_group/project_name",
      "default_branch" : "master",
      "ci_config_path" : null,
      "homepage" : "https://project_url/project_group/project_name",
      "url" : "ssh://git@project_url:port/project_group/project_name.git",
      "ssh_url" : "ssh://git@project_url:port/project_group/project_name.git",
      "http_url" : "https://project_url/project_group/project_name.git"
    },
    "target" : {
      "id" : 350,
      "name" : "project_name",
      "description" : "",
      "web_url" : "https://project_url/project_group/project_name",
      "avatar_url" : null,
      "git_ssh_url" : "ssh://git@project_url:port/project_group/project_name.git",
      "git_http_url" : "https://project_url/project_group/project_name.git",
      "namespace" : "project_name",
      "visibility_level" : 0,
      "path_with_namespace" : "project_group/project_name",
      "default_branch" : "master",
      "ci_config_path" : null,
      "homepage" : "https://project_url/project_group/project_name",
      "url" : "ssh://git@project_url:port/project_group/project_name.git",
      "ssh_url" : "ssh://git@project_url:port/project_group/project_name.git",
      "http_url" : "https://project_url/project_group/project_name.git"
    },
    "last_commit" : {
      "id" : "0de38465c7d17ec07ff9f7a88978d19f85bb6c3e",
      "message" : "trivial commit\n",
      "timestamp" : "2018-09-25T18:31:38-04:00",
      "url" : "https://project_url/project_group/project_name/commit/0de38465c7d17ec07ff9f7a88978d19f85bb6c3e",
      "author" : {
        "name" : "Eric Squires",
        "email" : "eric.squires@gtri.gatech.edu"
      }
    },
    "work_in_progress" : false,
    "total_time_spent" : 0,
    "human_total_time_spent" : null,
    "human_time_estimate" : null,
    "action" : "update",
    "oldrev" : "ef288a2e062d655e86c9e0a0d1bba9852f49b802"
  },
  "labels" : [ ],
  "changes" : {
    "assignee" : {
      "previous" : null,
      "current" : {
        "name" : "Squires, Eric G",
        "username" : "esquires3",
        "avatar_url" : "https://secure.gravatar.com/avatar/aed39440fe7eabb0793fbfb8a6583616?s=80&d=identicon"
      }
    },
    "total_time_spent" : {
      "previous" : null,
      "current" : 0
    }
  },
  "repository" : {
    "name" : "project_name",
    "url" : "ssh://git@project_url:port/project_group/project_name.git",
    "description" : "",
    "homepage" : "https://project_url/project_group/project_name"
  },
  "assignee" : {
    "name" : "Squires, Eric G",
    "username" : "esquires3",
    "avatar_url" : "https://secure.gravatar.com/avatar/aed39440fe7eabb0793fbfb8a6583616?s=80&d=identicon"
  }
}

Sep 25, 2018 10:31:41 PM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle

project_name triggered for merge request.

Sep 25, 2018 10:31:48 PM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds

Retrieving gitlab project ids

Sep 25, 2018 10:31:49 PM FINE com.dabsquared.gitlabjenkins.util.CommitStatusUpdater

Project (350) and commit (0de38465c7d17ec07ff9f7a88978d19f85bb6c3e) combination not found

Sep 25, 2018 10:33:11 PM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds

Retrieving gitlab project ids

Sep 25, 2018 10:33:12 PM FINE com.dabsquared.gitlabjenkins.util.CommitStatusUpdater

Project (350) and commit (0de38465c7d17ec07ff9f7a88978d19f85bb6c3e) combination not found

Sep 25, 2018 10:33:12 PM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds

Retrieving gitlab project ids

Sep 25, 2018 10:33:13 PM FINE com.dabsquared.gitlabjenkins.util.CommitStatusUpdater

Project (350) and commit (0de38465c7d17ec07ff9f7a88978d19f85bb6c3e) combination not found

Sep 25, 2018 10:38:03 PM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds

Retrieving gitlab project ids

Sep 25, 2018 10:38:04 PM FINE com.dabsquared.gitlabjenkins.util.CommitStatusUpdater

Project (350) and commit (0de38465c7d17ec07ff9f7a88978d19f85bb6c3e) combination not found

Sep 25, 2018 10:38:05 PM SEVERE com.dabsquared.gitlabjenkins.workflow.AcceptGitLabMergeRequestStep$AcceptGitLabMergeRequestStepExecution run

Failed to accept merge request for project '350'
javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:201)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:50)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.$Proxy90.acceptMergeRequest(Unknown Source)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.ResteasyGitLabClient.acceptMergeRequest(ResteasyGitLabClient.java:75)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$10.execute(AutodetectingGitLabClient.java:148)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$10.execute(AutodetectingGitLabClient.java:145)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.execute(AutodetectingGitLabClient.java:296)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.execute(AutodetectingGitLabClient.java:302)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.access$100(AutodetectingGitLabClient.java:293)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.execute(AutodetectingGitLabClient.java:289)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.acceptMergeRequest(AutodetectingGitLabClient.java:144)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$10.execute(AutodetectingGitLabClient.java:148)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$10.execute(AutodetectingGitLabClient.java:145)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.execute(AutodetectingGitLabClient.java:296)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.execute(AutodetectingGitLabClient.java:302)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.access$100(AutodetectingGitLabClient.java:293)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.execute(AutodetectingGitLabClient.java:289)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.acceptMergeRequest(AutodetectingGitLabClient.java:144)
	at com.dabsquared.gitlabjenkins.workflow.AcceptGitLabMergeRequestStep$AcceptGitLabMergeRequestStepExecution.run(AcceptGitLabMergeRequestStep.java:97)
	at com.dabsquared.gitlabjenkins.workflow.AcceptGitLabMergeRequestStep$AcceptGitLabMergeRequestStepExecution.run(AcceptGitLabMergeRequestStep.java:73)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution.start(AbstractSynchronousStepExecution.java:42)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:229)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:153)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
	at sun.reflect.GeneratedMethodAccessor2352.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:157)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:133)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:155)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:159)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:129)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:57)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:82)
	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
	at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:122)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:261)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$101(SandboxContinuable.java:34)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.lambda$run0$0(SandboxContinuable.java:59)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:58)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:174)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:332)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:83)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:244)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:232)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by ptzafrir** [comment]
I can reproduce the issue by accessing gitlab with user with no permissions for the specific project.
gitlab API return status 404 in this case.

@esquires Can you confirm that this address works for you
https://project_url/api/v4/projects/350/repository/commits/0de38465c7d17ec07ff9f7a88978d19f85bb6c3e
And then try to access it when logged in as the same user configured in Jenkins global configuration under Gitlab Connection?

**Comment by esquires** [comment]
It looks like I can see the project from jenkins and from my user. Here is the output from the jenkins user.

```
{"id":"0de38465c7d17ec07ff9f7a88978d19f85bb6c3e","short_id":"0de38465","title":"trivial commit","created_at":"2018-09-25T18:31:38.000-04:00","parent_ids":["ef288a2e062d655e86c9e0a0d1bba9852f49b802"],"message":"trivial commit\n","author_name":"Eric Squires","author_email":"eric.squires@gtri.gatech.edu","authored_date":"2018-09-25T18:31:38.000-04:00","committer_name":"Eric Squires","committer_email":"eric.squires@gtri.gatech.edu","committed_date":"2018-09-25T18:31:38.000-04:00","stats":{"additions":0,"deletions":1,"total":1},"status":null,"last_pipeline":null,"project_id":350}
```

**Comment by omehegan** [comment]
@ptzafrir any further comment on this?

**Comment by ptzafrir** [comment]
I'm sorry, but I have no additional ideas as to the cause of this.

**Comment by esquires** [comment]
Thanks for the follow-up. I never was able to figure out what the problem was. The gitlab status and automerge aren't critical for my application so I have gotten along ok without it. I'll go ahead and close this ticket.
