### ISSUE TITLE
cannot update gitlab git gitcommitStatus

### ISSUE THREAD

**Issue by gezn** [jenkinsci/gitlab-plugin#853]
## Issue
I set up jenkins and gitlab, I prepared everything but when I try to commit  status message to gitlab it fails. stating the the host is null, but it doesn't say anything on the docs about having to set up the host back, or were I can get this information from.

the code that I am using:
```

node () {
  def commitHash;
  def output;
  stage ('scm') {
    def scmVars = checkout(scm)
    commitHash = scmVars.GIT_COMMIT
  }
  stage('clean environment') {
    gitlabCommitStatus {
      sh 'rm -rf platforms'
      sh 'rm -rf node_modules'
    }
  }
....
```
the code above works well and builds successfully but throws the error trying to notify gitlab back
### Context
- **Gitlab plugin version**: 1.5.10
- **Gitlab version**: 11.3.4 30f019d comunity edition
- **Jenkins version**: 2.138.2
- **Job type**: Pipeline, 

### Logs & Traces

Retrieving gitlab project ids

Oct 31, 2018 4:18:38 PM SEVERE com.dabsquared.gitlabjenkins.util.CommitStatusUpdater updateCommitStatus

Failed to update Gitlab commit status for project '163'
java.lang.IllegalStateException: Target host is null
	at org.apache.http.util.Asserts.notNull(Asserts.java:52)
	at org.apache.http.impl.conn.DefaultHttpRoutePlanner.determineRoute(DefaultHttpRoutePlanner.java:100)
	at org.apache.http.impl.client.DefaultRequestDirector.determineRoute(DefaultRequestDirector.java:761)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:380)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:283)
Caused: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:287)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:436)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:102)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.$Proxy97.getCurrentUser(Unknown Source)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.ResteasyGitLabClient.getCurrentUser(ResteasyGitLabClient.java:115)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.autodetect(AutodetectingGitLabClient.java:317)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.autodetectOrDie(AutodetectingGitLabClient.java:305)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.delegate(AutodetectingGitLabClient.java:298)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.access$200(AutodetectingGitLabClient.java:14)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.execute(AutodetectingGitLabClient.java:335)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.access$100(AutodetectingGitLabClient.java:332)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.execute(AutodetectingGitLabClient.java:328)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.getCommit(AutodetectingGitLabClient.java:132)
	at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.existsCommit(CommitStatusUpdater.java:121)
	at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.updateCommitStatus(CommitStatusUpdater.java:83)
	at com.dabsquared.gitlabjenkins.workflow.GitLabCommitStatusStep$GitLabCommitStatusStepExecution$1.onStart(GitLabCommitStatusStep.java:104)
	at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution.launch(CpsBodyExecution.java:126)
	at org.jenkinsci.plugins.workflow.cps.CpsBodyInvoker.launch(CpsBodyInvoker.java:170)
	at org.jenkinsci.plugins.workflow.cps.DSL$ThreadTaskImpl.invokeBody(DSL.java:656)
	at org.jenkinsci.plugins.workflow.cps.DSL$ThreadTaskImpl.eval(DSL.java:623)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:192)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:332)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:83)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:244)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:232)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### Problem description

_Describe your problem in a meaningful way_:
When my code above runs, that is marked to be triggered only on merge requests, and push's to merge requests branchs. it just fails to update  the status back to gitlab.
it was expected that it just commit the status message to gitlab, as per the documentation state
it builds but it is not updating gitlab.

**Comment by omehegan** [comment]
@gezn have you set up a connection from Jenkins to GitLab, per https://github.com/jenkinsci/gitlab-plugin#jenkins-to-gitlab-authentication? If not, you need to do that.

**Comment by gezn** [comment]
@omehegan  thanks sorry for not updating on this. it was an issue about http:// or http:// not added to an ip url address, that I forgot to add manually. sorry for the inconveniences
