### ISSUE TITLE
Update GitLab Pipeline status when Jenkinsfile have wrong syntax

### ISSUE THREAD

**Issue by Zava2012** [jenkinsci/gitlab-plugin#855]
### Context
- **Gitlab plugin version**: 1.5.10
- **Gitlab version**: 11.4.5
- **Jenkins version**: 2.138.2 LTS
- **Job type**: Pipeline

### Problem description

After build is running on Jenkins (GitLab status is pending) and Jenkinsfile contain some mistakes, GitLab stucking this pipeline in pending status, but Jenkins Build is failed.
For example, i have this Jenkinsfile:
```
pipeline {
    agent {
        label 'Android'
    }

    options {
        timestamps()
        buildDiscarder logRotator(daysToKeepStr: '180')
        gitLabConnection 'jenkins'
        gitlabCommitStatus(name: 'Jenkins')
        gitlabBuilds(builds: ['Prebuild Actions', 'Gradle Build', 'Tests', 'Artifact Sync'])
        skipDefaultCheckout true
    }

    environment {
        PROJECT_NAME        = "TEST"
        BUILD_TYPE          = "debug"
        APK_PATH_JENKINS    = "${WORKSPACE}/app/build/outputs/apk/${BUILD_TYPE}/*.apk"
    }

    triggers {
        gitlab(
            triggerOnPush: false,
            triggerOnMergeRequest: true, 
            triggerOpenMergeRequestOnPush: "source",
            skipWorkInProgressMergeRequest: true,
            ciSkip: true,
            setBuildDescription: true,
            addNoteOnMergeRequest: true,
            addCiMessage: true,
            addVoteOnMergeRequest: true,
            acceptMergeRequestOnSuccess: false,
            branchFilterType: "NameBasedFilter",
            includeBranchesSpec: "dev, test, master",
            excludeBranchesSpec: "",
            pendingBuildName: "Jenkins",
            cancelPendingBuildsOnUpdate: true
        )
    }
    
    stages {
        stage('Prebuild Actions') {
            steps {
                gitlabCommitStatus(name: 'Prebuild Actions') {
                    deleteDir()
                    checkout scm
                    sh '''
                    // some script
                    '''
                }
            }
        }
        stage('Gradle Build') {
            steps {
                gitlabCommitStatus(name: 'Gradle Build') {
                    sh '''
                    // some script
                    '''
                }
            }
        }

        stage('Tests') {
            steps {
                gitlabCommitStatus(name: 'Tests') {
                    sh '''
                    // some script
                    '''
                }
            }
        }
        stage('Code Review') {
            parallel {
                stage('First Review') {
                    steps {
                        gitlabCommitStatus(name: 'First Review') {
                            input(
                                message: 'First Review Success?',
                                ok: 'Yes'
                            )
                        }
                    }
                }
                stage('Second Review') {
                    steps {
                        gitlabCommitStatus(name: 'Second Review') {
                            input {
                                message: 'Second Review Success?',
                                ok: 'Yes'
                            }
                        }
                    }
                }
            }
        }
        stage('Artifact Sync') {
            steps {
                gitlabCommitStatus(name: 'Artifact Sync') {
                    sh '''
                    // some script
                    '''
                }
            }
        }
    }
    post {
        failure {
            emailext(
                recipientProviders: [culprits()],
                subject: '$DEFAULT_SUBJECT',
                body: '$DEFAULT_CONTENT',
                mimeType: 'text/plain',
                attachmentsPattern: '**/*.html',
                attachLog: true
            )
            slackSend(
               ...
            )
            updateGitlabCommitStatus(name: 'Jenkins', state: 'failed')
        }

        aborted {
            slackSend(
                ...
            )
            updateGitlabCommitStatus(name: 'Jenkins', state: 'canceled')
        }

        success {
            archiveArtifacts(artifacts: '**/*.apk')

            emailext(
                recipientProviders: [culprits()],
                subject: '$DEFAULT_SUBJECT',
                body: '$DEFAULT_CONTENT',
                mimeType: 'text/plain',
                attachmentsPattern: '**/*.html',
                attachLog: false
            )

            slackSend(
                ...
            )
            updateGitlabCommitStatus(name: 'Jenkins', state: 'success')
        }
    }
}
```

Because i have wrong syntax, build failed. This is pipeline failed log:
```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 94: unexpected token: Second Review Success? @ line 94, column 42.
                        message: 'Second Re
                                 ^
1 error
	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollector.java:150)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:120)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:132)
	at org.codehaus.groovy.control.SourceUnit.addError(SourceUnit.java:350)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.transformCSTIntoAST(AntlrParserPlugin.java:144)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.parseCST(AntlrParserPlugin.java:110)
	at org.codehaus.groovy.control.SourceUnit.parse(SourceUnit.java:234)
	at org.codehaus.groovy.control.CompilationUnit$1.call(CompilationUnit.java:168)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:943)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:605)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:131)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:125)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:560)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:521)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:320)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
```

But GitLab Pipeline status is pending:
![screenshot from 2018-11-12 14-14-19](https://user-images.githubusercontent.com/10694679/48344152-566fb380-e685-11e8-880d-c0be0280989d.png)

It's a bug or I'm doing something wrong?

Thank You!

And in addition to this issue, **cancelPendingBuildsOnUpdate** option is not working. 
When i running new build, previous pipeline in pending status is not canceled in GitLab.

**Comment by omehegan** [comment]
@Zava2012 seems like a GitLab issue. I can imagine that the status is broken because the Jenkins job died and so no update was sent. 

`cancelPendingBuildsOnUpdate` is for canceling running Jenkins builds when a new commit is made to an open MR. It does not affect anything on the GitLab side.
