### ISSUE TITLE
NullPointerException when checking out non-default branch

### ISSUE THREAD

**Issue by edwinvanderham** [jenkinsci/gitlab-plugin#858]
### Context
- **Gitlab plugin version**: 1.5.11
- **Gitlab version**: 11.1.4
- **Jenkins version**: 2.147
- **Job type**: Freestyle

### Problem description

I am checking out a non-default branch from gitlab (branch specifier */somebranch). Using version 1.5.10 of the gitlab plugin, this works fine, after upgrading to 1.5.11 I get the following stack trace:

```
 > /bin/git rev-list --no-walk 21aa2388a211bd837d5f8791070dd704269a32f6 # timeout=10
FATAL: java.lang.NullPointerException
java.lang.NullPointerException
	at org.jboss.resteasy.plugins.providers.RegisterBuiltin.registerProviders(RegisterBuiltin.java:41)
	at org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:29)
Caused: java.lang.RuntimeException
	at org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:33)
	at org.jboss.resteasy.client.jaxrs.ResteasyClientBuilder.getProviderFactory(ResteasyClientBuilder.java:339)
	at org.jboss.resteasy.client.jaxrs.ResteasyClientBuilder.register(ResteasyClientBuilder.java:541)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.ResteasyGitLabClientBuilder.buildClient(ResteasyGitLabClientBuilder.java:116)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.ResteasyGitLabClientBuilder.buildClient(ResteasyGitLabClientBuilder.java:81)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.autodetect(AutodetectingGitLabClient.java:315)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.autodetectOrDie(AutodetectingGitLabClient.java:305)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.delegate(AutodetectingGitLabClient.java:298)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.access$200(AutodetectingGitLabClient.java:14)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.execute(AutodetectingGitLabClient.java:335)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.execute(AutodetectingGitLabClient.java:341)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.access$100(AutodetectingGitLabClient.java:332)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.execute(AutodetectingGitLabClient.java:328)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.getCommit(AutodetectingGitLabClient.java:132)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$9.execute(AutodetectingGitLabClient.java:136)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$9.execute(AutodetectingGitLabClient.java:133)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.execute(AutodetectingGitLabClient.java:335)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.access$100(AutodetectingGitLabClient.java:332)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.execute(AutodetectingGitLabClient.java:328)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.getCommit(AutodetectingGitLabClient.java:132)
	at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.existsCommit(CommitStatusUpdater.java:121)
	at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.updateCommitStatus(CommitStatusUpdater.java:83)
	at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.updateCommitStatus(CommitStatusUpdater.java:97)
	at com.dabsquared.gitlabjenkins.publisher.GitLabCommitStatusPublisher.prebuild(GitLabCommitStatusPublisher.java:45)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:798)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:793)
	at hudson.model.Build$BuildExecution.doRun(Build.java:145)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1810)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```

**Comment by omehegan** [comment]
@edwinvanderham have you confirmed that downgrading to 1.5.10 fixed this for you? The diff between .10 and .11 was minimal and I don't see that anything was touched which would cause the issue you are seeing.

**Comment by mus65** [comment]
We hit this particular NullPointerException randomly, about every few hundred build (meaning every few weeks). I haven't seen a particular pattern yet. I don't think it's related to the branch, I've seen this on master and other branches. When triggering the same build again manually, it works again.

### Context
- **Gitlab plugin version**: 1.5.13
- **Gitlab version**: 12.9.2
- **Jenkins version**: 222.1
- **Job type**: Multibranch-Pipeline

```
[2020-04-08T05:44:15.475Z] java.lang.RuntimeException: java.lang.NullPointerException
[2020-04-08T05:44:15.475Z] 	at org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:33)
[2020-04-08T05:44:15.475Z] 	at org.jboss.resteasy.client.jaxrs.ResteasyClientBuilder.getProviderFactory(ResteasyClientBuilder.java:339)
[2020-04-08T05:44:15.475Z] 	at org.jboss.resteasy.client.jaxrs.ResteasyClientBuilder.register(ResteasyClientBuilder.java:541)
[2020-04-08T05:44:15.475Z] 	at com.dabsquared.gitlabjenkins.gitlab.api.impl.ResteasyGitLabClientBuilder.buildClient(ResteasyGitLabClientBuilder.java:116)
[2020-04-08T05:44:15.475Z] 	at com.dabsquared.gitlabjenkins.gitlab.api.impl.ResteasyGitLabClientBuilder.buildClient(ResteasyGitLabClientBuilder.java:81)
[2020-04-08T05:44:15.475Z] 	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.autodetect(AutodetectingGitLabClient.java:315)
[2020-04-08T05:44:15.475Z] 	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.autodetectOrDie(AutodetectingGitLabClient.java:305)
[2020-04-08T05:44:15.475Z] 	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.delegate(AutodetectingGitLabClient.java:298)
[2020-04-08T05:44:15.475Z] 	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.access$200(AutodetectingGitLabClient.java:14)
[2020-04-08T05:44:15.475Z] 	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.execute(AutodetectingGitLabClient.java:335)
[2020-04-08T05:44:15.475Z] 	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.access$100(AutodetectingGitLabClient.java:332)
[2020-04-08T05:44:15.475Z] 	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.execute(AutodetectingGitLabClient.java:328)
[2020-04-08T05:44:15.475Z] 	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.getCurrentUser(AutodetectingGitLabClient.java:242)
[2020-04-08T05:44:15.475Z] 	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.autodetect(AutodetectingGitLabClient.java:317)
[2020-04-08T05:44:15.475Z] 	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.autodetectOrDie(AutodetectingGitLabClient.java:305)
[2020-04-08T05:44:15.475Z] 	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.delegate(AutodetectingGitLabClient.java:298)
[2020-04-08T05:44:15.475Z] 	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.access$200(AutodetectingGitLabClient.java:14)
[2020-04-08T05:44:15.475Z] 	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.execute(AutodetectingGitLabClient.java:335)
[2020-04-08T05:44:15.475Z] 	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.access$100(AutodetectingGitLabClient.java:332)
[2020-04-08T05:44:15.475Z] 	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.execute(AutodetectingGitLabClient.java:328)
[2020-04-08T05:44:15.475Z] 	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.getCommit(AutodetectingGitLabClient.java:132)
[2020-04-08T05:44:15.475Z] 	at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.existsCommit(CommitStatusUpdater.java:121)
[2020-04-08T05:44:15.475Z] 	at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.updateCommitStatus(CommitStatusUpdater.java:83)
[2020-04-08T05:44:15.475Z] 	at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.updateCommitStatus(CommitStatusUpdater.java:97)
[2020-04-08T05:44:15.475Z] 	at com.dabsquared.gitlabjenkins.workflow.UpdateGitLabCommitStatusStep$UpdateGitLabCommitStatusStepExecution.run(UpdateGitLabCommitStatusStep.java:79)
[2020-04-08T05:44:15.475Z] 	at com.dabsquared.gitlabjenkins.workflow.UpdateGitLabCommitStatusStep$UpdateGitLabCommitStatusStepExecution.run(UpdateGitLabCommitStatusStep.java:63)
[2020-04-08T05:44:15.475Z] 	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution.start(AbstractSynchronousStepExecution.java:42)
[2020-04-08T05:44:15.475Z] 	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:286)
[2020-04-08T05:44:15.475Z] 	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:179)
[2020-04-08T05:44:15.475Z] 	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
[2020-04-08T05:44:15.475Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-04-08T05:44:15.475Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-04-08T05:44:15.475Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-04-08T05:44:15.475Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2020-04-08T05:44:15.475Z] 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
[2020-04-08T05:44:15.475Z] 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
[2020-04-08T05:44:15.475Z] 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
[2020-04-08T05:44:15.475Z] 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
[2020-04-08T05:44:15.475Z] 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
[2020-04-08T05:44:15.476Z] 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
[2020-04-08T05:44:15.476Z] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
[2020-04-08T05:44:15.476Z] 	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:163)
[2020-04-08T05:44:15.476Z] 	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
[2020-04-08T05:44:15.476Z] 	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:157)
[2020-04-08T05:44:15.476Z] 	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:161)
[2020-04-08T05:44:15.476Z] 	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:165)
[2020-04-08T05:44:15.476Z] 	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:135)
[2020-04-08T05:44:15.476Z] 	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
[2020-04-08T05:44:15.476Z] 	at WorkflowScript.run(WorkflowScript:226)
[2020-04-08T05:44:15.476Z] 	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.delegateAndExecute(ModelInterpreter.groovy:137)
[2020-04-08T05:44:15.476Z] 	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.runPostConditions(ModelInterpreter.groovy:756)
[2020-04-08T05:44:15.476Z] 	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.catchRequiredContextForNode(ModelInterpreter.groovy:395)
[2020-04-08T05:44:15.476Z] 	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.catchRequiredContextForNode(ModelInterpreter.groovy:393)
[2020-04-08T05:44:15.476Z] 	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.runPostConditions(ModelInterpreter.groovy:755)
[2020-04-08T05:44:15.476Z] 	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2030)
[2020-04-08T05:44:15.476Z] 	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2015)
[2020-04-08T05:44:15.476Z] 	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2056)
[2020-04-08T05:44:15.476Z] 	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.runPostConditions(ModelInterpreter.groovy:745)
[2020-04-08T05:44:15.476Z] 	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.runPostConditions(ModelInterpreter.groovy)
[2020-04-08T05:44:15.476Z] 	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.executePostBuild(ModelInterpreter.groovy:723)
[2020-04-08T05:44:15.476Z] 	at ___cps.transform___(Native Method)
[2020-04-08T05:44:15.476Z] 	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
[2020-04-08T05:44:15.476Z] 	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
[2020-04-08T05:44:15.476Z] 	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
[2020-04-08T05:44:15.476Z] 	at sun.reflect.GeneratedMethodAccessor125.invoke(Unknown Source)
[2020-04-08T05:44:15.476Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-04-08T05:44:15.476Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2020-04-08T05:44:15.476Z] 	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
[2020-04-08T05:44:15.476Z] 	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
[2020-04-08T05:44:15.476Z] 	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
[2020-04-08T05:44:15.476Z] 	at sun.reflect.GeneratedMethodAccessor128.invoke(Unknown Source)
[2020-04-08T05:44:15.476Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-04-08T05:44:15.476Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2020-04-08T05:44:15.476Z] 	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
[2020-04-08T05:44:15.476Z] 	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
[2020-04-08T05:44:15.476Z] 	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
[2020-04-08T05:44:15.476Z] 	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
[2020-04-08T05:44:15.476Z] 	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
[2020-04-08T05:44:15.476Z] 	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
[2020-04-08T05:44:15.476Z] 	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
[2020-04-08T05:44:15.476Z] 	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
[2020-04-08T05:44:15.476Z] 	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
[2020-04-08T05:44:15.476Z] 	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
[2020-04-08T05:44:15.476Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
[2020-04-08T05:44:15.476Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
[2020-04-08T05:44:15.476Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
[2020-04-08T05:44:15.476Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
[2020-04-08T05:44:15.476Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
[2020-04-08T05:44:15.476Z] 	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
[2020-04-08T05:44:15.476Z] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2020-04-08T05:44:15.476Z] 	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
[2020-04-08T05:44:15.476Z] 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
[2020-04-08T05:44:15.476Z] 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
[2020-04-08T05:44:15.476Z] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2020-04-08T05:44:15.476Z] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2020-04-08T05:44:15.476Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2020-04-08T05:44:15.476Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2020-04-08T05:44:15.476Z] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mat1e** [comment]
@mus65, I got the same issue. It's append randomly like you describe. Did you find a solution?

### Context

**- Gitlab plugin version:** 1.5.13
**- Gitlab version:** 12.7.6
**- Jenkins version:** 2.204.2
**- Job type:** Multibranch-Pipeline

**Comment by clementckw** [comment]
Can this be reopened or should we file a new ticket?

Similar to @mus65 and @mat1e , we also got hit by this issues every once in a while. The only difference is it is only reproducible in one of our maven build projects, while our other pipeline jobs have never reproduced the same.

We are not able to find any concrete pattern. System health (Jenkins, GitLab) is looking fine when issue is found, as other jobs are running fine.

- Gitlab plugin version: 1.5.17 (built and install manually)
- Gitlab version: 12.3.5
- Jenkins version: 2.222.3
- Job type: Maven project

**Comment by markjacksonfishing** [comment]
@clementckw Kindly open a new issue
