### ISSUE TITLE
Null Pointer Error during Multibranch Pipeline Build

### ISSUE THREAD

**Issue by Olipro** [jenkinsci/gitlab-plugin#895]
## Issue

While building a Pipeline build, the job suddenly failed with an NPE (pasted below)

### Context
- **Gitlab plugin version**: 1.5.11
- **Gitlab version**: 10.8.4
- **Jenkins version**: 2.150.1
- **Job type**: Multibranch Pipeline

### Logs & Traces

java.lang.NullPointerException
	at com.dabsquared.gitlabjenkins.workflow.GitLabCommitStatusStep.access$400(GitLabCommitStatusStep.java:34)
	at com.dabsquared.gitlabjenkins.workflow.GitLabCommitStatusStep$GitLabCommitStatusStepExecution$1.onSuccess(GitLabCommitStatusStep.java:103)
	at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$SuccessAdapter.receive(CpsBodyExecution.java:368)
	at com.cloudbees.groovy.cps.Block$Noop.eval(Block.java:30)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$101(SandboxContinuable.java:34)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.lambda$run0$0(SandboxContinuable.java:59)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:58)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:182)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:332)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:83)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:244)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:232)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### Problem description

The pipeline script consists of a number of stages with `gitlabCommitStatus()` calls inside `option {}` blocks - my suspicion is that this NPE occurred when exiting a stage, or possibly when entering it.

**Comment by geraintwhite** [comment]
I'm getting a related problem, but it only happens after a successful pipeline has finished:

```
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] End of Pipeline
java.lang.NullPointerException
	at com.dabsquared.gitlabjenkins.workflow.GitLabBuildsStep$GitLabBuildStepExecution$1.onSuccess(GitLabBuildsStep.java:92)
	at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$SuccessAdapter.receive(CpsBodyExecution.java:377)
	at com.cloudbees.groovy.cps.Outcome.resumeFrom(Outcome.java:73)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:166)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:405)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:317)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:281)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```


I set the GitLab connection in the properties block:

```
properties([
    disableConcurrentBuilds(),
    gitLabConnection('VE Redside Gitlab'),
    buildDiscarder(logRotator(artifactNumToKeepStr: '1'))
])
```


And declare the pipeline stages around the node block:

```
gitlabBuilds(builds: ['Configure', 'Test', 'Package', 'Deploy', 'Report']) {
  node('Mac_Mini') {
    catchError {
```	



What's interesting is that this NPE has only just started happening without any config change.

**Comment by dalvizu** [comment]
Lookslike this might be fixed in 1.5.17?

https://github.com/jenkinsci/gitlab-plugin/commit/29e4d34d1c5c94c541eb71d3e969d756edf8f90a

**Comment by rsaba5612** [comment]
It seems that the NPE occurred in the GitLab plugin during the execution of a GitLabCommitStatusStep. This may be related to an issue with the plugin version you are using or a compatibility issue with the Jenkins version you are using.

To troubleshoot this issue, you can try the following steps:

Check the GitLab plugin version you are using and compare it with the latest version available. If you are using an older version, try upgrading to the latest version.

Check if the Jenkins version you are using is compatible with the GitLab plugin version you are using. You can check the plugin documentation for compatibility information.

Check if there are any environment changes or updates that could have caused this issue. Check if there are any recent changes in the GitLab repository that could have caused this issue.

Check the pipeline script for any syntax errors or issues with the option blocks containing gitlabCommitStatus() calls. You can try removing the option blocks and see if the issue persists.

If the issue persists, you can try reproducing the issue in a test environment and share the pipeline script and logs for further analysis.

**Comment by krisstern** [comment]
I think the bug has already been patched recently about 2 months ago: https://github.com/jenkinsci/gitlab-plugin/blob/c520cad14e6ac4132ebd24c4a4a4a5040fd9839c/src/main/java/com/dabsquared/gitlabjenkins/workflow/GitLabCommitStatusStep.java#L106
