### ISSUE TITLE
Connection uses api v3 instead of v4

### ISSUE THREAD

**Issue by unix0r** [jenkinsci/gitlab-plugin#960]
Tried to create a new gitlab Organization folder, so all projects of a group with a Jenkinsfile should be integrated into jenkins with all their branches.
Created a new Gitlab Connection to our server, that should use API Level v4, but the requests to the server still are using v3 API that throws an error.

### Context
- **Gitlab plugin version**: 1.5.12
- **Gitlab version**: 12.0.2
- **Jenkins version**: 2.164.3
- **Job type**: Organization Folder

### Logs & Traces

> Aug 07, 2019 8:40:30 AM INFO jenkins.branch.OrganizationFolder$OrganizationScan run
> 
> server-pipeline #20190807.084030 organization scan action completed: NOT_BUILT in 93 ms
> 
> Aug 07, 2019 8:40:30 AM SEVERE hudson.model.Executor finish1
> 
> Executor threw an exception
> java.io.FileNotFoundException: https://git.xxx/api/v3/groups/backend/projects
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
> 	at org.gitlab.api.http.GitlabHTTPRequestor.parse(GitlabHTTPRequestor.java:327)
> 	at org.gitlab.api.http.GitlabHTTPRequestor.access$200(GitlabHTTPRequestor.java:28)
> 	at org.gitlab.api.http.GitlabHTTPRequestor$1.fetch(GitlabHTTPRequestor.java:232)
> Caused: java.lang.Error
> 	at org.gitlab.api.http.GitlabHTTPRequestor$1.fetch(GitlabHTTPRequestor.java:239)
> 	at org.gitlab.api.http.GitlabHTTPRequestor$1.hasNext(GitlabHTTPRequestor.java:193)
> 	at org.gitlab.api.http.GitlabHTTPRequestor.getAll(GitlabHTTPRequestor.java:161)
> 	at argelbargel.jenkins.plugins.gitlab_branch_source.api.GitLabAPI.findProjects(GitLabAPI.java:168)
> 	at argelbargel.jenkins.plugins.gitlab_branch_source.api.GitLabAPI.findProjects(GitLabAPI.java:157)
> 	at argelbargel.jenkins.plugins.gitlab_branch_source.GroupProjectQuery.execute(GroupProjectQuery.java:21)
> 	at argelbargel.jenkins.plugins.gitlab_branch_source.ProjectQuery.execute(ProjectQuery.java:56)
> 	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceVisitor.visitSources(SourceVisitor.java:32)
> 	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceVisitor.visitSources(SourceVisitor.java:25)
> 	at argelbargel.jenkins.plugins.gitlab_branch_source.GitLabSCMNavigator.visitSources(GitLabSCMNavigator.java:399)
> 	at jenkins.branch.OrganizationFolder.computeChildren(OrganizationFolder.java:488)
> 	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:277)
> 	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:164)
> 	at jenkins.branch.OrganizationFolder$OrganizationScan.run(OrganizationFolder.java:968)
> 	at hudson.model.ResourceController.execute(ResourceController.java:97)
> 	at hudson.model.Executor.run(Executor.java:429)

![gitlabConnection](https://user-images.githubusercontent.com/4679329/62601346-7620c900-b8f1-11e9-97e8-a959ad03786c.png)

![Gitlab_OrganizationFolder_Connection](https://user-images.githubusercontent.com/4679329/62601354-79b45000-b8f1-11e9-8833-4b4df206a329.png)

### Problem description
- Scan Gitlab Projects of organization folder
- expecting List with projects containing a Jenkinsfile
- The folder is empty

### Additional Information
There was another gitlab connection configured for auto detecting the API Level. And all other projects in jenkins are using this Connection. But they also fail for getting the project list for organization folders. I think it was working fine, while v3 was still active in gitlab. But after an update of gitlab and the disappearing of v3 they can't find new projects anymore. But nobody cares because all needed projects are already integrated in jenkins.

Edit:
Also, the regarding classes like V4GitLabClientBuilder are only used in Test classes? Cant find them elsewhere using the github search.

**Comment by unix0r** [comment]
okay, the problem was found in another plugin...
closed.
