### ISSUE TITLE
Failed to update Gitlab commit status for project 'XXXX': HTTP 400 Bad Request

### ISSUE THREAD

**Issue by tkluza** [jenkinsci/gitlab-plugin#968]
After update to GitLab Community Edition **11.11.8** I get following error when doing POST with build status:

> Failed to update Gitlab commit status for project 'XXXX': HTTP 400 Bad Request

> Response body: {
>   "message" : {
>     "target_url" : [ "is blocked: Host cannot be resolved or invalid" ]
>   }
> }

Jenkins version: **2.176.2** and it is running in docker container. 
Gitlab plugin version **1.5.12**

Jenkinsfile:
```
pipeline {
  agent {
    docker {
      image 'trion/ng-cli-karma'
    }
  }
  options {
    gitLabConnection('xyz/')
    gitlabBuilds(builds: ['Checkout', 'Check tools', 'Install modules', 'lint', 'test', 'build'])
  }
  triggers {
    gitlab(
      branchFilterType: 'All',
      triggerOnPush: false,
      triggerOnMergeRequest: true,
      triggerOpenMergeRequestOnPush: "source",
      triggerOnAcceptedMergeRequest: true,
      triggerOnClosedMergeRequest: true,
      triggerOnNoteRequest: true,
      noteRegex: "Jenkins please retry a build",
      acceptMergeRequestOnSuccess: true,
      skipWorkInProgressMergeRequest: true,
      ciSkip: false,
      secretToken: "xyz",
      setBuildDescription: true,
      addNoteOnMergeRequest: true,
      addCiMessage: true,
      addVoteOnMergeRequest: true,
      includeBranchesSpec: "",
      excludeBranchesSpec: "",
      pendingBuildName: "Pending build name for pipeline",
      sourceBranchRegex: "",
      targetBranchRegex: "")
  }
  stages {
    stage('Checkout'){
        steps {
           checkout scm
        }
    }
    stage('Check tools') {
      steps {
        gitlabCommitStatus('Check tools') {
          sh 'node -v'
          sh 'npm -v'
          sh 'npm i -g @angular/cli'
          sh 'npm rebuild node-sass --force'
        }
      }
    }
    stage('Install modules') {
      steps {
        gitlabCommitStatus('Install modules') {
          sh 'npm install'
        }
      }
    }
    stage('Run lint') {
      steps {
        gitlabCommitStatus('lint') {
          sh 'npm run lint'
        }
      }
    }
    stage('Run tests') {
      steps {
        gitlabCommitStatus('test') {
          sh 'npm run test'
        }
      }
    }
    stage('Build') {
      steps {
        gitlabCommitStatus('build') {
          sh 'ng build --prod'
        }
      }
    }
  }
}
```
Errror itself:

`javax.ws.rs.BadRequestException: HTTP 400 Bad Request
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:197)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:50)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.$Proxy97.changeBuildStatus(Unknown Source)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.ResteasyGitLabClient.changeBuildStatus(ResteasyGitLabClient.java:60)
	at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.updateCommitStatus(CommitStatusUpdater.java:85)
	at com.dabsquared.gitlabjenkins.workflow.GitLabCommitStatusStep$GitLabCommitStatusStepExecution$1.onSuccess(GitLabCommitStatusStep.java:103)
	at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$SuccessAdapter.receive(CpsBodyExecution.java:377)
	at com.cloudbees.groovy.cps.Outcome.resumeFrom(Outcome.java:73)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:166)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:186)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:370)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:93)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:282)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:270)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:66)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

At this point can't tell where problem is: Gitlab itself or plugin? Any suggestions?

**Comment by arcadien** [comment]
Hi, i have the same issue, connecting Gitlab at 127.0.0.1.
