### ISSUE TITLE
Merge Request from Gitlab does not Merge but Checkout

### ISSUE THREAD

**Issue by AndreasBoehme** [jenkinsci/gitlab-plugin#98]
When Jenkins receives a Merge-Request from Gitlab, it seems not to do the requested merge, but a checkout of a revision from the last merge-attempt (rev a15f43ab9677d5e2273a3d64d8e4e3be2e2d8ad5). That last merge-attempt failed too, and was meant to merge from a different branch.
So, I get why it is failing, but I don't get why it behaves that way.

This seems like a bug, or am I missing something here?

P.S.: Jenkins ver. 1.612, GitLab Plugin v1.1.25, git 2.5.0 on Ubuntu 12.04.2 LTS with Oracle JDK 1.8, GitLab 7.4.3

Log from the Build-Console:
(at the line it says 'Checking out Revision...' it should be something like 'Merging...' which I've seen in working Builds, but don't have the logs anymore)
```
GitLab Merge Request #10 : git-versioning => dev
Building in workspace /var/lib/jenkins/jobs/MyProject_Build/workspace
Wiping out workspace first.
Cloning the remote Git repository
Cloning repository git@git.mycompany.com:i2subst/MyProject.git
 > /usr/lib/git-core/git init /var/lib/jenkins/jobs/MyProject_Build/workspace # timeout=10
Fetching upstream changes from git@git.mycompany.com:i2subst/MyProject.git
 > /usr/lib/git-core/git --version # timeout=10
 > /usr/lib/git-core/git -c core.askpass=true fetch --tags --progress git@git.mycompany.com:i2subst/MyProject.git +refs/heads/*:refs/remotes/origin/*
 > /usr/lib/git-core/git config remote.origin.url git@git.mycompany.com:i2subst/MyProject.git # timeout=10
 > /usr/lib/git-core/git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > /usr/lib/git-core/git config remote.origin.url git@git.mycompany.com:i2subst/MyProject.git # timeout=10
Pruning obsolete local branches
Fetching upstream changes from git@git.mycompany.com:i2subst/MyProject.git
 > /usr/lib/git-core/git -c core.askpass=true fetch --tags --progress git@git.mycompany.com:i2subst/MyProject.git +refs/heads/*:refs/remotes/origin/* --prune
Seen branch ...
...
Seen branch in repository origin/dev
Seen branch in repository origin/dev_INPD-374
Seen branch in repository origin/git-versioning
Seen branch in repository origin/master
Seen 8 remote branches
Checking out Revision a15f43ab9677d5e2273a3d64d8e4e3be2e2d8ad5 (origin/dev)
 > /usr/lib/git-core/git config core.sparsecheckout # timeout=10
 > /usr/lib/git-core/git checkout -f a15f43ab9677d5e2273a3d64d8e4e3be2e2d8ad5
FATAL: Could not checkout a15f43ab9677d5e2273a3d64d8e4e3be2e2d8ad5
hudson.plugins.git.GitException: Could not checkout a15f43ab9677d5e2273a3d64d8e4e3be2e2d8ad5
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$8.execute(CliGitAPIImpl.java:1867)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1060)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1276)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:610)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:532)
	at hudson.model.Run.execute(Run.java:1744)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: hudson.plugins.git.GitException: Command "/usr/lib/git-core/git checkout -f a15f43ab9677d5e2273a3d64d8e4e3be2e2d8ad5" returned status code 128:
stdout: 
stderr: fatal: reference is not a tree: a15f43ab9677d5e2273a3d64d8e4e3be2e2d8ad5

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1600)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:61)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$8.execute(CliGitAPIImpl.java:1859)
	... 10 more
```

Log from Jenkins logger:
```
Aug 05, 2015 6:47:21 PM INFO com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
WebHook called with url: 
Aug 05, 2015 6:47:21 PM FINE com.dabsquared.gitlabjenkins.GitLabWebHook
data: {
    "object_kind": "merge_request",
    "object_attributes":     {
        "id": 84,
        "target_branch": "dev",
        "source_branch": "git-versioning",
        "source_project_id": 93,
        "author_id": 56,
        "assignee_id": null,
        "title": "Git versioning",
        "created_at": "2015-08-05 16:47:20 UTC",
        "updated_at": "2015-08-05 16:47:20 UTC",
        "milestone_id": null,
        "state": "opened",
        "merge_status": "unchecked",
        "target_project_id": 93,
        "iid": 10,
        "description": "",
        "position": 0,
        "source":         {
            "name": "MyProject",
            "ssh_url": "git@git.mycompany.com:i2subst/MyProject.git",
            "http_url": "http://git.mycompany.com/i2subst/MyProject.git",
            "namespace": "RR",
            "visibility_level": 0
        },
        "target":         {
            "name": "MyProject",
            "ssh_url": "git@git.mycompany.com:i2subst/MyProject.git",
            "http_url": "http://git.mycompany.com/i2subst/MyProject.git",
            "namespace": "RR",
            "visibility_level": 0
        },
        "last_commit":         {
            "id": "1d6d8c86f7af75343ae529312fdd0fe9ec636d27",
            "message": "Remove trailing NL/LF from git-revision-string.\n",
            "timestamp": "2015-08-04T13:56:45+02:00",
            "url": "http://git.mycompany.com/i2subst/MyProject/commit/1d6d8c86f7af75343ae529312fdd0fe9ec636d27",
            "author":             {
                "name": "...",
                "email": "..."
            }
        }
    }
}
Aug 05, 2015 6:47:21 PM INFO com.dabsquared.gitlabjenkins.GitLabPushTrigger$2 run
MyProject_Build triggered for merge request.
Aug 05, 2015 6:47:21 PM INFO com.dabsquared.gitlabjenkins.GitLabPushTrigger$2 createActions
Trying to get name and URL for job: MyProject_Build using project MyProject_Build
Aug 05, 2015 6:47:21 PM INFO com.dabsquared.gitlabjenkins.GitLabPushTrigger$2 run
GitLab Merge Request detected in MyProject_Build. Triggering  #92
```

**Comment by pabloa** [comment]
That happen to me too.

**Comment by bassrock** [comment]
Did you delete the branch from the merge and then the commit disappear? Or did you do a rebase where the commit sha1 changed?
