### ISSUE TITLE
java.lang.NullPointerException on job triggering by comment on commit

### ISSUE THREAD

**Issue by sotona-** [jenkinsci/gitlab-plugin#989]
### Context
- **Gitlab plugin version**: 1.5.13
- **Gitlab version**: 11.10.1
- **Jenkins version**: 2.176.3
- **Job type**: Pipeline, Freestyle

### Java trace
[trace.txt](https://github.com/jenkinsci/gitlab-plugin/files/3686894/trace.txt)

### Problem description

Triggering by comment is working for merge request's comments but not for commit's. Tested on same repo/job. Log attached.

**Comment by pedro-ribeiro** [comment]
Hi.

What is the desired behaviour here? Does it make sense to trigger the job in this case?

**Comment by sotona-** [comment]
Hi.
Jenkins should trigger job.

**Comment by phallamen** [comment]
this problem also happened to me, it work only on MR's comments only.

**Comment by teragoon** [comment]
me too
```
java.lang.NullPointerException
	at com.dabsquared.gitlabjenkins.trigger.handler.note.NoteHookTriggerHandlerImpl.retrieveCauseData(NoteHookTriggerHandlerImpl.java:66)
	at com.dabsquared.gitlabjenkins.trigger.handler.note.NoteHookTriggerHandlerImpl.retrieveCauseData(NoteHookTriggerHandlerImpl.java:23)
	at com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler.createActions(AbstractWebHookTriggerHandler.java:86)
	at com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler.handle(AbstractWebHookTriggerHandler.java:54)
	at com.dabsquared.gitlabjenkins.trigger.handler.note.NoteHookTriggerHandlerImpl.handle(NoteHookTriggerHandlerImpl.java:36)
	at com.dabsquared.gitlabjenkins.trigger.handler.note.NoteHookTriggerHandlerImpl.handle(NoteHookTriggerHandlerImpl.java:23)
	at com.dabsquared.gitlabjenkins.GitLabPushTrigger.onPost(GitLabPushTrigger.java:506)
	at com.dabsquared.gitlabjenkins.webhook.build.NoteBuildAction$1.performOnPost(NoteBuildAction.java:57)
	at com.dabsquared.gitlabjenkins.webhook.build.BuildWebHookAction$TriggerNotifier.run(BuildWebHookAction.java:54)
```
